### ISSUE TITLE
gofumports depricated

### ISSUE THREAD

**Issue by Davincible** [ray-x/go.nvim#10]
From [this](https://github.com/mvdan/gofumpt/commit/38fc491470bae6f44e2d38b06277dd95cf1bdf97) commit: `As the v0.1.0 release notes describe, gofumports was always a bit of a
hack to allow IDEs to run both gofumpt and goimports at once. Now that
gopls exists and bundles both features in an efficient way, people
should just use that.`

It's not installing anymore with gofumpt, and therefore the goimport command does not work

Edit: I just noticed gopls has not been integrated at all yet, was that done for a reason?

**Comment by ray-x** [comment]
Is that means to do gofumports, will need to run goimports and gofumpt separately?

The reason did not bring in gopls is I have a separate setup for all LSP.  And `-remote=auto` of gopls does not work so well with that. (at least a few months back). B

TW, what you think may missing for gopls with default lspconfig? 

Lsplens might be something worth taking a look when neovim have better support for that.

**Comment by Davincible** [comment]
> Is that means to do gofumports, will need to run goimports and gofumpt separately?
yes

> The reason did not bring in gopls is I have a separate setup for all LSP. And `-remote=auto` of gopls does not work so well with that. (at least a few months back). B
Ahh okay, I have not setup gopls separately (myself, I did do `LspInstall go`), only use this plugin so far.
 
> Lsplens might be something worth taking a look when neovim have better support for that.
Haven't heard of that, sounds nice

**Comment by ray-x** [comment]
I used to use both vim-go and coc-go at once, they do not play well with remove/auto option and I have to startup 2 gopls instance. It is lots of memory if you have a large go project.
I will take a look if it is any better now and allow gopls to format code. And maybe some gopls features later if they were not included in lspconfig.

**Comment by Davincible** [comment]
That sounds amazing

**Comment by Davincible** [comment]
I'm using lsp-compe seems to work well

**Comment by ray-x** [comment]
lsp-compe will not startup a server.  But it worthwhile to check how it share gopls with other plugins.

**Comment by ray-x** [comment]
If you'd like to use gopls to format the code, Please enable gopls format by:

```lua
 require('go').setup(cfg = {
  lsp_cfg = false, -- true: apply go.nvim non-default gopls setup
  lsp_gofumpt = false, -- true: set default gofmt in gopls format to gofumpt
})
```

And
 
```
-- Format on save
vim.api.nvim_exec([[ autocmd BufWritePre *.go :silent! lua require('go.format').gofmt() ]], false)
-- or
-- Import on save
vim.api.nvim_exec([[ autocmd BufWritePre *.go :silent! lua require('go.format').goimport() ]], false)
```
