### ISSUE TITLE
No split pane with `:GoRun` results or `:GoDoc`

### ISSUE THREAD

**Issue by robbyki** [ray-x/go.nvim#100]
Not getting any panes opened when I run `:GoRun`. Same thing happens with `:GoDoc`. `:GoBuild` works fine and does generate the binary. Not sure where my settings are preventing the editor from opening up the result of `go run .` in a different buffer. This is my basic setup:
```
    use({
        "ray-x/go.nvim",
        config = function()
            require("go").setup({
                verbose = false,
                run_in_floaterm = true,
            })
        end,
    })
```

```
nvim_lsp.gopls.setup({
    -- lsp_cfg = false,
    on_attach = on_attach,
    capabilities = capabilities,
    root_dir = require("lspconfig").util.root_pattern(".git", "go.mod", "."),
    flags = {
        debounce_text_changes = 150,
    },
    cmd = { "gopls", "serve" },
    settings = {
        gopls = {
            experimentalPostfixCompletions = true,
            analyses = {
                nilness = true,
                simplifyrange = true,
                unusedwrite = true,
                unusedparams = true,
                shadow = true,
            },
            staticcheck = true,
        },
    },
})
```
![gorun](https://user-images.githubusercontent.com/1027357/159487630-afcbeac3-c4be-42fc-b106-e35de159008f.gif)

**Comment by ray-x** [comment]
Do you have `guihua.lua` installed?

**Comment by robbyki** [comment]
Still getting same result after installing it.

**Comment by robbyki** [comment]
![gorun-manual](https://user-images.githubusercontent.com/1027357/159522845-5880f6ab-c36f-45ee-9f71-41365dacaddf.gif)

**Comment by ray-x** [comment]
I added a sample init.lua

https://github.com/ray-x/go.nvim/blob/master/playground/init.lua

Hope it works for you
Also you can check the output of `:checkhealth go` and see if there are any warnings/errors.

**Comment by robbyki** [comment]
thank you. seems to work now with the float option. here is a dumb question...what's the recommended way to close the floating window?

**Comment by robbyki** [comment]
thanks @jaredmcqueen.
