### ISSUE TITLE
Use lspconfig to register user commands

### ISSUE THREAD

**Issue by etrnal70** [ray-x/go.nvim#103]
Use lspconfig functionality to register custom commands. Example can be seen in https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/rust_analyzer.lua.

This will avoid Go-related commands showing up when not opening Go project.

(While this can be prevented by using something like packer.nvim's lazy loading, i think this is not ideal. Also i see that plugins like rust-tools use lspconfig approach)

**Comment by ray-x** [comment]
I only enable go.nvim when filetype is `go` or `mod`
Also this plugin does not rely on lsp.

**Comment by etrnal70** [comment]
I see, seems reasonable. I'll use the lazy loading method then. Thanks !
