### ISSUE TITLE
Key Bindings

### ISSUE THREAD

**Issue by NicholasKao1029** [ray-x/go.nvim#104]
Hi love the plugin, very feature rich and enjoyable to use!

I am having an issue with my go setup. I use telescope and have bound `<Leader> ff` to use telescope for project movement. However when I work in go files It seems to be bound to `gofmt` (based on empirical evidence). I am having a hard time resolving this as I cannot find documentation if the default key bindings for `go.nvim` are responsible or some other quirk of my config. 

Was wondering if you could help me out here.

Optimally I would like to unbind `<Leader> ff` off of `gofmt` and instead use my usually set up of triggering Telescope. Or I could utilize information regarding keybindings and `go.nvim` and explore from there.

**Comment by ray-x** [comment]
The keybinding is attached to vim buffer in lsp on_attach function.
If you want to override the keymapping you can provide your own lsp on_attach. You can config on_attach with `lsp_on_attach`.
Also, I think fmt is mapped to `<Space>ff`, `<Leader> ff` might be bonded by other plugins.

**Comment by NicholasKao1029** [comment]
ahhh my Leader key is `<Space>` so thats where the collision happened. I will attempt to provide my on configs.
Thanks for the reply!
