### ISSUE TITLE
Getting a build error when testing individual tests

### ISSUE THREAD

**Issue by rogeruiz** [ray-x/go.nvim#105]
Here's my `launch.json` file.

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Test Current File",
      "type": "go",
      "request": "launch",
      "mode": "test",
      "program": "${relativeFileDirname}",
      "showLog": true
    }
  ]
}
```

When I go into a file, I am getting the following error message. I've removed unnecessary information from the following output.

```console
Build Error: go test -c -o /path/to/project/__debug_bin -gcflags all=-N -l pkg/handlers/internalapi
package pkg/handlers/internalapi is not in GOROOT (/nix/store/1168hmr97r5lk8d7y0hinp3vf42sq4r2-go-1.17.7/share/go/src/pkg/handlers/internalapi) (exit status 1)
```

The error I'm seeing is that `go test` can't seem to find my package because it's not a relative path? I am able to successfully create the binary manually with the following command, note the relative path.

```sh
go test -c -o /path/to/project/__debug_bin -gcflags all=-N -l ./pkg/handlers/internalapi
```

Any help would be appreciated, thank you!

Also, to note, I am using the same `launch.json` file for VSCode and am able to get the debugger running without issue.

**Comment by ray-x** [comment]
one quick workaround is using

```
      "program": "./${relativeFileDirname}",
```
It is more an upstream issue from nvim-dap.

**Comment by rogeruiz** [comment]
@ray-x Thanks for the suggestion. I had tried that. and tried it again just now. It seems like I needed to restart Neovim in order to get it working properly. I'll close this issue now. thanks again.
