### ISSUE TITLE
GoDebug testopts completion arguments are wrong after latest change

### ISSUE THREAD

**Issue by rodrigc** [ray-x/go.nvim#106]
@ray-x  After this change: https://github.com/ray-x/go.nvim/commit/ed3dfb85b2e4a559f3d4f9c98a83b8a6a9475e65, the command-line completion for `:GoDebug` still lists the old arguments.
I think you need to change `testopts` here to the new arguments: https://github.com/ray-x/go.nvim/blob/4c66365aa27f7b3d62f1266ca65afdd66496f4d7/lua/go.lua#L232

**Comment by ray-x** [comment]
Yes, I am working on https://github.com/ray-x/go.nvim/pull/102 and it should solve the issue you mentioned.
But do not have enough time to verify my changes. May need a few more days before I can get this fixed.

**Comment by ray-x** [comment]
The arguments are updated.
