### ISSUE TITLE
GoAddTag does not support transform flag

### ISSUE THREAD

**Issue by pengux** [ray-x/go.nvim#108]
I was trying to use `GoAddTag` with camelCase instead of the defautl snake_case but couldn't figure out how to do it successfully. Looking through the code, it could be because of the typo for `tag_transform` and `tag_transfer`

https://github.com/ray-x/go.nvim/blob/4c66365aa27f7b3d62f1266ca65afdd66496f4d7/lua/go/tags.lua#L22
https://github.com/ray-x/go.nvim/blob/4c66365aa27f7b3d62f1266ca65afdd66496f4d7/lua/go.lua#L12

**Comment by ray-x** [comment]
It should be fixed in the latest version.
