### ISSUE TITLE
GoTestFunc dose not work in symbolic link directory

### ISSUE THREAD

**Issue by gloomyzerg** [ray-x/go.nvim#110]
<img width="670" alt="WX20220415-151026@2x" src="https://user-images.githubusercontent.com/1195510/163537557-df77e235-f203-40f8-9cd7-b219cb930eb0.png">

GoTestFunc  get full file path using  ```local fpath = vim.fn.expand("%:p:h")```. [source code](https://github.com/ray-x/go.nvim/blob/63d81679d06bff33e3f24bca76f513cadac2f64c/lua/go/gotest.lua#L169)

It got this result
```
/Users/kwazii/www/tmp/test
```
Run :GoTestFunc Result:
<img width="1423" alt="image" src="https://user-images.githubusercontent.com/1195510/163538110-8273ad33-15e9-4f0c-84dc-4b26ddcddcee.png">

It's like 
```
go test /Users/kwazii/www/tmp/test/... -count=1
```

I hope it will be
```
go test /www/tmp/test/... -count=1
or
go test ./xxx/xxx -count=1
```
<img width="1077" alt="WX20220415-151934@2x" src="https://user-images.githubusercontent.com/1195510/163538645-c006b08a-004e-43e0-9383-29df28df0b61.png">

Temporary workaround I used
```
  local fpath = "./" .. vim.fn.expand("%:h")
```

GoTest, GoTestFile, GoTestPkg has the same problem

**Comment by ray-x** [comment]
Thanks, I think the relative path is the best solution so far.

**Comment by ray-x** [comment]
@gloomyzerg Could you check if the latest version works for you?

**Comment by gloomyzerg** [comment]
@ray-x solved, thanks

**Comment by ray-x** [comment]
In fact, when I create a symbolic link to a go project, the current dir always jumps to the original project folder. So I could not really reproduce the issue you saw.

**Comment by gloomyzerg** [comment]
Going to a symlink on MacOS doesn't auto jump to the original directory.

**Comment by gloomyzerg** [comment]
I will try to fix this and create a PR

**Comment by ray-x** [comment]
Hi, @gloomyzerg 
Do you still see this issue?

**Comment by gloomyzerg** [comment]
I tried to fix it, But I didn't get the expected result.

**Comment by ray-x** [comment]
For me, using the mimium vimrc from playground folder, with following folder link
<img width="615" alt="image" src="https://user-images.githubusercontent.com/1681295/179498373-7a25f57f-8aba-4d10-af76-853167565dfd.png">

Once I open neovim and `:cd /tmp/go`, neovim will change to the original position. 
And the `GoTestFunc` will use something like this:

`"go", "test", "-v", "-run", "'^TestCat$'", "./fun" `

I do not see anything wrong here

**Comment by gloomyzerg** [comment]
The problem is not in neovim, but which directory you are in when you start neovim
No problem if you start neovim in the original directory
In your example, start neovim in the /home/ray/lsp_test/go directory has no problem, but if you start in the /tmp/go directory, you will have this problem.
Now `GoTestFunc` is ok, the problem appears on `GoTest`, `GoTestFile`, `GoTestPkg`

**Comment by gloomyzerg** [comment]
I think this problem is not easy to solve, because neovim always gets the original directory
My current solution is to avoid into the symlink directory  use `alias cd = "cd -P"`

**Comment by ray-x** [comment]
But currently, the `go test` is run with relative path,  e.g.
`go test -v -run '^TestCat$' ./fun`
I think it should work...

**Comment by gloomyzerg** [comment]
Sorry I didn't update to the latest version, I forgot that I used the specified commit version in packer.
Now they can work except `GoTest`.
I think this issue can be closed.
