### ISSUE TITLE
fixplurals error!

### ISSUE THREAD

**Issue by crusj** [ray-x/go.nvim#111]
E5108: Error executing lua ...e/nvim/site/pack/packer/start/go.nvim/lua/go/reftool.lua:88: Vim(execute):E121: Undefined variable: cd
stack traceback:
        [C]: in function 'cmd'
        ...e/nvim/site/pack/packer/start/go.nvim/lua/go/reftool.lua:88: in function 'fixplurals'
        [string ":lua"]:1: in main chunk

**Comment by ray-x** [comment]
it was fixed by using my own version of fixpurals with treesitter instead of go ast.
