### ISSUE TITLE
textDocument/codeLens is not supported issues

### ISSUE THREAD

**Issue by RakerZh** [ray-x/go.nvim#113]
Error detected while processing BufEnter Autocommands for "<buffer=1>":
method textDocument/codeLens is not supported by any of the servers registered for the current buffer

**Comment by ray-x** [comment]
which gopls version you are using? 
By default the codelens is enabled. If your gopls does not support codelens, please set
```
  lsp_codelens = false,

```

**Comment by meinside** [comment]
Hi, I do too have the same issue here.
neovim's version is v0.8.0-dev+40-g843d9223a, and gopls' version is v0.8.3 (supports codelens).
Is there any other configuration for enabling codelens?

**Comment by ray-x** [comment]
you can set `lsp_codelens = false` to disable codelens.
But it should be enable by default in latest gopls.

**Comment by robbyki** [comment]
Same here on `v0.7.0`. I've had to disable codelens for now.

**Comment by rainbowhxch** [comment]
For me, reinstalling go.nvim solved this issue.

**Comment by ray-x** [comment]
Please enable `lsp_cfg` by setting `lsp_cfg=true`

And it will enable the codelens here:

https://github.com/ray-x/go.nvim/blob/a8000badf6d55b2f90af597da6ca589ac23130e3/lua/go/gopls.lua#L193-L198

**Comment by akinsho** [comment]
@ray-x in my case this is already enabled. My config looks like
```lua
  local ok, path =  pcall(require, 'nvim-lsp-installer.path')
  local gopls_cmd
  if ok then
    local install_root_dir = path.concat { vim.fn.stdpath 'data', 'lsp_servers' }
    gopls_cmd = { install_root_dir .. '/go/gopls' }
  end
  require('go').setup {
    gopls_cmd = gopls_cmd,
    max_line_len = 100,
    goimport = 'gopls',
    icons = false,
    lsp_cfg = {
      codelenses = {
        generate = true,
        gc_details = false,
        test = true,
        tidy = true,
      },
      analyses = {
        unusedparams = true,
      },
    },
    lsp_gofumpt = true,
    lsp_keymaps = false,
    lsp_on_attach = as.lsp.on_attach,
    lsp_diag_virtual_text = false,
    dap_debug_keymap = false,
    textobjects = false,
  }
```

To be clear, the code lenses *do work* I can see them in each file. The problem is that it is erroring the first time I open a go file. Which makes me think that something is running too early since the error is immediate, but I work in a monorepo, and it takes like 3-4secs for the lsp to be setup. So I think it tries to add codelenses too early. I think they should only be refreshed/the autocmd created when on attach is first run

**Comment by ray-x** [comment]
can anyone confirm the issue fixed?

**Comment by akinsho** [comment]
I'm not seeing the issue anymore 👍🏾

**Comment by mawkler** [comment]
I'm also seeing this error each time I save a Go file after I have also opened some other file type (for instance Markdown) that uses some other language server (in my case [typos-lsp](https://github.com/tekumara/typos-lsp)).

My guess is that go.nvim is trying to trigger the code lense for `typos-lsp` as well even though it doesn't support it.
