### ISSUE TITLE
Can't close guihua floatterm if I run unit tests

### ISSUE THREAD

**Issue by alesbrelih** [ray-x/go.nvim#118]
How can I close the floatterm from guihua?

I've tried settings:

```    
    use {'ray-x/guihua.lua',
        run = 'cd lua/fzy && make',
        config = function()
            require('guihua.maps').setup({
                maps = {
                    close_view = '<C-k>',
                }
            })
        end
    }

```

But it doesn't seem to work using the C-k combination. I've even tried using the defaults: <C-e> but it doesn't work as well. What am I missing here?

**Comment by alesbrelih** [comment]
I've solved this like this:

```
  vim.cmd(
    [[command! -nargs=* -complete=custom,v:lua.package.loaded.go.package_complete GoFloatClose lua require("go.term").close()]]
  )
```

Should I prepare a pull request? Or is there another way?

Thanks for this plugin again!

**Comment by ray-x** [comment]
Please create a PR, thanks.
Guihua can close the float buffer with the keymap. But close float term is different and I did not provide a keymap for it.
