### ISSUE TITLE
GoAlternate command

### ISSUE THREAD

**Issue by alphatroya** [ray-x/go.nvim#12]
vim-go has a handy [:GoAlternate](https://github.com/fatih/vim-go/blob/13108b0e16005abeecbc631022dc81014905a326/doc/vim-go.txt#L687) command for transition to/from current test file. I think this feature will be useful here as well.

**Comment by ray-x** [comment]
Thanks for your recommandation. 
"GoAlt" commands were added. Please check if it works for you.

**Comment by alphatroya** [comment]
It was fast, thx! It works perfectly!
