### ISSUE TITLE
GoAddTag error

### ISSUE THREAD

**Issue by etrnal70** [ray-x/go.nvim#120]
Got an error on latest master while trying to use `:GoAddTag json`

```
E5108: Error executing lua .../share/nvim/site/pack/packer/opt/go.nvim/lua/go/tags.lua:46: bad argument #1 to 'insert' (table expected, got nil)
stack traceback:
        [C]: in function 'insert'
        .../share/nvim/site/pack/packer/opt/go.nvim/lua/go/tags.lua:46: in function 'modify'
        .../share/nvim/site/pack/packer/opt/go.nvim/lua/go/tags.lua:91: in function 'add'
        [string ":lua"]:1: in main chunk
```

Using latest master on `c89418a`

**Comment by ray-x** [comment]
Can you share the struct. Also is your gomodifytags in latest version?

**Comment by etrnal70** [comment]
Pretty much every struct giving that error though. Yes i already do `:GoUpdateBinaries` to make sure that it is up to date

**Comment by ray-x** [comment]
I can not reproduce this issue with everything set to the latest.
Also tags.lua:46 related to case when transform flag is set.
Also the tag function is unit tested in `go_tags_spec.lua` for each integration and should support nvim 0.6.1 and up.

**Comment by etrnal70** [comment]
Looks like i set a wrong value for `tag_transform` in my config and uncovered a bug 😅. Please check my PR
