### ISSUE TITLE
gopls complains about AddImportArgs.ImportPath when saving files

### ISSUE THREAD

**Issue by meinside** [ray-x/go.nvim#124]
Hi,

with following configuration:

```lua
use {
  'ray-x/go.nvim',
  config = function()
    require'go'.setup {
      gofmt = 'gopls',
    }
    vim.api.nvim_create_autocmd('BufWritePre', {pattern = '*.go', callback = require('go.format').goimport})
  end
}
```

I see this kind of error message on file saves:

```
gopls: 0: json: cannot unmarshal object into Go struct field AddImportArgs.ImportPath of type string
```

Strange thing is, when running :GoImport command manually, it just works as expected.

When I replace `callback = require('go.format').goimport` with `callback = require('go.format').gofmt`,
files are saved without any error message.

I'm experiencing this issue since 1 or 2 days ago.
Maybe I missed something?

* neovim version: both on `v0.7.0` and `v0.8.0-dev+3101-ge50b1fe60`
* go version: `v1.18.2`
* gopls version: `v0.8.3`
* goimports version: latest version installed with :GoUpdateBinaries command

**Comment by meinside** [comment]
FYI, I tested with other versions (go 1.17, 1.18.1 and gopls 0.8.2) but the same.

I still don't get what's the difference, but will try finding out and let you know.

**Comment by ray-x** [comment]
Thanks. As I can not reproduce and the error is from gopls. Can not offer much help.
But you can check the logs from neovim ~/.cache/nvim/lsp.log to see if there is any useful info.

**Comment by meinside** [comment]
Thanks for the tip! But unfortunately, I cannot see useful logs there.

**Comment by meinside** [comment]
I found out that replacing the line in my config:
```
vim.api.nvim_create_autocmd('BufWritePre', {pattern = '*.go', callback = require('go.format').goimport})
```
with the following line (as in the [README](https://github.com/ray-x/go.nvim#code-format)):
```
vim.api.nvim_exec([[autocmd BufWritePre *.go :silent! lua require('go.format').goimport()]], false)
```
fixes my problem.

I still don't get what made the difference recently, but I will stick with the vim script version for now.
