### ISSUE TITLE
I want to see the print.

### ISSUE THREAD

**Issue by j2501987804** [ray-x/go.nvim#127]
neovim0.7
GO1.15
Run: gorun, you can't see the print output
![image](https://user-images.githubusercontent.com/41771911/168574477-9dc2ba0b-f581-496b-a2e8-fe934deb217a.png)

**Comment by ray-x** [comment]
You can either
1> open quickfix by running `copen`, you will see the result.
2> run with floaterm by `GoRun main.go -F` ( you need guihua.lua installed)
