### ISSUE TITLE
gofmt() autocommand leaves modified buffer

### ISSUE THREAD

**Issue by jhillyerd** [ray-x/go.nvim#128]
Hi, I've tried adding gofmt on write with either:

```lua
local group = vim.api.nvim_create_augroup('go-nvim', {})
vim.api.nvim_create_autocmd('BufWritePre', {
  pattern = "*.go", 
  callback = require('go.format').gofmt,
  group = group,
})
```
or

```viml
  augroup GO
    autocmd!
    autocmd BufWritePre *.go :silent! lua require('go.format').gofmt()
  augroup END
```

Both methods seem to write the unformatted version, then leave me with a formatted but modified buffer I need to save a second time.  Is this expected?

**Comment by ray-x** [comment]
This should have been fixed.

**Comment by dnjp** [comment]
I'm also experiencing this issue so I'm not sure https://github.com/ray-x/go.nvim/commit/dbf0094f25a188efc1ebdec4da697fd219053015 completely fixed the issue. This is the only way I got it to write the buffer properly:

```
local group = vim.api.nvim_create_augroup('go-nvim', {})
vim.api.nvim_create_autocmd('BufWritePre', {
	pattern = "*.go",
	callback = function()
		require('go.format').gofmt()
		vim.cmd('write')
	end,
	group = group,
})
```

I have go.nvim updated as well:

```
```
