### ISSUE TITLE
Consistency of vim commands

### ISSUE THREAD

**Issue by urandom** [ray-x/go.nvim#13]
I've noticed that a few commands, like `Gfstruct` only start with a `G`, whereas the majority of the commands start with `Go`. A few of the `Go` prefixed commands are also not camelcased: `Gofmt` for example. Would it be possible to normalize all of these commands, so that they all start with `Go`, and they are all camelcased? Also, most of the commands are quite expressive with their name, but some, like `Gfstruct` are rather succinct. Would it be possible to name them more expressively as well, such as `GoFillStruct`?

**Comment by ray-x** [comment]
Yes. Good suggestion. 
I renamed some of the commands in the new version.

**Comment by urandom** [comment]
@ray-x
Thanks for making them consistent. Now only one seems to be left not matching the rest - `Goiferr` - it's not camel cased :)

**Comment by ray-x** [comment]
Thanks, that was fixed in latest commit.
