### ISSUE TITLE
GoFmt/Formatting on save causes characters to disappear

### ISSUE THREAD

**Issue by andrewcohen** [ray-x/go.nvim#131]
When calling `lua require('go.format').gofmt()` with new imports, characters are removed from the code after format. However `lua require('go.format').goimports()` is okay. The same thing happens when I save the file, however my autocmd is setup for `goimport`, not `gofmt`. (see video)

I was able to bisect to find that https://github.com/ray-x/go.nvim/commit/8b7d2c3eda972a3e00ed8844532e24502e0f3282 is where my issue began, and reverting it fixes the issue for me.

My plugin setup:
```
  use {
    'ray-x/go.nvim',
    config = function()
      require('go').setup({
        tag_transform = 'camelcase',
      })
    end
  }

vim.api.nvim_exec([[ autocmd BufWritePre *.go :silent! lua require('go.format').goimport() ]], false)
```

Edit - I have this in my lsp on_attach which may be causing additional trouble:
```
    if client.resolved_capabilities.document_formatting then
      vim.api.nvim_command [[augroup Format]]
      vim.api.nvim_command [[autocmd! * <buffer>]]
      vim.api.nvim_command [[autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting_seq_sync()]]
      vim.api.nvim_command [[augroup END]]
    end
```

https://user-images.githubusercontent.com/1016046/170839507-e96d5514-2cc8-4e1d-815a-44d2da9a20d5.mov

.

**Comment by ray-x** [comment]
How about you call `lua require('go.format').goimport() ` directly?
I think there are other hooks to BufWritePre/Post in your system and multiple writes happened at same time.

**Comment by djdv** [comment]
I was also having this problem with a similar setup.

>I think there are other hooks to BufWritePre/Post in your system and multiple writes happened at same time.

This lead me to the solution.

It makes sense, but I knew that this was not true for my config.
So what I did was change the autocmd. Giving it a `desc`: 
```lua
-- (config shortened for brevity)
vim.api.nvim_create_autocmd("BufWritePre", {
	callback = function()
		require('go.format').goimport()
	end,
	desc = "formatter"
})
```
I then loaded up some Go sources, and checked `:autocmd BufWritePre`, which showed the command.
Then I switched buffers back and forth and checked again. This time seeing the autocommand twice.
I'm not sure what trigger is causing it, but I assume the LSP's `on_attach` method is being called multiple times which in my case is registering that autocmd.

To fix this I just wrapped it in an augroup.
```lua
local fmt_augroup = vim.api.nvim_create_augroup("lsp_fmt", { clear = true })
vim.api.nvim_create_autocmd("BufWritePre", {
	group = fmt_augroup,
	callback = function()
		require('go.format').goimport()
	end
})
```
I assume we still get called multiple times, but we clear the augroup each time, so it should never call gofmt more than once for the same buffer (which it must have been doing before - even with `lsp_fmt_async = false`)

***
<details>
<summary>For posterity here's my whole `on_attach`</summary>

```lua
M.on_attach = function(client, bufnr)
	local function buf_set_option(...) vim.api.nvim_buf_set_option(bufnr, ...) end

	-- Enable completion triggered by <c-x><c-o>
	buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')
	M.set_mappings(bufnr)
	M.set_commands(client)
end

function M.set_commands(client)
	local gofmt -- TODO: we shouldn't lazy load manually
	local fmt_augroup = vim.api.nvim_create_augroup("lsp_fmt", { clear = true })
	vim.api.nvim_create_autocmd("BufWritePre", {
		group = fmt_augroup,
		desc = "lsp formatter",
		callback = function()
			local ft = vim.bo.filetype
			if ft == "go" or ft == "gomod" then
				if gofmt == nil then
					gofmt = require('go.format').goimport
				end
				gofmt()
			else
				vim.lsp.buf.format()
			end
		end
	})

	-- TODO: check all capabilities #lazy
	if client.server_capabilities.codeLensProvider ~= nil then
		vim.api.nvim_create_autocmd({
			'BufEnter',
			'CursorHold',
			'InsertLeave'
		}, {
			callback = vim.lsp.codelens.refresh
		})
	end
end
```
</details>

**Comment by ray-x** [comment]
Thanks, that is a good suggestion.

**Comment by andrewcohen** [comment]
>I think there are other hooks to BufWritePre/Post in your system and multiple writes happened at same time.

This was 100% my issue which caused the strange behavior.

Even with @djdv suggestion, I do still have an issue where after save with format changes, I end up with unsaved buffer changes (`[+]`). I'm not sure if that is normal for async formatting in general, or if it is a further issue with my setup.

Feel free to close this issue as i'm not sure its the fault of this plugin

**Comment by ray-x** [comment]
I think that is caused by neovim API changs. you should use sync format if you see anything wrong.
