### ISSUE TITLE
Calling require("go.format").goimport() in BufWritePre causes changes after the write

### ISSUE THREAD

**Issue by urandom** [ray-x/go.nvim#132]
Could we change the following to `async = false`?  Using the goimports function with gopls inside that above autocommand will cause inconsistencies because of the current async action

https://github.com/ray-x/go.nvim/blame/f5f5c411656a84fbee3904a7b50a9c2f46ed6964/lua/go/format.lua#L134

**Comment by ray-x** [comment]
The setup flag is `lsp_fmt_async`
Maybe I should set it to false by default. Just for consistency.

**Comment by urandom** [comment]
That option is not used for that specific usage of the command, which is linked in the description.

**Comment by urandom** [comment]
looks like the latest one fixes the problem, thx
