### ISSUE TITLE
`GoCheat` causing `nvim_open_win` Error

### ISSUE THREAD

**Issue by robbyki** [ray-x/go.nvim#134]
Getting the below whenever I try to run `GoCheat` with cursor on a keyword:

```
E5108: Error executing lua ...ite/pack/packer/start/guihua.lua/lua/guihua/floating.lua:60: 'height' key must b
e a positive Integer
stack traceback:
        [C]: in function 'nvim_open_win'
        ...ite/pack/packer/start/guihua.lua/lua/guihua/floating.lua:60: in function 'floatbuf'
        ...im/site/pack/packer/start/guihua.lua/lua/guihua/view.lua:57: in function 'initialize'
        ...ite/pack/packer/start/guihua.lua/lua/guihua/textview.lua:96: in function 'initialize'
        ...im/site/pack/packer/start/guihua.lua/lua/middleclass.lua:135: in function 'new'
        ...are/nvim/site/pack/packer/start/go.nvim/lua/go/chtsh.lua:23: in function 'run'
        [string ":lua"]:1: in main chunk
```

**Comment by ray-x** [comment]
Is a specific keyword break the plugin or any keyword?

**Comment by robbyki** [comment]
Any keyword. I'm pretty sure it has something to do with how it's quoting. I can reproduce at cli with `curl cht.sh/go/Split?T` versus `curl "cht.sh/go/Split?T"` which does work.

![gocheat](https://user-images.githubusercontent.com/1027357/171846810-3539b0c1-5590-49fa-b67f-4db0d7ad3042.gif)

**Comment by ray-x** [comment]
I think you may use `fish`. I updated the plugin and it should work for you now.
