### ISSUE TITLE
Latest nvim-dap-ui 1.0.0 and 1.0.1 contains breaking changes

### ISSUE THREAD

**Issue by sradevel** [ray-x/go.nvim#137]
the latest nvim-dap-ui release 1.0.0 upwards contains breaking changes, which cause go.nvim to error out when start debugging.

see [nvim-dap-ui changes](https://github.com/rcarriga/nvim-dap-ui/compare/v0.34.4...v1.0.0)

temporary fix, revert back to version 0.34.4

e.g. with packer.nvim
```
...
use {"rcarriga/nvim-dap-ui", commit="85b266e20e45004a86b51f13293129b01e2dcf3b"}
...
```

**Comment by ray-x** [comment]
Pushed a fix should work now
