### ISSUE TITLE
GoTestFunc set regex to match start not end

### ISSUE THREAD

**Issue by zenyusy** [ray-x/go.nvim#143]
hello ray,

when calling GoTestFunc, i primarily want to test **one** specific function only, so i hope the match is unique.

currently the func name regex  has "^" but lacks "$", so calling GoTestFunc around `TestFoo` will  trigger `TestFooBar` as well.

( https://github.com/ray-x/go.nvim/blob/master/lua/go/gotest.lua#L334 )

**Comment by ray-x** [comment]
Should be fixed now

**Comment by zenyusy** [comment]
sorry to revisit this closed issue, but do we really need (single) quotes around the regex string ?
