### ISSUE TITLE
Dap UI not working

### ISSUE THREAD

**Issue by ray-x** [ray-x/go.nvim#145]
This check doesn't work for me, it keeps opening windows indefinitely

https://github.com/ray-x/go.nvim/blob/d402d9cbf9e62b4c8e9b8ced3d67db18cfcdf923/lua/go/dap.lua#L272-L275

_Originally posted by @Davincible in https://github.com/ray-x/go.nvim/issues/139#issuecomment-1170593917_

**Comment by ray-x** [comment]
@Davincible 
What is your workflow? I checked debug with unit test it looks good.
Also just to be sure you are using latest dap-ui, right?

**Comment by Davincible** [comment]
Well I haven't actually gotten debugging to work yet, everytime I set a breakpoint and run `GoDebug` (without any arguments, just like that), I get `could not remove /tmp/test/go/__debug_bin: remove /tmp/test/go/__debug_bin: no such file or directory
`

**Comment by Davincible** [comment]
Everything should be latest, according to packer

**Comment by Davincible** [comment]
Just replicated everything with a very minimal config, same behavior for both.

```lua
local execute = vim.api.nvim_command
local fn = vim.fn
 
local install_path = fn.stdpath("data") .. "/site/pack/packer/start/packer.nvim"
 
if fn.empty(fn.glob(install_path)) > 0 then
        fn.system({ "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path })
        execute("packadd packer.nvim")
end
 
return require("packer").startup(function()
        -- Packer can manage itself    
        use("wbthomason/packer.nvim")
 
        -- Nvim Treesitter
        use({ "nvim-treesitter/nvim-treesitter", run = ":TSUpdate" })
        use("kyazdani42/nvim-web-devicons")
 
        -- Golang
        use({
                "ray-x/go.nvim",
                requires = {
                        "mfussenegger/nvim-dap", -- Debug Adapter Protocol
                        "rcarriga/nvim-dap-ui",
                        "theHamsta/nvim-dap-virtual-text",
                        "ray-x/guihua.lua",
                },
        })
 
        local path = require("nvim-lsp-installer.core.path")
        local install_root_dir = path.concat({ vim.fn.stdpath("data"), "lsp_servers" })
        require("go").setup({
                gopls_cmd = { install_root_dir .. "/go/gopls" },
        })
 
        -- Nvim LSP
        use({ "neovim/nvim-lspconfig", "williamboman/nvim-lsp-installer", after = "go.nvim" })
end)
```

**Comment by ray-x** [comment]
Your config look good. I pushed an update. Could you check if it works for you?

**Comment by Davincible** [comment]
You updated the readme? I tried `GoDebug` and `GoDebug -c, -r, -p`, all same result.

**Comment by ray-x** [comment]
Sorry, the merge was not successful, re-push a new version.
You can use init.lua in playground folder to run some tests.

**Comment by Davincible** [comment]
Yeeaahh it works now. But also the reason the UI keeps double opening is because the session failed to launch, and thus the check `is session running` fails, causing the UI to open again.

I can start a debug session now successfully. But if you just set your cursor on line 1 (package definition), it will fail to start the debug session as expected, but open the UI. If you then run GoDebug again, it doesn't detect a running session and re-opens another UI

**Comment by ray-x** [comment]
Filed an issue here:
https://github.com/rcarriga/nvim-dap-ui/issues/115
Also, commit a check for that as well.

**Comment by ray-x** [comment]
Close this now. Most parts of the issue are solved.
