### ISSUE TITLE
GoRun doesn't work at nvim 0.6

### ISSUE THREAD

**Issue by AllenDang** [ray-x/go.nvim#15]
Invoke :GoRun result like this
```
|| 
|| go run: no go files listed
|| 
||
```
Here is my nvim --version
```
NVIM v0.6.0-dev+1518-g02bf251bb
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210714-39663-lqn3eb/build/config -I/tmp/neovim-20210714-39663-lqn3eb/src -I/usr/local/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210714-39663-lqn3eb/build/src/nvim/auto -I/tmp/neovim-20210714-39663-lqn3eb/build/include
编译者 allendang@MacBook-Pro.local

Features: +acl +iconv +tui
See ":help feature-compile"

     系统 vimrc 文件: "$VIM/sysinit.vim"
         $VIM 预设值: "/usr/local/Cellar/neovim/HEAD-02bf251/share/nvim"

Run :checkhealth for more info
```

**Comment by ray-x** [comment]
Thanks, there was a bug in the plugin. Fixed

**Comment by AllenDang** [comment]
@ray-x Thanks it works well if the project is executable. One more scenario is for a library project which contains examples inside, like this folder structure.
```
root
  - examples
    - sample1
      - main.go <- with this file is opened, run GoRun should run main.go, not the root project
  - lib.go
```

This could be done by running a grep for `function main()` to check whether we should change cwd, run `go run .` and change cwd back.

**Comment by ray-x** [comment]
You can use 
`GoRun ./sample1`
to run sample1
The smartRun function can be very useful. But it seems it can only run the `main` in the first match. There are cases where a project may have multiple main package/function.

**Comment by robbyki** [comment]
this is what I use right now for a keymap to current file. I feel like there is a better way to do this though:
`vim.cmd("autocmd FileType go nmap <leader>gr  :cd %:p:h <CR> :GoRun  .<CR>")`
