### ISSUE TITLE
go.nvim clashing with using telescope for LSP keymaps

### ISSUE THREAD

**Issue by vitorf7** [ray-x/go.nvim#156]
Recently I have noticed that my lsp keymaps no longer were acting like they used to.
Specifically I have 2 keymaps (Find References and Find Implementations) which use telescope to open the list of found items.

```lua
  vim.api.nvim_buf_set_keymap(bufnr, "n", "gi", "<cmd>lua require('telescope.builtin').lsp_implementations(require('telescope.themes').get_dropdown())<cr>", opts)
  vim.api.nvim_buf_set_keymap(bufnr, "n", "gr", "<cmd>lua require('telescope.builtin').lsp_references(require('telescope.themes').get_dropdown())<cr>", opts)
```
When I perform these keybindings I get:
![Screenshot 2022-07-05 at 13 57 01](https://user-images.githubusercontent.com/469102/177333054-cc9e041e-5a12-4c0a-8fdd-481a60d8a401.png)

And when I remove the `go.nvim` plugin and try it again I get:
![Screenshot 2022-07-05 at 13 59 27](https://user-images.githubusercontent.com/469102/177333344-17da980e-2d27-4dc0-8d2e-0d174b3a3d62.png)

However even when the `go.nvim` plugin is installed, if I type the actual command `lua require('telescope.builtin').lsp_references(require('telescope.themes').get_dropdown())` it will open the telescope window correctly with the LSP find references results.

So something (which I don't know what) is clashing with the LSP commands and overriding them which it wasn't before.

**Comment by ray-x** [comment]
There is a `lsp_keymaps ` setting, set to false to disable lsp maps

**Comment by vitorf7** [comment]
I have tried that although when I try and do activate the keymap, instead it starts replacing the current character

**Comment by ray-x** [comment]
Sorry, I am not following.
If you setup `lsp_keymaps=false`, this will disable go.nvim from adding keymaps for you when gopls attached. Do you mean it is not working?

**Comment by vitorf7** [comment]
Yes that was correct. 
However, I realised I had the `lsp_cfg` also set up, and when I remove it and I don't even need to add the `lsp_keymaps=false`.
It is strange as it used to all work before but now it is not. I have checked and I do have `use({ "hrsh7th/cmp-nvim-lsp", commit = "affe808a5c56b71630f17aa7c38e15c59fd648a8" })` in my plugins.

For reference my go.nvim set-up was as follows:

```lua
local status_ok, rayx_go_nvim = pcall(require, "go")
if not status_ok then
  return
end

local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())
rayx_go_nvim.setup({
  max_line_len = 120,
  lsp_cfg = {
    capabilities = capabilities,
  },
  lsp_codelens = true,
  dap_debug = true,
  dap_debug_gui=true,
  run_in_floaterm = true,
})
```
