### ISSUE TITLE
Disable golines?

### ISSUE THREAD

**Issue by curtbushko** [ray-x/go.nvim#157]
Great job on this plugin!

How do I disabled golines? It is creating massive diffs and making it difficult in PR reviews.

**Comment by ray-x** [comment]
if you setup `gofmt='gofumpt'` or `gopls` it will not use `goline`.
The exception is `goimport` , as `goline` can do import+format. I submitted a fix for it.
Alternatively:
If you do not want golines split the lines. you can setup `max_line_len = 120,` to a large value, e.g. `max_line_len = 300`.

There is another feature I want to mention is per-project set, where you can setup format options for each project. You can also take a look.

**Comment by curtbushko** [comment]
Thank you for the help!
