### ISSUE TITLE
GoTestFunc output show current working directory at the beginning of each line

### ISSUE THREAD

**Issue by vcraescu** [ray-x/go.nvim#158]
Hi

Every time I run `GoTestFunc` I see something like this in qfixlist:

```
internal/map_test.go|96| 
|| ./internal/Error Trace:	map_test.go:96
|| ./internal/Error:      	Not equal: 
|| ./internal/expected: "foobar"
|| ./internal/actual  : "foobar1"
|| ./internal/
|| ./internal/Diff:
|| ./internal/--- Expected
|| ./internal/+++ Actual
```

Why each line is prefixed with the dir path? It makes it hard to read the output. Any way to disable this?

Thanks!

**Comment by ray-x** [comment]
Seems related to the test package you are using 
Here is a sample output from playground folder

<img width="597" alt="image" src="https://user-images.githubusercontent.com/1681295/177753273-3732c840-46e8-43d9-baca-c7af662c85d8.png">

**Comment by vcraescu** [comment]
@ray-x I'm using testify but those "prefixes" are not displayed if I run `go test -run= ...` directly in the console. So I don't understand where it comes from. I've also tried `vim-go` which also displays the output inside qfixlist but the directory is not displayed at the beginning of each line.

**Comment by vcraescu** [comment]
Yes, it works now! 

Thanks!
