### ISSUE TITLE
GoAddTag doesn't work with inline struct.

### ISSUE THREAD

**Issue by AllenDang** [ray-x/go.nvim#16]
Here is the code I'm trying to add tag.
```go
func test() {
  type some struct {
    Success bool   //<- where the cursor is
  }
  ...
}
```

Invoke :GoAddTag reports
```
Unable to find any nodes at pos.
struct not found
```

This may related to treesitter.

**Comment by ray-x** [comment]
thanks! The issue was fixed.

**Comment by AllenDang** [comment]
@ray-x No issue still remains...

**Comment by ray-x** [comment]
https://user-images.githubusercontent.com/1681295/126025710-b9903592-14dc-4d54-bd10-bc44bd1da971.mov


Strange. But with the code you sent out, I can add tag.

**Comment by AllenDang** [comment]
@ray-x I know what's going no here. I have multiple inline struct with same name, so the  gomodifytags with `-server` options cannot work well. I guess we should use `-line` for a accurate result.

**Comment by ray-x** [comment]
If you have a naming conflict, gomodifytag wont work.
I added `-line` option to the code. not sure if it will work for you.
