### ISSUE TITLE
is there a way to quickly generate return variables?

### ISSUE THREAD

**Issue by edte** [ray-x/go.nvim#170]
just like this in goland

![image](https://user-images.githubusercontent.com/50194671/178979112-c34c0c4b-a2d1-4f7d-9b67-8ec98adcb6bd.png)
![a](https://user-images.githubusercontent.com/50194671/178979513-1887c93f-f3b4-47ee-9813-a9c035dc9891.gif)

**Comment by ray-x** [comment]
looks cool, i can put it in a wish list.

**Comment by gabzim** [comment]
one of the things I really miss from goland

**Comment by ray-x** [comment]
You can add keybinding to `GoGenReturn`
