### ISSUE TITLE
Notify message for GoRun shows 'go run main.go failed' when runs succeed

### ISSUE THREAD

**Issue by ziontee113** [ray-x/go.nvim#171]
Hi, I'm learning golang and I came across your amazing plugin. I do have a question related to the `GoRun` command, which is how can I use GoRun to run a simple .go file?

Let's say I only have a `main.go` file. I can use `:!go run main.go`, but it's quite boring. Can I use `GoRun` instead? Is it supported atm? If I use `:GoRun main.go`, it just say `go run main.go succeeed` and doesn't print the results. Thank you :pray:

The `main.go` file is just this:

```go
package main

import "fmt"

func main() {
	a := 2
	b := 2

	if a < b {
		fmt.Println("a is smaller than b")
	}

	if a > b {
		fmt.Println("a is larger than b")
	}

	if a == b {
		fmt.Println("a is equal to b")
	}
}

```

**Comment by ray-x** [comment]
Do you have any output from quickfix.  Also you can run with floating terminal.

**Comment by ziontee113** [comment]
If I run `GoRun main.go`, quickfix won't open. Just vim.notify `go run main.go succeeed`. No results output.

If I run `GoRun main.go -F`, the result will be printed out:

```
a is equal to b

[Process exited 0]
```

**Comment by ray-x** [comment]
You should see this in quickfix.
<img width="522" alt="image" src="https://user-images.githubusercontent.com/1681295/179375641-fc2b4ebb-733e-4abb-8129-2f15e2d620bd.png">

Could you either try init.lua in playground folder or send a minium init.lua for me to reproduce?

**Comment by ziontee113** [comment]
Hi man, I check it again and now quickfix will prints out results. Floating window also works fine.

1 small problem is that while quickfix prints out the correct results, there's also a notify `go run main.go failed`, it's very odd.

![Screenshot from 2022-07-17 12-42-48](https://user-images.githubusercontent.com/102876811/179385577-cb935420-874e-4cea-a2cf-41c14e4ca4f7.png)

**Comment by ray-x** [comment]
<img width="774" alt="image" src="https://user-images.githubusercontent.com/1681295/179385908-bd148d8c-840f-4228-8404-ec894854037e.png">

**Comment by ray-x** [comment]
<img width="746" alt="image" src="https://user-images.githubusercontent.com/1681295/179385953-b3d114c6-960a-4c01-b081-d49befd1a2de.png">

**Comment by ziontee113** [comment]
Hmm.. I wonder if there's an option to disable the promt?

**Comment by ray-x** [comment]
Not really. You can disable vim.notify to popup by disabling the UI hook (I think it is `dressing.nvim`) once the go.nvim is loaded.

**Comment by ziontee113** [comment]
Yeah I mean having something in the setup function for go.nvim to not use the vim.notify when using `GoRun`, but this is such a minor issue. The floating window is working very nice already.

I use this to execute the file:
```lua
vim.keymap.set(
	"n",
	"<Leader>x",
	function() vim.cmd("GoRun " .. vim.fn.expand("%") .. " -F") end,
	{ noremap = true, silent = true }
)
```

**Comment by ray-x** [comment]
Thanks for the update.
I update the title, in case anyone also sees the notification incorrect message. Feel free to post your setup here and reopen the issue.
