### ISSUE TITLE
[Feature request] minimal defaults

### ISSUE THREAD

**Issue by akinsho** [ray-x/go.nvim#173]
So I've used this plugin on and off for go development, and it does a lot of really cool things, thanks so much for working on it. Unfortunately, it is often very opinionated, which means that to have a simple setup you have to disable a lot of functionality. In my config I generally have broad solutions to most problems rather than expecting specific plugins to reimplement their own solutions to specific issues, e.g. I set up all my diagnostics using `vim.diagnostic.config` I have virtual text set up the way I like this way without things like emoji. I have debugging through `nvim-dap` setup with its own config with dap ui and treesitter with its own key bindings.

My minimal config for this plugin involves having to disable a lot of functionality because I have already set up a lot of these things and if not this plugin automatically and silently overrides my editor behaviour e.g.

```lua
icons = false, <-- I have already setup dap icons so don't want them overriden here
lsp_keymaps = false, <-- most users probably have their own so this should not be default
lsp_on_attach = as.lsp.on_attach, <-- I normally use `LspAttach` to call my own on attach function
lsp_diag_virtual_text = false, <-- I have set this up already with vim.diagnostic
dap_debug_keymap = false, <-- I have set this up already with all my other nvim-dap setup
textobjects = false, <-- I have set up textobjects myself so do not want mapping for this
```

Btw, I think an opinionated plugin is fine as most of my own are, but I think here a user's settings and mappings are sometimes being changed just for `go` in a way that they might not know or expect. I did not realise some of these overrides until I read through the source code of this plugin

Is it possible to offer less opinionated defaults that don't add mappings unless a user asks for them, and doesn't change lsp appearance unless a user opts in to that?

Some plugins solve this using a thing like `require('plugin').set_default_keymap()` so a user can get all of this behaviour with one function if they want it, but otherwise they don't have anything overridden.

I think by default, invasive features should be super transparent to the user and not done by default since it can end up conflicting with a user's config

**Comment by ray-x** [comment]
if most of concern is LSP setup, you can set lsp_cfg to false, that will disable those lsp setup for you.

**Comment by akinsho** [comment]
@ray-x I'm aware of that setting but the LSP isn't my main issue especially since I can pass in my config the main issue to be clear is that *keymaps*, and *diagnostic behaviour* is changed by this plugin _by default_.

I think key maps are a sensitive issue in neovim and I don't think they should be added by default, especially because as user almost definitely already defined key maps for the LSP if they are using neovim for more than one language so having this plugin define key maps in the background really messes with a users settings

**Comment by ray-x** [comment]
if you do not enable lsp_cfg the keymaps wont enable, those come with lsp attach

**Comment by akinsho** [comment]
@ray-x sorry I think maybe my point is not coming through clearly. I guess what I'm trying to say is that if a person is using nvim lsp they almost certainly have already set up keymaps it is a *very common thing to do* as far as I know *no other lsp language plugin* tries to add lsp keymaps because a user will already have done this themselves.

If you look at `nvim-metals`, `nvim-jdtls`, `rust-tools.nvim` etc. they do not add lsp key maps or tbh many other default keymaps a user should add things like that themselves. This issue is more about not doing things for a user by default that they have probably already done or there is a very high chance that they will need to do

Anyway, everything can be disabled, I just think it's invasive/inconvenient that so many settings that override user behaviour are on by default.

**Comment by testinfected** [comment]
Agree here @akinsho. It took me some time to understand why some of my key mappings were no longer working. I use Space a a key leader, as many other people. 

It looks like the `disable_defaults` is aggressively disabling all config, unless I got it wrong. I think it would be less surprising and less intrusive for new users @ray-x if keymaps, icons and treesittterobjects were an opt-in and not an opt-out.

**Comment by gonzaloserrano** [comment]
Hey, I just got here because I wanted to disable the default keymaps, not all the default configs. @testinfected suggestion would work for me.
