### ISSUE TITLE
Hover error after inlay hints

### ISSUE THREAD

**Issue by Esequiel378** [ray-x/go.nvim#175]
Hello there! I find out that after the [inlay hints commit](https://github.com/ray-x/go.nvim/commit/c8d02a9d6adb4194597ce71c292fd9f1f9e01f86#diff-7559bffc1613a8920b2170e22091a4853c9ab4a477746bc9c6fe1c270835392d) there is an issue with hovering

Before **inlay hints**
![before-inlay-hints](https://user-images.githubusercontent.com/40343304/180351047-af476c40-3ba8-4523-90f8-5c0ea2a8686f.png)

After **inlay hints**
![after-inlay-hints](https://user-images.githubusercontent.com/40343304/180350692-cac25785-5d4e-4b3a-9962-651c1fd6aa69.png)

Is there any new config that I should be using after the changes?

This is my current config
![my-config](https://user-images.githubusercontent.com/40343304/180351785-2eb99fa7-a988-49e5-bedf-06506a144b14.png)

**Comment by ray-x** [comment]
Seems this is something wrong with  gopls. The response:

```lua
{
  contents = {
    kind = "markdown",
    value = '{"synopsis":"InjectXraySegment injects the base Segment to be used for the AWS X-Ray Instrumentation.","fullDocumentation":"InjectXraySegment injects the base Segment to be used for the AWS X-Ray Instrumentation.\\n","signature":"func internalmiddlware.InjectXraySegment(serviceName string) func(next http.Handler) http.Handler","singleLine":"func internalmiddlware.InjectXraySegment(serviceName string) func(next http.Handler) http.Handler","symbolName":"middleware.InjectXraySegment","linkPath":"","linkAnchor":"InjectXraySegment"}'
  },
  range = {
    end = {
      character = 44,
      line = 91
    },
    start = {
      character = 27,
      line = 91
    }
  }
}
```

It is sending list instead of string.
The spec says
```
interface HoverResult {
	value: string;
}
```

**Comment by ray-x** [comment]
Ok, it not releated to hintlay, it is Structured setup for hover. Maybe I should revert that specific changes.
