### ISSUE TITLE
gomvp - refactor packages / rename module, early though

### ISSUE THREAD

**Issue by abenz1267** [ray-x/go.nvim#176]
Hi,

i just created a little cli tool that helps refactoring/moving packages and renaming the module itself. It's literally just been released, but i figured you might be interested in adding that to go.nvim regardless.

https://github.com/abenz1267/gomvp

See here: https://drive.google.com/file/d/1GRDP6P5zhFADyiDlQVUWZMhPTrujHYQ5/view?usp=sharing

Regards

**Comment by ray-x** [comment]
Does the tool move all reference in the workspace and maybe .mod/sum from url_for_package_a  to url_for_backage_b if I run `gomvp url_for_package_a url_for_package_a`

**Comment by abenz1267** [comment]
It does indeed!

**Comment by lijinglin3** [comment]
+1

**Comment by ray-x** [comment]
I added a new command `Gomvp`

**Comment by abenz1267** [comment]
gopls just released a new version with experimental package renaming. https://github.com/golang/tools/releases

so i might deprecate gomvp in the near future.

**Comment by mawkler** [comment]
I would love it go.nvim supported gopls's native package renaming!

**Comment by ray-x** [comment]
Try `GoRename`

**Comment by mawkler** [comment]
@ray-x `:GoRename` seems to just rename the import, not the name of the file. I'm guessing that it just calls `vim.lsp.buf.rename()`.

I'm looking for a a way to rename a file and have it propagate to all other files that import it 🙂
