### ISSUE TITLE
lsp_format_on_save has no effect

### ISSUE THREAD

**Issue by khjcph** [ray-x/go.nvim#177]
It seems that `lsp_format_on_save` has no effect. I would assume that setting `lsp_format_on_save=0` would disable formatting on save. I also can't seem to find any references to the variable except for in the `_GO_NVIM_CFG`. Any thoughts on this?

**Comment by ray-x** [comment]
Please refer to doc and add 
```
autocmd BufWritePre *.go :silent! lua require('go.format').gofmt()
```
To your setup
I will remove lsp_format_on_save.

One reason is there are way too many setups to enable format_on_save, they may conflict to each other and result a mal-formated source code.
