### ISSUE TITLE
Gotest Cannot load env variable

### ISSUE THREAD

**Issue by asyrawih** [ray-x/go.nvim#178]
So I Dont have Any Idea When I Running The App Using Command Line like go test ./... the env file has load 

but when Am try using GoTestFunc -F the variable is not loaded how i fixed ? 

my Code like this
![image](https://user-images.githubusercontent.com/23658759/181119038-a0a917d9-f590-41ea-927b-22fb42b161ae.png)

When Running The Test Using GoTests 
![image](https://user-images.githubusercontent.com/23658759/181119101-f34283f1-500c-4af5-a72b-bb9970e9eeb9.png)

But When Running Manual Working 
![image](https://user-images.githubusercontent.com/23658759/181119174-44367086-e4f5-4ed5-9f87-334bab556307.png)

**Comment by ray-x** [comment]
I do not think env file can be loaded automatically. 
You can check how to use per-project setup and launch.json to setup env variables.

**Comment by asyrawih** [comment]
> I do not think env file can be loaded automatically. You can check how to use per-project setup and launch.json to setup env variables. Alternatively: GoEnv cmd can load env file.

Solve Thanks
