### ISSUE TITLE
is_installed return false on windows 11

### ISSUE THREAD

**Issue by ying234** [ray-x/go.nvim#179]
is_installed return false on windows 11
`
local env_path = os.getenv("PATH")
local base_paths = vim.split(env_path, ":", true)
`
The env_path is using ";" not ":" on my windows 11 system.  Is this the reason that is_installed always return false?

**Comment by ray-x** [comment]
I am using linux and mac only. I pushed a change as you suggested. Could you check if it works for you?

**Comment by ying234** [comment]
Thank you @ray-x  @djdv ! Looks like @djdv  is right.

**Comment by ying234** [comment]
It works now. Thanks!
