### ISSUE TITLE
Gofumports url

### ISSUE THREAD

**Issue by Davincible** [ray-x/go.nvim#18]
https://github.com/ray-x/go.nvim/blob/7872cc3ea0713f0247f15110b5a79b2e5b640698/lua/go/install.lua#L6
This line should be:
`  gofumports = "mvdan.cc/gofumpt/gofumports",`

**Comment by Davincible** [comment]
Oh just noticed my other issue about it being depricated lol. But I guess as long as it is looking for gofumports the url should be as above to install it properly

**Comment by ray-x** [comment]
The README.md of gofumpt shows

```
GO111MODULE=on go get mvdan.cc/gofumpt
```

Are both urls work?

**Comment by ray-x** [comment]
gofumport removed
