### ISSUE TITLE
Using a custom `lsp_cfg` disables inlay hints

### ISSUE THREAD

**Issue by akinsho** [ray-x/go.nvim#181]
Using a setup with your own `lsp_cfg` from the docs should merge your settings with go.nvim's but I've found that this causes `inlay_hints` to be disabled. This can be reproduced using
```lua
  require('go').setup({
    gopls_cmd = { 'gopls' },
    icons = false,
    verbose = false,
    lsp_cfg = {}, -- <- Just adding an empty table will cause inlay hints not to work
    lsp_codelens = false,
    lsp_keymaps = false,
    lsp_diag_hdlr = false,
    dap_debug_keymap = false,
    textobjects = false,
    luasnip = true,
  })
```

**Comment by ray-x** [comment]
unable to reproduce with your setup.

<img width="264" alt="image" src="https://user-images.githubusercontent.com/1681295/181297534-a3b2ab7e-daab-4492-bdd6-13a33caa7175.png">

**Comment by akinsho** [comment]
@ray-x how about using
```lua
vim.api.create_autocmd('BufEnter', {
  pattern = '*.go',
  once = true,
  callback = function()
    require('go').setup({
      gopls_cmd = { 'gopls' },
      icons = false,
      verbose = false,
      lsp_cfg = {},
      lsp_codelens = false,
      lsp_keymaps = false,
      lsp_diag_hdlr = false,
      dap_debug_keymap = false,
      textobjects = false,
      luasnip = true,
    })
  end,
})
```

**Comment by ray-x** [comment]
You should not call go.setup()  when buffer is entered.
1) From lspconfig, the lsp setup should be called only once.  As go.nvim will call lspconfig.setup in setup if lsp_cfg is true, you should also call go.setup() only once not in bufenter autocommand.
2) If I attached your script (you have a typo for `vim.api.create_autocmd`) to end of https://github.com/ray-x/go.nvim/blob/master/playground/init.lua it works fine for me. Although it is not the correct way to use the setup

<img width="294" alt="image" src="https://user-images.githubusercontent.com/1681295/181392253-51df0ce7-1b9b-462a-838f-bc5eb6285ae6.png">

**Comment by akinsho** [comment]
@ray-x just to clarify the autocommand I'm using `once = true` which is similar to `++once` so the command is only ever executed one time. It will not run on every `BufEnter` only the first. It's just a mechanism to only load this plugin for golang rather than every time vim opens.

The typo in the command is because I actually use a wrapper (which definitely works) in my config, so I just adapted it to the general example but made a mistake in the name.

I'll try and figure out exactly what is happening, I thought the example would be enough since in my case if I use any lsp config table inlay doesn't work for me.

**Comment by akinsho** [comment]
Ok I was able to reproduce it with a minimal `init.lua`
```lua
vim.cmd.packadd("go.nvim")
vim.cmd.packadd("nvim-lspconfig")

require("go").setup({
	icons = false,
	verbose = false,
	lsp_cfg = {
		settings = {
			gopls = {
				analyses = {
					unusedparams = false,
				},
			},
		},
	},
	lsp_codelens = false,
	lsp_keymaps = false,
	lsp_diag_hdlr = false,
	dap_debug_keymap = false,
	textobjects = false,
	luasnip = true,
})
```

I thought it reproduced with an empty table, but actually if you put anything inside `settings.gopls` the problem appears.

**Comment by ray-x** [comment]
Ok, I saw what you saw now. Thanks!
I pushed an update.

**Comment by akinsho** [comment]
Thanks that fixed it 👍🏿
