### ISSUE TITLE
fieldalignment analyses does not work

### ISSUE THREAD

**Issue by mateusz834** [ray-x/go.nvim#182]
```
local golspcfg = {
    settings = {
	    gopls = {
	        analyses = {
                    fieldalignment = true,
    	        },
    	        staticcheck = true,
	    },
    },
}

require('go').setup({
    lsp_cfg = golspcfg, 
    lsp_on_attach = function()
        require('lsp_signature').on_attach()
    end;
})
```
nvim does not show the warnings about struct field alignment.
When I use the same config, but directly with lspconfig, the warning is displayed.

Edit: also using lsp_on_attach causes the codelens not to be displayed.

**Comment by ray-x** [comment]
Thanks. there was a bug in the code. The fix is pushed through. Could you take another look?

**Comment by mateusz834** [comment]
Thanks. Now it works correctly.
