### ISSUE TITLE
GoTest open Trouble.nvim

### ISSUE THREAD

**Issue by ziombo** [ray-x/go.nvim#184]
Is it possible to set GoTest to open [Trouble.nvim](https://github.com/folke/trouble.nvim) instead of the standard quickfix window?

**Comment by ray-x** [comment]
I am not familiar with Trouble, is there other plug can output the test result to Trouble? 
Also the GoTest output is not lsp diagnostic output.

**Comment by ziombo** [comment]
The issue is not with outputting results to Trouble, but with not opening quickfix list automatically after some tests fail and opening Trouble instead. Trouble can display quickfix data, just in a nicer way.

**Comment by ray-x** [comment]
This is supported in [93c724d](https://github.com/ray-x/go.nvim/commit/93c724d6b0d0f96b695b0538b401e705742e00c3)
