### ISSUE TITLE
" if you are running old version of neovim (<0.7.0)" in neovim 0.7.2

### ISSUE THREAD

**Issue by desdic** [ray-x/go.nvim#189]
After upgrading to latest I get a notification that I'm running a old version of neovim from

https://github.com/ray-x/go.nvim/blob/master/lua/go/format.lua#L21

but I'm using latest stable

```
vim --version
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser
```

do I need to configure it in a new way ? the moment I require go.format I get this

**Comment by ray-x** [comment]
I am not aware that that is a 0.8.x feature. 
Pushed a update to suppress warnings
