### ISSUE TITLE
inlay hints seem to cause errors

### ISSUE THREAD

**Issue by abenz1267** [ray-x/go.nvim#190]
see this error message:

```
Error detected while processing CursorHold Autocommands for "*.go":                                                                                         
Error executing lua callback: /usr/share/nvim/runtime/lua/vim/lsp/util.lua:2017: attempt to get length of local 'line' (a nil value)                        
stack traceback:                                                                                                                                            
        /usr/share/nvim/runtime/lua/vim/lsp/util.lua:2017: in function 'character_offset'                                                                   
        /usr/share/nvim/runtime/lua/vim/lsp/util.lua:1940: in function 'make_given_range_params'                                                            
        ...are/nvim/site/pack/packer/start/go.nvim/lua/go/inlay.lua:40: in function 'get_params'                                                            
        ...are/nvim/site/pack/packer/start/go.nvim/lua/go/inlay.lua:274: in function 'set_inlay_hints'                                                      
        ...are/nvim/site/pack/packer/start/go.nvim/lua/go/inlay.lua:27: in function <...are/nvim/site/pack/packer/start/go.nvim/lua/go/inlay.lua:26> 
  ```
  
  It just breaks at some point, after the error occured for the first time, it'll keep happening on cursor hold. I don't know what causes the breakage though.

Regards

**Comment by ray-x** [comment]
Seems the result of following function is nil
`  local line = get_line(buf, row)`
It seems to be a known neovim bug
https://github.com/neovim/neovim/issues/17615
From the description, seems the `buf` pointing to a file that no longer exists. Is that what happened? e.g. `.go` file removed (by git checkout another branch), or it is a temporary buffer?

**Comment by abenz1267** [comment]
Nothing removed, nor a temporary buffer.

**Comment by ray-x** [comment]
I saw similar thing when I use dap to debug the code. I suspect it is an upstream error.

**Comment by altosys** [comment]
I was just about to post this exact same issue.
I can replicate this anytime by going into a `.go` file and removing the end of a file, for instance if I have this:
```
func a() {
  ...
}

func b() {
  ...
}

func c() {
  ...
}
```
Removing the whole function `c` and saving the file will trigger the error, and it keeps popping up until neovim is restarted or the deletion is undone so that the function is back in the file again.

**Comment by altosys** [comment]
@ray-x I just pulled your new commit into my plugin, at least for me it seems to have fixed the problem, the error doesn't appear when deleting something at the end of a file anymore. Fantastic!
