### ISSUE TITLE
[FEATURE REQUEST] Code coverage visualization by colorizing code

### ISSUE THREAD

**Issue by altosys** [ray-x/go.nvim#192]
The readme has the below image showing that you can visualize the test coverage, but this doesn't seem to work for me, or is incompatible with something else. When I run `:GoCoverage -tm` I get a new window at the bottom of the screen showing the test coverage output, but the indicator is never shown. I'm wondering if this function is using the same left hand gutter as the `gitsigns` plugin, meaning that the coverage indicator in the gutter is overridden by the other plugin showing which lines are added/changed/removed in git (in my case all of them since I'm working on a new file)? Or do you need to configure this visualization to be enabled? 

If this is the case, would it be possible to implement the coverage visualization in the same way that `vim-go` has it, i.e. colorize the code itself so that the text color is indicating the coverage and not the gutter? This was done quite nicely by having a `:GoCoverageToggle` function to turn the coverage color on and off. It's quite useful to be able to toggle the coverage indicator on and off without having to pop up the test output window, so that you can focus on just getting the coverage for a specific piece of code and not have to close down the new window all the time.

![code coverage](https://user-images.githubusercontent.com/1681295/130821038-fa2545c6-16f6-4448-9a0c-91a1ab333750.png)

**Comment by ray-x** [comment]
you have to open a source code and run `GoCoverage`

**Comment by altosys** [comment]
@ray-x I've opened both `myCode.go` and `myCode_test.go` and ran `:GoCoverage` in both, the gutter indicator doesn't show up.

**Comment by ray-x** [comment]
The tests files are in playground
https://user-images.githubusercontent.com/1681295/182873650-60c34687-32fd-4e42-ab2e-acf1a6af8514.mp4

**Comment by altosys** [comment]
> The tests files are in playground https://user-images.githubusercontent.com/1681295/182873650-60c34687-32fd-4e42-ab2e-acf1a6af8514.mp4

It doesn't look like you're using a git plugin in your video clip, try adding `gitsigns` and see how it behaves then.

**Comment by ray-x** [comment]
You can either add the hunk to git or you have to adjust the priority of git signs

**Comment by ray-x** [comment]
An alternative solution is `Gitsigns toggle_signs`

**Comment by altosys** [comment]
> An alternative solution is `Gitsigns toggle_signs`

Should I create a different issue with a specific feature request instead, since we have now verified that nvim-go and gitsigns conflict, meaning there is not a bug or mistake in this case?

**Comment by ray-x** [comment]
Changing the issue title will do.

**Comment by ray-x** [comment]
In fact, the sign priority can be changed for go.nvim. 
There is an undocumented `  sign_priority = 7,`
The value used to be 5 which is very low.  I bumped it to 7.
Also gitsigns also have a similar setup `sign_priority` you can play with

**Comment by altosys** [comment]
> In fact, the sign priority can be changed for go.nvim. There is an undocumented ` sign_priority = 7,` The value used to be 5 which is very low. I bumped it to 7. Also gitsigns also have a similar setup `sign_priority` you can play with

Maybe you missed it, but I already tried that in my post above: https://github.com/ray-x/go.nvim/issues/192#issuecomment-1205395083
It's not a nice solution since the coverage will still obscure gitsigns even if its priority is higher, one will always clobber the other.

**Comment by ray-x** [comment]
Thanks for the suggestions!

I found a dedicated go coverage highlight plugin.
https://github.com/rafaelsq/nvim-goc.lua

Also with introduce the `statuscolumn` in neovim you can display both `gitsigns` and `coverage signs` at same time
e.g.
![image](https://user-images.githubusercontent.com/1681295/215447953-e13f99e9-a320-4ed4-9584-ae326efdef0e.png)

I think there is no need to duplicate the code/work in go.nvim. Will close the issue for now.
