### ISSUE TITLE
GoTest stopped working in floaterm after last updates

### ISSUE THREAD

**Issue by proivk** [ray-x/go.nvim#193]
How to reproduce:
:GoTest

INF: plugin guihua.lua module guihua.floating  not loaded                                                                                                                                         
WARN: guihua not installed, please install ray-x/guihua.lua for GUI functions
Error executing Lua callback: ...hare/nvim/site/pack/packer/start/go.nvim/lua/go/term.lua:57: attempt to index upvalue 'guihua_term' (a nil value)
stack traceback:
        ...hare/nvim/site/pack/packer/start/go.nvim/lua/go/term.lua:57: in function 'term'
        ...re/nvim/site/pack/packer/start/go.nvim/lua/go/gotest.lua:192: in function 'run_test'
        ...re/nvim/site/pack/packer/start/go.nvim/lua/go/gotest.lua:252: in function 'test'
        .../nvim/site/pack/packer/start/go.nvim/lua/go/commands.lua:203: in function <.../nvim/site/pack/packer/start/go.nvim/lua/go/commands.lua:202>

:PackerStatus

 • LuaSnip                                    
 • awesome-vim-colorschemes                   
 • cmp-buffer                                 
 • cmp-cmdline                                
 • cmp-nvim-lsp                               
 • cmp-path                                   
 • go.nvim                                    
 **• guihua.lua**                                 
 • lspkind-nvim                               
 • lualine.nvim                               
 • nvim-cmp                                   
 • nvim-dap                                   
 • nvim-dap-ui                                
 • nvim-lspconfig                             
 • nvim-tree.lua                              
 • nvim-treesitter                            
 • nvim-web-devicons                          
 • packer.nvim                                
 • plenary.nvim                               
 • telescope.nvim

**Comment by ray-x** [comment]
It should be fixed in the latest commit 160897a93f2031fd4c76109a3d1037eb4c9029ef. could you check that out?

**Comment by proivk** [comment]
Nope, still not working on latest

**Comment by proivk** [comment]
It works now. Thanks!
