### ISSUE TITLE
Unable to find any nodes on GoAddTag and GoImpl 

### ISSUE THREAD

**Issue by mnabila** [ray-x/go.nvim#202]
## Sample code
```
type Person struct {
	Name string
	Age  int
}

type IPerson interface {
	SetName(name string)
	SetAge(age int) 
}
```

## Expected Behavior
```
type Person struct {
	Name string `json:"name"`
	Age  int `json:"age"`
}


type IPerson interface {
	SetName(name string)
	SetAge(age int) 
}

func (p *Person) SetName(name string){
	panic("...")
}
func (p *Person) SetAge(age int){
	panic("...")
}

```

## Actual Behavior
tag not fill and got `Unable to find any nodes. place your cursor on a go symbol and try again`

https://user-images.githubusercontent.com/37516576/185517739-add4a899-a582-42f0-a230-44ea5408a9db.mp4

**Comment by ray-x** [comment]
I think you need to save main.go before you run those commands.

**Comment by mnabila** [comment]
still not working :cry: 

https://user-images.githubusercontent.com/37516576/185726294-5bb8c38f-e54b-4999-a789-bdf1768763a4.mp4

**Comment by mnabila** [comment]
**solved**

reinstall go.nvim
