### ISSUE TITLE
Disabling inlay hints also disable github copilot suggestions

### ISSUE THREAD

**Issue by Esequiel378** [ray-x/go.nvim#203]
First, thanks for the plugins and your fantastic work 🤗

I've been trying to disable the `lsp_inlay_hints` with like this

```lua
  require("go").setup {
    ...
    lsp_inlay_hints = {
      enable = false,
    },
  }
```

And it works, but it also disables my GitHub Copilot suggestions.
Any idea how I can disable the inlay hints without breaking other plugins?

**Comment by ray-x** [comment]
I do not think they are related. I also using copilot ATM and see no errors so far.
