### ISSUE TITLE
Disable underline of diagnostics when using go.nvim lsp

### ISSUE THREAD

**Issue by ziombo** [ray-x/go.nvim#204]
I couldn't find an option for this in the config. 

When using go.nvim lsp:
![image](https://user-images.githubusercontent.com/15613606/186271720-b877edc6-c8f7-407c-9b5a-965d8c9198f4.png)

When using standard lspconfig setup:
![image](https://user-images.githubusercontent.com/15613606/186271650-42715992-1b58-4933-91f1-58b6c5a65240.png)

I verified that it's not a matter of a highlight group for my current colorscheme, as it occurs for every colorscheme I tried.

Not sure if I should create a separate issue for that, but I'm also getting this message after quitting vim when go.nvim's lsp is being used:
`Client 1 quit with exit code 2 and signal 0%  
`

**Comment by ray-x** [comment]
I do think it relates to your colorscheme
<img width="222" alt="image" src="https://user-images.githubusercontent.com/1681295/186281648-2fed9166-37d6-4c83-8ea3-8bdd264dc7ce.png">

**Comment by ziombo** [comment]
I can no longer re-create this. Not sure why, but atm. it's working exactly as I expect.
