### ISSUE TITLE
TestNearest with Ginkgo

### ISSUE THREAD

**Issue by rejoshed** [ray-x/go.nvim#205]
Hey, I'm having troubles getting GoTest -n to run anything when I'm using Ginkgo with `It(` style specs.

I just get a pop up menu that looks like:
![image](https://user-images.githubusercontent.com/93345136/186547764-2fe1ea4d-d0f3-4500-82bc-878856b8dc43.png)

My config is:
``` lua
require 'go'.setup({
    goimport = 'gopls', -- if set to 'gopls' will use golsp format
    gofmt = 'gopls', -- if set to gopls will use golsp format
    max_line_len = 120,
    tag_transform = false,
    test_dir = '',
    comment_placeholder = '   ',
    lsp_cfg = true, -- false: use your own lspconfig
    lsp_gofumpt = true, -- true: set default gofmt in gopls format to gofumpt
    lsp_on_attach = true, -- use on_attach from go.nvim
    dap_debug = true,
    test_runner = "ginkgo",
    verbose_tests = true,
    run_in_floaterm = true,
})
```

**Comment by ray-x** [comment]
In commit 1fed4b733cb39c7f362a1b21707c9129f0d21e19
three new commands added
* Ginkgo
* GinkgoFunc
* GinkgoFile

Please check if it works for you

**Comment by Vealcoo** [comment]
> In commit [1fed4b7](https://github.com/ray-x/go.nvim/commit/1fed4b733cb39c7f362a1b21707c9129f0d21e19) three new commands added
> 
> * Ginkgo
> * GinkgoFunc
> * GinkgoFile
> 
> Please check if it works for you

It doesn't work, I even cant find the cmd QQ
