### ISSUE TITLE
Decoupling go tools integration from the rest of the plugin

### ISSUE THREAD

**Issue by Alvinferdi990** [ray-x/go.nvim#208]
Is there any possibility to use the go tools integrations separate from the lsp\dap\ts setup? I would like to use them, but i already have my lsp\null\dap set up and dont want to migrate. I can always just copy the code and try to decouple it from the configuration, but id like to be able to be up to date on them easier.
Maybe it would be possible to split the tool integrations into its own package, that can be configured separately, if it is needed?

**Comment by ray-x** [comment]
you can use this option:
```
  lsp_cfg = false, -- true: use non-default gopls setup specified in go/lsp.lua
                   -- false: do nothing
                   -- if lsp_cfg is a table, merge table with with non-default gopls setup in go/lsp.lua, e.g.
                   --   lsp_cfg = {settings={gopls={matcher='CaseInsensitive', ['local'] = 'your_local_module_path', gofumpt = true }}}
```

**Comment by Alvinferdi990** [comment]
Did not notice that, thank you. Ill try it out.
