### ISSUE TITLE
Config option to disable method placeholders for gopls

### ISSUE THREAD

**Issue by alphatroya** [ray-x/go.nvim#210]
As the title says, I would like to disable this feature for myself, how can I do this?

**Comment by ray-x** [comment]
Could you share a screen shot. I am not 100% sure what you mean by `method placeholders`

**Comment by alphatroya** [comment]
<img width="859" alt="Screenshot 2022-09-06 at 14 47 52" src="https://user-images.githubusercontent.com/4927633/188630272-331f3d9c-c651-4f81-b5ab-0b9e9e8dc30d.png">

I mean method parameters placeholder of course

**Comment by alphatroya** [comment]
Looks like, did not help

**Comment by ljupcho** [comment]
@alphatroya this works for me, should be inside `lsp_cfg` like
```
go.setup({
  lsp_cfg = {
    capabilities = capabilities,
    settings = {
      gopls = {
        usePlaceholders = false,
      },
    },
  },
  lsp_on_attach = on_attach,
})
```

**Comment by alphatroya** [comment]
Thanks, that solve the problem!
