### ISSUE TITLE
List all declarations in a package

### ISSUE THREAD

**Issue by nontw** [ray-x/go.nvim#212]
Hi there, is there a way to see all the declarations (variables, functions, methods, types etc) within a package?  Since a package can contain more than one file and some declarations may be scattered across those files, sometimes it can be cumbersome to locate and look at what are declared inside a package, especially when you need to understand a code base.

Vim-go has :GoDecls and :GoDeclsDir to list out the local declarations of a file and of a directory (package) respectively.  Just curious if this project has something similiar.

Thank you very much.

**Comment by ray-x** [comment]
GoPkgOutline is what you looking for. require guihua.lua installed.

**Comment by nontw** [comment]
Thank you very much!
