### ISSUE TITLE
Is there a shortcut to `go to the test` of current buffer?

### ISSUE THREAD

**Issue by LintaoAmons** [ray-x/go.nvim#214]
Like IDEA, I can go to the related test by `Goto the tests`~

Don't know if there's a way to achieve this in neovim? maybe should include in LSP stuff...

**Comment by ray-x** [comment]
Do side bar plugins meet the requirement?
![image](https://user-images.githubusercontent.com/1681295/189522626-7da27f87-cf98-4d5e-a492-5774fb1069a1.png)

**Comment by LintaoAmons** [comment]
I mean when I'm editing `filename.go`, then I hit the shortcut of `Goto tests`, it will jump to `filename_test.go`

Like this, when I hit the shortcut, it jump to the related test file~
![goto-test](https://user-images.githubusercontent.com/95092244/189522951-2fb99428-2c11-4755-b08b-f3191292b62b.gif)

**Comment by LintaoAmons** [comment]
Thanks!
