### ISSUE TITLE
Can I disable the diagnostics virtual text?

### ISSUE THREAD

**Issue by LintaoAmons** [ray-x/go.nvim#216]
Cause I'm using the LspSaga plugin as well, so there's duplicated virtual text.

Like:
![image](https://user-images.githubusercontent.com/95092244/189789936-24a5cba1-1cb2-4e46-b654-869c50f8d992.png)

I tried to set: `  lsp_diag_signs = false`, but seems not this option~~

**Comment by ray-x** [comment]
go.nvim does not setup your diagnostic. 
You can setup it with 

```
vim.diagnostic.config({
  virtual_text = {
    source = 'always',
    prefix = '■',
    -- Only show virtual text matching the given severity
    severity = {
      -- Specify a range of severities
      min = vim.diagnostic.severity.ERROR,
    },
  },
  float = {
    source = 'always',
    border = 'rounded',
  },
  signs = true,
  underline = true,
  update_in_insert = false,
  severity_sort = true,
})
```

Please refer to the reference manual of diagnostic for more details.

**Comment by LintaoAmons** [comment]
Thanks for your hint!~
