### ISSUE TITLE
package test is not in GOROOT (/usr/lib/go/src/test)

### ISSUE THREAD

**Issue by xaotag** [ray-x/go.nvim#225]
https://user-images.githubusercontent.com/40427877/193422455-1d75797d-2ed4-408c-8e1a-bf476da9d640.mp4

**Comment by ray-x** [comment]
Do you have `go.mod` in your project root folder?

**Comment by xaotag** [comment]
https://user-images.githubusercontent.com/40427877/193455115-628dce54-16fc-4cb9-ac89-e69770dd62a7.mp4


![image](https://user-images.githubusercontent.com/40427877/193454995-6ecf14de-bf5e-47a1-9b5b-8f39fe9857e0.png)
@ray-x

**Comment by xaotag** [comment]
![image](https://user-images.githubusercontent.com/40427877/193474040-2c56b2f1-7662-45f9-bcb6-fc8732cd0538.png)
test_runner="go" ,
