### ISSUE TITLE
Gopls formatting error

### ISSUE THREAD

**Issue by Davincible** [ray-x/go.nvim#228]
I get this when running GoFmt with fmt set to gopls

```
gopls: 0: json: cannot unmarshal bool into Go struct field AddImportArgs.ImportPath of type string
```

Not sure if issue with gopls itself or this plugin

**Comment by ray-x** [comment]
Could you send me the source you saw the error?

**Comment by ray-x** [comment]
It might releated to the go source code:
Check this : https://github.com/awslabs/goformation/issues/39
and :  https://stackoverflow.com/questions/73451511/json-cannot-unmarshal-number-into-go-struct-field-amount-of-type-string

Looks like ImportPath is not setting correctly.

**Comment by Davincible** [comment]
Ahh hmm. Thanks for the links.

Since writing the issue I've looked a bit more into the LSPs, and I also got some golangci lint errors. 

Don't think its related to this package config so I'll close.

Side note though; lately I've been having lots of LSP timeout and gopls taking up way too much memory. Looked a bit into it but couldn't find too much, any ideas on how to improve that?

**Comment by ray-x** [comment]
There are a few setup can reduce the frequency gopls sync your codebase
 in gopls.lua
```     
      debounce_text_changes = 500
      diagnosticsDelay = '500ms',
      experimentalWatchedFileDelay = '200ms',
```
You can increase those to around 1s to see if it can help.
They are hard-coded ATM
