### ISSUE TITLE
gotest arguments

### ISSUE THREAD

**Issue by roychoo** [ray-x/go.nvim#229]
Hi,

wish to ask, how can i pass additional arguments to GoTestXXX?

**Comment by ray-x** [comment]
e.g. 
`GoTestXXXX -flags`
`-flags` should be forward to `go test`

```lua
local long_opts = {
  verbose = "v",
  compile = "c",
  coverage = "C",
  count = "n",
  tags = "t",
  bench = "b",
  metric = "m",
  select = "s",
  floaterm = "F",
}
```
As long as it does not start with the above options (v, c, C, n ...)

**Comment by roychoo** [comment]
hi, i tried and it didnt. 

```GoTestFunc -args mock=true``` became
```go test -tags=tag1,tag2 -v -run '^Test$' ./test dontInit=true exited with code: 1 failed  ```

expecting 
```go test -tags=tag1,tag2 -v -run '^Test$' ./test -args mock=true```

**Comment by ray-x** [comment]
well, it is correct the `-args` is not correct supported. I have to add an extra args '-a' for this.
So to run test with args, you have to use `-a`, e.g.
`GoTest -a mock=true`

**Comment by ray-x** [comment]
I assume this can be close with above PR
