### ISSUE TITLE
Error detected while processing BufEnter Autocommands for "<buffer=1>"

### ISSUE THREAD

**Issue by mortezadadgar** [ray-x/go.nvim#23]
hey, the title error message flash out on screen on every *.go files

<details>
<summary>minimal_config</summary>

-- install packer
local fn = vim.fn

local install_path = '/tmp/nvim/site/pack/packer/start/packer.nvim'

vim.cmd [[set packpath=/tmp/nvim/site]]

local function load_plugins()
	local use = require('packer').use
	require('packer').startup {
		function()
			use 'wbthomason/packer.nvim'
			use 'neovim/nvim-lspconfig'
			use {
				"hrsh7th/nvim-compe",
				config = function()
					vim.o.completeopt = "menuone,noselect"
					require'compe'.setup {
						source = {
							path = true;
							buffer = true;
							nvim_lsp = true;
							nvim_lua = true;
							vsnip = true;
							emoji = true;
						};
					}
				end
			}
		use {
			"ray-x/go.nvim",
			config = function ()
				require("go").setup{
					cfg = {
						tag_transform = true,
						lsp_on_attach = false,
					}
				}
			end
		}
		end,
		config = { package_root = '/tmp/nvim/site/pack' },
	}
end

_G.load_config = function()
  local nvim_lsp = require 'lspconfig'
  local name = 'gopls'
  local cmd = { 'gopls' }
  nvim_lsp[name].setup {
    cmd = cmd,
  }

end

if fn.isdirectory(install_path) == 0 then
  fn.system { 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path }
  load_plugins()
  require('packer').sync()
  vim.cmd 'autocmd User PackerComplete ++once lua load_config()'
else
  load_plugins()
  _G.load_config()
end

</details>

**Comment by ray-x** [comment]
I thinks this is releated to to gopls codelens refresh. Sometime gopls is slow on startup and calling to it will result an error.
I add some fix to it. Would you check if it works for you.

**Comment by Jackson-soft** [comment]
![image](https://user-images.githubusercontent.com/3928114/130387727-e2a53643-a2c4-4d11-86d5-4d5ce84261e4.png)

**Comment by ray-x** [comment]
yes, should be utils.log

**Comment by mortezadadgar** [comment]
yeah it's fine now though I'm getting a harmless error "LSP: no client attached"
