### ISSUE TITLE
Run commands on init and not first on save

### ISSUE THREAD

**Issue by emilpriver** [ray-x/go.nvim#231]
I am using ray-x/go with gopls and have a issue where my LSP show me this information first on save 
![Skärmavbild 2022-10-24 kl  23 21 44](https://user-images.githubusercontent.com/34039674/197631959-39abb8b2-fbaf-4ee6-8262-5471b382c843.png)

I am trying to get this information to show when entering a new go file. is it possible?

**Comment by ray-x** [comment]
If those are virtual text, it should be a setup for gopls inlay feature.
Please check lsp_inlay_hints setup in readme.

**Comment by emilpriver** [comment]
Works, u a boss @ray-x Thank you! :D 👯
