### ISSUE TITLE
TMPL syntax highlighting

### ISSUE THREAD

**Issue by bjufre** [ray-x/go.nvim#238]
First of all thank you for this amazing plugin. I'm kinda new to Neovim; and I'm trying to setup a good Go development environment. Everything seems to work as expected except the files `.tmpl` or `.tmpl.html` or `.html.tmpl`. I'm seeing the buffer as if it was plain text.

Any advice as to get proper experience with those files? 🙏 

Thank you very much!

**Comment by ray-x** [comment]
Pushed a change for it.

**Comment by bjufre** [comment]
@ray-x that seemed to do that trick. There are some caveats, but I guess the next step would be to have a proper treesitter plugin. I will look into it; nonetheless thank you very much!!!
