### ISSUE TITLE
Frozen when using Goto declaration from a different package

### ISSUE THREAD

**Issue by gonzaloserrano** [ray-x/go.nvim#239]
When going to a declaration from a different package, nvim freezes. In the same package it does not.

I tried it with a minimal example:
```
➜  ~/g/s/g/g/foo cat foo.go
package foo

import "github.com/gonzaloserrano/foo/bar"

type x string

type foo struct {
	x   x
	bar bar.Bar
}
➜  ~/g/s/g/g/foo cat bar/bar.go
package bar

type Bar string
➜  ~/g/s/g/g/foo
```

Goto definition of `x` works, but freezes when goto definition of `bar.Bar`. Nvim becomes unresponsive and I need it to kill the process.

I'd appreciate any help to troubleshoot this.

My env:

- https://github.com/LunarVim/LunarVim
- I've tried neovim 0.8.1 and v0.9.0-dev-326+gfa7e1e260-dirty (`brew install nvim --HEAD`).
- gopls:
```
$ gopls version
golang.org/x/tools/gopls v0.10.0
    golang.org/x/tools/gopls@v0.10.0 h1:OGrMgGUl9LWTPaeN5ML3SotSguhrdMHbWevtM8cYN6s=
```

**Comment by ray-x** [comment]
I can not reproduce this issue.

The test I using 
lsp_go/fun/fun.go
```go
package fun

type Dog struct {
    name  string
    age   int
    owner string
}

func NewDog(name string, age int) *Dog {
    return &Dog{name: name, age: age}
}

```

lsp_go/pkg/interface.go
```go
package pkg

import (
	"fmt"
	"math"

	"lsp_go/fun"
	//"math"
)

type geometry interface {
	area() float64
	perim() float64
}

type rect struct {
	width  float64 `-line:"width"`
	height float64 `-line:"height"`
}

type rect2 struct {
	width  int `yml:"width"`
	height int `yml:"height"`
}

func (r rect) area() float64 {
	_ = fun.NewDog("", 2)
	return r.width * r.height
}

```

I have no issue jumping to newDog from pkg to fun package.

**Comment by gonzaloserrano** [comment]
Thanks! What version of nvim and gopls are you using?

**Comment by ray-x** [comment]
neovim: I pull the master each week. So it is more of a nightly build.
I using the same version gopls as you do.

The freeze sounds like the gopls can not response your request. But as the request is async request. I see no reason it freezes the neovim.

**Comment by gonzaloserrano** [comment]
I noticed it gets stuck even when the references are on another file of the same package 🤦 

Not on the same file, though. Anyway, closing this.
