### ISSUE TITLE
:Goimport not formatting code

### ISSUE THREAD

**Issue by tristan957** [ray-x/go.nvim#24]
:Gofmt is formatting code correctly. A little confused.

**Comment by ray-x** [comment]
If you would like to import and gofmt, you can set `goimport` to `gofumports`
If you are using gopls to import module, gopls does not format the code after import. You can set format on save.
There is a reason why `gofumports` deprecated and I add gopls to goimport. If you maintaining legacy codebase, `gofmt` or `gofumpt` may have side effects.

**Comment by tristan957** [comment]
What I am noticing is `:lua require('go.format').goimport()` has no effect. You are saying this is deprecated?

**Comment by tristan957** [comment]
Oh wait I see what you are saying. gofmt() is for the code. goimport() is for imports. Got it.

**Comment by ray-x** [comment]
Yes. If you want import & format
```
{
    goimport = 'gofumports'
}
```
