### ISSUE TITLE
Unclear installation instructions

### ISSUE THREAD

**Issue by RafaelZasas** [ray-x/go.nvim#252]
I am new to neovim and vim plugins, so please bear with me. It hasn't been easy to find all the info to get set up.

It's not clear where to run `require('go').setup()
` but when I run `lua require('go').setup()` in the terminal I get `INF: plugin nvim-treesitter module nvim-treesitter  not loaded`

The instructions stated that treesitter should be installed the first time I use it (what is it?) I installed the vim-plug plugins but there wasnt anything about treesitter in the installation process I dont think.

What am I missing?

**Comment by ray-x** [comment]
I updated the doc. 
some of the plugin is not required in some feature. but if you do healthcheck, you will have a list of all plugins you needed.
