### ISSUE TITLE
can we have GoPlay command to create a go snippet and run it on `https://go.dev/play/`?

### ISSUE THREAD

**Issue by xiantang** [ray-x/go.nvim#253]
When we type the command `GoPlay` will generate a new buffer like this:

```go
// You can edit this code!
// Click here and start typing.
package main

import "fmt"

func main() {
	fmt.Println("Hello, 世界")
}
```

after that when u run `GoPlayRun` it will invoke the http request to `https://go.dev/play/` and get result from server, finally it will create a new buffer with `Hello, 世界`

do u think this feature is ok? can I work on it?

**Comment by ray-x** [comment]
I am using sniprun plugin(https://github.com/michaelb/sniprun).  Could this be an alternative for you?

**Comment by xiantang** [comment]
look good
