### ISSUE TITLE
Make floaterm position and dimensions configurable

### ISSUE THREAD

**Issue by oddlid** [ray-x/go.nvim#257]
Hi,

It would be great if one could configure the position and dimensions of the floaterm used for tests.
Position like "center", "top", "right", "bottom", "left".
Dimensions in percentage of width and height of the screen.

I often run tests that log lots of long lines of output, and the default split right makes it a bit cumbersome to read all output.
If I could configure the term to open covering almost all of the screen, that would be awesome!

BR,
Odd

**Comment by oddlid** [comment]
Hi,

I've noticed that lately, the float term closes after a short timeout after the test is complete. Disabling this auto-close would also need to be configurable for the above to be useful.

BR,
Odd

**Comment by ray-x** [comment]
Both should been fixed

**Comment by hippeus** [comment]
Hi folks,

**Comment by xiantang** [comment]
> Hi, 你好，
> 
> I've noticed that lately, the float term closes after a short timeout after the test is complete. Disabling this auto-close would also need to be configurable for the above to be useful.我注意到最近，测试完成后，浮动窗口会在短暂的超时后关闭。禁用这个自动关闭功能也需要可配置，以便上述功能能够发挥作用。
> 
> BR, 您好，以下是您要求的翻译内容： BR, Odd 奇怪的

this is not fixed, still have this isuee
