### ISSUE TITLE
GoLint with golangci-lint bad paths in quickfix window

### ISSUE THREAD

**Issue by Jared-Janrain** [ray-x/go.nvim#260]
Using golangci-lint, the quickfix window isn't populated correctly for lint errors in test files.

running `GoLint` I see this message of what is run
```
golangci-lint run --print-issued-lines=false --exclude-use-default=false exited with code: 1 failed
```

Lint errors in most files are populated correctly, but the ones in test files look like
```
.//path/to/file.go
```
instead of
```
path/to/file.go
```
so they can't be jumped to.

**Comment by Jared-Janrain** [comment]
Issue/difference looks to be in `extract_filepath` in `asyncmake.lua`, where test files are treated differently. The `find` is adding `./` as it does, and then using `./` instead of `.` adds yet another

**Comment by ray-x** [comment]
This should be fixed in the latest version. Would you take a look?

**Comment by Jared-Janrain** [comment]
Looks fixed! thank you.
