### ISSUE TITLE
Can't run code coverage when code and tests are in different packages

### ISSUE THREAD

**Issue by proivk** [ray-x/go.nvim#261]
I've got the following project structure
```
.
├── cmd
│   ├── root.go
│   └── run.go
├── go.mod
├── go.sum
├── main.go
└── pkg
    ├── checks
        ├── file.go
        └── tests
            └── file_test.go
```

When I run :GoCoverage in `checks` package (having both files `file.go` and `file_test.go` opened in nvim), I get 
```
test finished:
?       checker/pkg/checks/        [no test files]

ok      checker/pkg/checks/tests  0.308s  coverage: [no statements] 
```

Though, it works fine when running `go test -cover ./... -v -coverpkg=./...` from command line

```
coverage: 62.5% of statements in ./...
ok  	checker/pkg/checks/tests	(cached)	coverage: 62.5% of statements in ./...
```
What is the right way to run GoCoverage for the tests located in different package?

**Comment by ray-x** [comment]
I think you need to run 
```
GoCoverage -p
```

**Comment by proivk** [comment]
I tried this as well, but no luck

```
test finished:

ok      checker/pkg/checks/aws/tests  0.292s  coverage: [no statements]

```

**Comment by ray-x** [comment]
How about 
```
GoCoverage -p -coverpkg 'yourpkgname'
```

**Comment by proivk** [comment]
> How about
> 
> ```
> GoCoverage -p -coverpkg 'yourpkgname'
> ```

Nope, still not working. Prints exactly the same result as above.

**Comment by ray-x** [comment]
It should been fixed
![image](https://user-images.githubusercontent.com/1681295/209456928-7d12cbe0-2e9e-4dce-af8e-729fa961dc73.png)
