### ISSUE TITLE
How to disable specific gopls analysis rules?

### ISSUE THREAD

**Issue by raine** [ray-x/go.nvim#262]
Hello @ray-x. I updated go.nvim and this linting complaint came out of nowhere:

<img width="573" alt="image" src="https://user-images.githubusercontent.com/11027/209469748-9530b604-15ac-4541-be43-1148c3afdd7b.png">

I found that it's this rule: https://staticcheck.io/docs/checks#ST1003, enabled here: https://github.com/ray-x/go.nvim/blob/9f0d92ab2d6d9338d6afbc2680afc9946ddabedc/lua/go/gopls.lua#L243

I tried to disable it by adding `staticcheck.conf` with `checks = ["all", "-ST1003"]`, but it does not have any effect.

The only way I could disable it was by editing `lua/go/gopls.lua` in this plugin and setting `ST1003 = false`.

Any ideas? Thanks.

**Comment by ray-x** [comment]
You need to put a override to it:
```lua
require('go').setup({
    lsp_cfg = {
      settings = {
        gopls = {
          analyses = {
            ST1003 = false,
          },
        },
      },
    }
})
```
