### ISSUE TITLE
dlv first startup wait too long

### ISSUE THREAD

**Issue by y1rn** [ray-x/go.nvim#263]
nvim-dap show follow message:
```
Debug adapter didn't respond. Either the adapter is slow (then wait and ignore this) or there is a problem with your adapter or `go` configuration. Check the logs for errors (:help dap.set_log_level)
```
 [nvim-dap initialize_timeout_sec ](https://github.com/mfussenegger/nvim-dap/blob/master/doc/dap.txt#L133) default is 4 seconds.

Is there any solution?

**Comment by ray-x** [comment]
Do you want an option to increase timeout?

**Comment by y1rn** [comment]
> nvim-dap show follow message:
> 
> ```
> Debug adapter didn't respond. Either the adapter is slow (then wait and ignore this) or there is a problem with your adapter or `go` configuration. Check the logs for errors (:help dap.set_log_level)
> ```
> 
> [nvim-dap initialize_timeout_sec ](https://github.com/mfussenegger/nvim-dap/blob/master/doc/dap.txt#L133) default is 4 seconds.
> 
> Is there any solution?

I've try to added time out option to nvim-dap, and it works. maybe you could increase it or add timeout option, or both.

**Comment by ray-x** [comment]
pushed a change for it
new options:
```
  dap_timeout = 15, --  see dap option initialize_timeout_sec = 15,
  dap_retries = 20, -- see dap option max_retries
```

**Comment by y1rn** [comment]
> dap_timeout

thx
