### ISSUE TITLE
GoCoverage result incorrect

### ISSUE THREAD

**Issue by y1rn** [ray-x/go.nvim#264]
lines 226, 229, 233, 242 actually ran but coverage result shows red.

![image](https://user-images.githubusercontent.com/70128797/209676210-6c4c6bf6-06a6-43ce-98d9-5bd829fc7b06.png)

bellow is image debugging in line 229:
![image](https://user-images.githubusercontent.com/70128797/209676845-89d263a9-a7d4-4af1-88ad-057914bb2e99.png)

there is part of cover.cov result:
github.com/xtls/xray-core/app/dns/fakedns/fake.go:224.74,226.57 2 1
github.com/xtls/xray-core/app/dns/fakedns/fake.go:229.2,229.25 1 1
github.com/xtls/xray-core/app/dns/fakedns/fake.go:226.57,228.3 1 0
github.com/xtls/xray-core/app/dns/fakedns/fake.go:232.13,233.122 1 1
github.com/xtls/xray-core/app/dns/fakedns/fake.go:242.2,242.127 1 1
github.com/xtls/xray-core/app/dns/fakedns/fake.go:233.122,236.77 3 0
github.com/xtls/xray-core/app/dns/fakedns/fake.go:239.3,239.16 1 0
github.com/xtls/xray-core/app/dns/fakedns/fake.go:236.77,238.4 1 0
github.com/xtls/xray-core/app/dns/fakedns/fake.go:242.127,245.77 3 0
github.com/xtls/xray-core/app/dns/fakedns/fake.go:248.3,248.16 1 0
github.com/xtls/xray-core/app/dns/fakedns/fake.go:245.77,247.4 1 0

**Comment by ray-x** [comment]
thanks, it was a bug, should have been fixed.

**Comment by y1rn** [comment]
looks coverage highlight not as expect:
![image](https://user-images.githubusercontent.com/70128797/210248691-e63e211a-70a0-4293-a864-f4aa94e0403e.png)
![image](https://user-images.githubusercontent.com/70128797/210248775-4015c1ee-da1f-45d2-a59a-d3a5ea9fcf57.png)

**Comment by ray-x** [comment]
It may releated to new config option
```lua
  sign_partial_hl = "WarningMsg",
```
You should see three colors
![image](https://user-images.githubusercontent.com/1681295/210277650-a5ed62b1-90ff-4d30-9ac2-b145e3050610.png)
Please check your colorscheme has `WarningMsg`

**Comment by y1rn** [comment]
thanks for your reply, I've set color for `WarningMsg` , there are no need to highlight as partial  in my block
![image](https://user-images.githubusercontent.com/70128797/210297082-3e37495a-845a-44fe-88ec-8c1a93f82d29.png)
expect:
![image](https://user-images.githubusercontent.com/70128797/210296600-93b559d3-ca1f-4be7-ae89-59683db74f0e.png)


![image](https://user-images.githubusercontent.com/70128797/210297126-1fca3ae9-eaf1-4c83-b995-7fd3b161846c.png)
expect:
![image](https://user-images.githubusercontent.com/70128797/210296734-38a57ba3-f5c6-4144-952e-9c5249146c86.png)

**Comment by ray-x** [comment]
If you do not want to see partial tested to be coloured differently, you can set 
`  sign_partial_hl = "Error", `

**Comment by y1rn** [comment]
> If you do not want to see partial tested to be coloured differently, you can set ` sign_partial_hl = "Error",` That will behave the same as the old version.
I mean partial highlight not correct in my blocks

**Comment by ray-x** [comment]
Cool, it should be fixed

**Comment by ray-x** [comment]
@y1rn Does the new version work for you?

**Comment by y1rn** [comment]
new version work great, thx
