### ISSUE TITLE
checkhealth fails

### ISSUE THREAD

**Issue by toytown** [ray-x/go.nvim#267]
neovim : 0.8.1
os: macos  Monterey (12.6.2 )
go : go version go1.19.4 darwin/amd64 (installed via homebrew)
echo $PATH | grep "$GOPATH/bin" --> echo /usr/local/bin:/usr/bin:/bin:/usr/sbin:......
gopls : installed  under /Users/<user>/go/bin/gopls

I get this error when I run :checkhealth. Also LSP is not getting attached 

  - ERROR: Failed to run healthcheck for "go" plugin. Exception:
    function health#check, line 20
    Vim(eval):E5108: Error executing lua ...re/nvim/site/pack/packer/start/go.nvim/lua/go/health.lua:22: attempt to index global '_GO_NVIM_CFG' (a nil value)
    stack traceback:
    ...re/nvim/site/pack/packer/start/go.nvim/lua/go/health.lua:22: in function 'binary_check'
    ...re/nvim/site/pack/packer/start/go.nvim/lua/go/health.lua:134: in function 'check'
    [string "luaeval()"]:1: in main chunk

**Comment by ray-x** [comment]
Ok, a fix was pushed
