### ISSUE TITLE
`:GoGenerate` ignored directive

### ISSUE THREAD

**Issue by yanskun** [ray-x/go.nvim#271]
`:GoGenerate` command is ignored directive.

## Probrem

Run `:GoGenerate` with the code below yields nothing.

`cmd/main.go`
```go
//go:generate mockgen -source=$GOFILE -destination=mock_$GOFILE -package=$GOPACKAGE
package main

func main() {
  // logic
}
```

But where I run `go generate cmd/main.go` in the console, it produces `cmd/main_mock.go`

## Expected

If `:GoGenerate` is executed, `cmd/main_mock.go` will be generated.

## Example

https://github.com/yanskun/go-workspace-sample/blob/main/cmd/app2/main.go

**Comment by ray-x** [comment]
It should be fixed in latest

**Comment by yanskun** [comment]
I confirmed fixed!

thx!❤️
