### ISSUE TITLE
breakpoint issue

### ISSUE THREAD

**Issue by y1rn** [ray-x/go.nvim#272]
I setup and breakpoint in main.go, and debug test function, then saw `could not find file /xxx/main.go `
Is there any way to fix this?

**Comment by ray-x** [comment]
What is your project structure? also what is the current directory nvim is running?

**Comment by ray-x** [comment]
when you said `test file` . Are you trying to debug test or main?
with main
run `GoDebug`
Debug test run `GoDebug -t`
Is `/xxx/main.go` existed or not, what should be the path for main.go?

**Comment by y1rn** [comment]
sorry, I setup breakpoint in main.go, and debug other go test file not in root. I just run `GoDebug` both main.go and other go test file,

**Comment by y1rn** [comment]
I found root cause is:
```
  -- if breakpoint is not set add breakpoint at current pos
  local pts = require('dap.breakpoints').get()
  if utils.empty(pts) then
    require('dap').set_breakpoint()
  end
```
I setup break point in main.go, and run test file function with `GoDebug`, and It did not set breakpoint in test function and run.

**Comment by ray-x** [comment]
that makes sense. As /xxx/main.go was not compiled in your test binary. But dap still trying to set breakpoints for main.go. 
Above helper is trying to set a breakpoint so when you run debug it will stop.  For me it would be better to keep it there instead of removing it.

**Comment by ray-x** [comment]
I added a debug message when breakpoint was added automatically.  Going to close the issue as it is more a designed behaviour.
