### ISSUE TITLE
GoUpdateBinaries from outside nvim

### ISSUE THREAD

**Issue by EmilSodergren** [ray-x/go.nvim#273]
Hi,

I am currently trying to get the GoUpdateBinaries command to be a part of my "1-touch-configure-my-computer"-setup. I have it configured as a postinstall hook in the packer package manager and call the package manager from the commandline by:

`nvim -u .config/nvim/lua/plugins.lua --headless -c autocmd User PackerComplete quitall -c PackerSync`

where .config/nvim/lua/plugins.lua contains:

```lua
require("packer").startup(function(use) 
   use "wbthomason/packer.nvim"
   use {"ray-x/go.nvim", run = ":GoUpdateBinaries", requires = { "ray-x/guihua.lua"}}
end)
```
It seems like the the package manager is not recognizing the GoUpdateBinaries task as ongoing and sends the PackerComplete signal before it has completed.

I have tried to run something like: `nvim -c GoUpdateBinaries -c quitall` but with the same result. It reaches the quitall command instantly and has no time to go install anything.

Is it possible to run the GoUpdateBinaries from the commandline in a synchronous way?

**Comment by ray-x** [comment]
GoUpdateBinaries will be registered until you run `require('go').setup{}`
To use it outside. You may want to create a function/command of your own
e.g. 

You can add a user command in your `init.lua`
or maybe `ftdetect/go.vim`
or maybe this:
```lua


require("packer").startup(function(use) 
   use "wbthomason/packer.nvim"
   use {"ray-x/go.nvim", run = ":lua require('go.install').install_all()", requires = { "ray-x/guihua.lua"}}
end)
```

**Comment by EmilSodergren** [comment]
Ah, so simple... thank you so much!

**Comment by EmilSodergren** [comment]
But... the command that executes in `run =` is aborted as soon as packer has pulled all the git repos. If it needs to pull many plugins I get more go binaries but if everything is up to date it gets less, or none.

I previously had the same issue with Treesitter where the TSInstall/TSUpdate commands failed. Turned out that these commands does things async and therefore is not allowed to finish before nvim shut down. Instead there is a TSInstallSync, command that runs the installation synchronously. Could it be a similar issue here? That the update_all() function is spun off into a separate thread?

**Comment by ray-x** [comment]
Ok, I added sync method as well . So instead of `install_all()`, you run `install_all_sync()` in your plugin `run` script

**Comment by EmilSodergren** [comment]
Awesome! This works. Thank you so much. Both `install_all_sync()` and `update_all_sync()` works beautifully.
Another thing, it seems like the mockgen binary is called github.com/golang/mock**/mockgen**@latest now.

**Comment by ray-x** [comment]
mockgen updated
