### ISSUE TITLE
Keymap error when debugging go project

### ISSUE THREAD

**Issue by ray-x** [ray-x/go.nvim#276]
I'm seeing the same error when restarting a debug session in ray-x/go.nvim.  Guessing I should file an issue in that project unless there is a common workaround?  New user of go.nvim and neovim in general so may be something i'm doing wrong.

```lua
Error executing Lua callback: ...ck/packer/start/nvim-dap-ui/lua/dapui/windows/layout.lua:37: Invalid buffer id: 6
stack traceback:
        [C]: in function 'nvim_set_current_buf'
        ...ck/packer/start/nvim-dap-ui/lua/dapui/windows/layout.lua:37: in function 'open'
        ...im/site/pack/packer/start/nvim-dap-ui/lua/dapui/init.lua:361: in function 'cb'
        ...im/site/pack/packer/start/nvim-dap-ui/lua/dapui/init.lua:287: in function 'keep_cmdheight'
        ...im/site/pack/packer/start/nvim-dap-ui/lua/dapui/init.lua:339: in function 'open'
        ...share/nvim/site/pack/packer/start/go.nvim/lua/go/dap.lua:358: in function 'run'
        .../nvim/site/pack/packer/start/go.nvim/lua/go/commands.lua:62: in function <.../nvim/site/pack/packer/start/go.nvim/lua/go/commands.lua:57> 
```

_Originally posted by @clarkezone in https://github.com/ray-x/navigator.lua/issues/225#issuecomment-1405441245_

**Comment by ray-x** [comment]
@Darkclainer could you send how you reproduce this issue? Thanks!

**Comment by clarkezone** [comment]
I opened an issue with repo steps here https://github.com/ray-x/go.nvim/issues/278

**Comment by ray-x** [comment]
It is a `dapui` API changes. Filed an issue in `dapui` and as there is an duplicated open in `go.nvim`. I will close this one.
