### ISSUE TITLE
Failing generated go tests for null-ls

### ISSUE THREAD

**Issue by blob42** [ray-x/go.nvim#279]
I am trying to use go.nvim with null-ls with automated test on save feature with diagnostics. I can run the tests manually or with `GoTest` without issue. This issue might be related to #259 

It is not working with null-ls , It looks like the generated regex for the test run is broken. This is a log from a session where I opened a tests file:
```
  /go/utils.lua:793 |1: testing: invalid regexp for element 0 of -test.run ("TestMain\\|Test(name\\|string,\\|t\\|*testing.T,\\|test\\|func\\|Test_addUrlNode\\|Test_addFolderNode\\|Test_addTagNode\\|Test_PlaceBookmarkTimeParsing\\|Test_scanBookmarks\\|Test_scanFolders\\|Test_FindModifiedBookmarks\\|Test_FindModifiedFolders"): error parsing regexp: missing closing ): `TestMain\|Test(name\|string,\|t\|*testing.T,\|test\|func\|Test_addUrlNode\|Test_addFolderNode\|Test_addTagNode\|Test_PlaceBookmarkTimeParsing\|Test_scanBookmarks\|Test_scanFolders\|Test_FindModifiedBookmarks\|Test_FindModifiedFolders`
  /go/utils.lua:793 |1: FAIL	***/gomark/firefox	0.013s
  /go/utils.lua:793 |1: 
  o/null_ls.lua:87 |1: {}
```

Here is the list of all test functions in my file:
```
  TestMain         
  setupFirefox     
  runPlacesTest    
  Test_addUrlNode  
  Test_addFolderNode
  Test_addTagNode  
  Test_PlaceBookmarkTimeParsing
  findTagsInNodeTree
  Test_scanBookmarks
  Test_scanFolders 
  Test_FindModifiedBookmarks
  Test_FindModifiedFolders
```

**Comment by ray-x** [comment]
This looks strange:
```
Test(name\\|string,\\|t\\|*testing.T,\\|test\\|func\\
```
Could you send the function signature for this? look like the regex is not correct to get the function name. 
Could you send what function look like for `Test`, thanks!

**Comment by blob42** [comment]
I think it is referring to this function signature:
`func runPlacesTest(name string, t *testing.T, test func(t *testing.T)) {`

It's a helper function that runs tests given a name for the test

**Comment by blob42** [comment]
Is there a way to customize the generator to run the test of the currently active function under the cursor ? Since the code action test is working this would solve the problem

**Comment by ray-x** [comment]
Pushed a fix for it. Please check if it works for you or not, Thanks!

**Comment by blob42** [comment]
Thank you very much this fixes the issue. There was an other minor issue I sent a quick PR for.
