### ISSUE TITLE
Stopping debugger with Shift S doesn't exit cleanly

### ISSUE THREAD

**Issue by clarkezone** [ray-x/go.nvim#281]
I notice that leaving a debug session with shift S key leaves nvim in a broken state.. all the debug windows close and the debugger attaches but the keybindings think I'm still debugging (eg pressing w pops up a window saying No Expression, pressing b toggles breakpoint).  If i do a GoDebug -s this fixes is.  LMK if you need a more detailed repo.

**Comment by ray-x** [comment]
Yes, it is a bit confusing. Pushed a fix for it.

**Comment by clarkezone** [comment]
Fixed.

One more (can open a new issue if you like).. GoTest when there is a failing case, hit enter on the failure in the fix list to go to line number, get a window with red text in it expected ; found EOF rather than the source file.

**Comment by ray-x** [comment]
Could you send the structure of test file/project? Also a screenshot of failed quickfix item as well. thanks! 
I think it may be related to the folder structure.

**Comment by clarkezone** [comment]
The project is the gitignoresupport branch of: https://github.com/clarkezone/rk/tree/gitignoresupport

The test file is in the same dir as the source file.

Immediately after running tests via GoTests:

<img width="1572" alt="Screenshot 2023-02-01 at 7 50 25 AM" src="https://user-images.githubusercontent.com/1128250/216093948-a984ca3f-3ce9-4337-85e8-5cbca7437b36.png">

After pressing enter to goto failing line:

<img width="1572" alt="Screenshot 2023-02-01 at 7 50 42 AM" src="https://user-images.githubusercontent.com/1128250/216094096-9e734a04-627b-4c92-b723-ec2e39921d66.png">

**Comment by ray-x** [comment]
Thanks for reporting. It was a bug. Should have been fixed in the latest version.

**Comment by clarkezone** [comment]
Fixed! Thx!
