### ISSUE TITLE
gd and gr not working after latest ray-x/go.nvim update

### ISSUE THREAD

**Issue by rodrigc** [ray-x/go.nvim#287]
Hey @ray-x , I was wondering if you could help.

I haven't changed my neovim config which is at:
https://github.com/rodrigc/neovim-setup/tree/main/.config/nvim

I recently did a `PackerSync` to update my dependencies which updated `ray-x/go.nvim` to https://github.com/ray-x/go.nvim/commit/3cdd68a17ffebcb85a0dd37332e081b0c0eca76d, and also update `ray-x/go.nvim`, and now
my keybindings for `gd` and `gr` are not executing the proper functions to go-to-definition and go-to-references.

Any idea what the problem might be?

I load go.nvim here:
https://github.com/rodrigc/neovim-setup/blob/main/.config/nvim/lua/config/go.lua

and my lsp keybindings are here:

https://github.com/rodrigc/neovim-setup/blob/main/.config/nvim/lua/config/lsp.lua

I am using neovim 0.8.3.

Thanks for your help!
Great plugin, I use it every day!

**Comment by rodrigc** [comment]
BTW, I backreved go.nvim to 
https://github.com/ray-x/go.nvim/commit/3a853d50afd2b9ed56fe263420b3e873b6285544

and got a working setup.

**Comment by ray-x** [comment]
A fix was committed. Could you check?

**Comment by rodrigc** [comment]
It works now!  Thank you!
