### ISSUE TITLE
Go Auto Format And Import Not Working

### ISSUE THREAD

**Issue by asyrawih** [ray-x/go.nvim#288]
<img width="831" alt="image" src="https://user-images.githubusercontent.com/23658759/218165599-663add52-aa0a-4268-9fc2-72c113da77aa.png">

<img width="663" alt="image" src="https://user-images.githubusercontent.com/23658759/218165648-cf9134d1-ae1e-4cf4-b1de-55560a88f209.png">

**Comment by rodrigc** [comment]
Sounds similar to to some issues I'm having.  See: https://github.com/ray-x/go.nvim/issues/287#issuecomment-1426197431

**Comment by rodrigc** [comment]
@asyrawih But in the meantime, can you run this command inside
neovim:

```
:GoInstallBinaries
```

**Comment by asyrawih** [comment]
thanks reply but i have do this command before
