### ISSUE TITLE
Real time test output

### ISSUE THREAD

**Issue by ldelossa** [ray-x/go.nvim#29]
Hey there,

This is a subjective request so feel free to shoot this down. 

In vim-go when you run a test a new window is opened and all the output is immedaitely present. In your plugin, there is not much indication that tests are indeed running and that nothing went wrong. 

I'd like to see if you have any thoughts on providing some kinda of feedback to the user that tests are indeed running and under way. This could be a buffer with test output as its running or some kinda ui element which suggests tests are currently running.

**Comment by ray-x** [comment]
There is a quickfix.  It should popup once there is console output.

**Comment by ldelossa** [comment]
Ah, sorry, i guess my test just runs faster then i thought. At first it appeared all output is buffered first then sent to a vim buffer (not real time)
