### ISSUE TITLE
:GoAddTag don't work and show some error

### ISSUE THREAD

**Issue by Ynoop** [ray-x/go.nvim#293]
I am use :GoAddTag on my demo. But it do not works.

```golang
package main

type S struct {
	A int
}

func main() {
}
```
this is error message:
----
installing gomodifytags
Error executing Lua callback: Vim:E475: Invalid value for argument cmd: 'gomodifytags' is not executable
stack traceback:
        [C]: in function 'jobstart'
        ...l\nvim-data\site\pack\packer\opt\go.nvim/lua/go/tags.lua:75: in function 'modify'
        ...l\nvim-data\site\pack\packer\opt\go.nvim/lua/go/tags.lua:116: in function 'add'
        ...im-data\site\pack\packer\opt\go.nvim/lua/go/commands.lua:255: in function <...im-data\site\pack\packer\opt\go.nvim/lua/go/commands.lua:254>

I have used :GoInstallBinaries when I first opend gofile and $GOPATH/bin exist gomodifytags

**Comment by ray-x** [comment]
Is  $GOPATH/bin added to $PATH? What os/shell you are using?

**Comment by Ynoop** [comment]
> 

I have added $GOPATH/bin to $PATH.I am using PowerShell7 now.

**Comment by Ynoop** [comment]
> > 
> 
> I have added $GOPATH/bin to $PATH.I am using PowerShell7 now.

I am sorry, I checked my $PATH without $GOPATH/bin, when add it.It's works.
