### ISSUE TITLE
GoTestXXXX with flag -C for coverage not working

### ISSUE THREAD

**Issue by ybbond** [ray-x/go.nvim#296]
## Summary

I tried

```sh
GoTest -n -C=coverage.out
GoTest -n -C coverage.out
GoTestFunc -C=coverage.out
GoTestFunc -C coverage.out
```

but the output will always be

```sh
go test -run '^Test_AcceptLeadOfferHandler$' ./domain/leadassignments succeed
```

## Other Case

other flag is working, such as

```sh
GoTestFunc -t test
```

outputs

```sh
go test -tags=test -run '^Test_AcceptLeadOfferHandler$' ./domain/leadassignments succeed
```

## Expected Result

output for test function with coverage flag should be 

```sh
go test -coverprofile=coverage.out -run '^Test_AcceptLeadOfferHandler$' ./domain/leadassignments succeed
```

## Platform
- latest macos
- latest HEAD neovim
- latest go.nvim

**Comment by ray-x** [comment]
You are correct. Seems this argument was broken.
I pushed a fix for it. Could you check if it works?
Thanks!

**Comment by ybbond** [comment]
you are fast response and I really appreciate that!

however, I think the correct command flag should be `-coverprofile`. by that, the test coverage file not generated

I created PR for that, though I cannot run lua unit test so I rely on GitHub runner
