### ISSUE TITLE
Module 'vim.lsp.codelens' not found

### ISSUE THREAD

**Issue by juanandresgs** [ray-x/go.nvim#30]
Nvim is pretty unhappy about not finding this codelens module. I've followed the setup as instructed but can't figure out what's missing. Any guidance?
<img width="1038" alt="Screen Shot 2021-09-12 at 10 41 45 PM" src="https://user-images.githubusercontent.com/15952691/133016181-79fcef9a-6e98-42e2-8bef-fc359c4944ca.png">

**Comment by ray-x** [comment]
What vim version you are using?
codelens is a feature from neovim 0.6.0 released a few months back. Make sure you are using the latest or you have to disable codelens.

**Comment by juanandresgs** [comment]
Agh, of course. That was it.
Thank you for the prompt reply :)
