### ISSUE TITLE
Running GoUpdateBinaries in headless mode from the command line

### ISSUE THREAD

**Issue by farzadmf** [ray-x/go.nvim#305]
Hi, I have a function I normally use to do an "update all" of neovim, and I'm trying to update go binaries installed by `go.nvim`

So, when I run this:
```
nvim --headlesss +'GoUpdateBinaries' +qa
```

I think `GoUpdateBinaries` is running asynchronously, and the command above won't wait for it, and it immediately reaches `qa`, and quits `nvim`.

I was wondering if there's a way that I can run `GoUpdateBinaries` and somewhoe "wait" for it to finish

Thank you

**Comment by ray-x** [comment]
Please check this thread:
https://github.com/ray-x/go.nvim/issues/273

**Comment by farzadmf** [comment]
Thank you @ray-x for the quick reply. Before I get into implementing what's mentioned in there, do you think there would be any value in having a sync version of the function `GoUpdateBinariesSync` along with the async one that we can use and call?

(because my issue is basically _not_ to get it working (requiring `require('go').setup()` and those stuff), but it's because it's running async)

Or, maybe there would be a "complete event" that I can use for an `autocmd` (like what's mentioned in the first post of the thread you linked)

**Comment by ray-x** [comment]
Please use `install_all_sync()` or `update_all_sync()` . You can create a user command using those functions.

**Comment by farzadmf** [comment]
Yes, thank you. That's what I ended up doing, but I think it would have been nice if the function was built-in.

Just _in case_ anyone has the question as me in the future:
```lua
vim.api.nvim_create_user_command(
  'GoUpdateBinariesSync',
  function() require('go.install').update_all_sync() end,
  {}
)
```
