### ISSUE TITLE
Discussion: adding params for TS modules

### ISSUE THREAD

**Issue by vanhtuan0409** [ray-x/go.nvim#31]
Hi, tks you for a great plugin for Gophers.

I really like your idea of using Treesitter to extract struct/interface/method/... at the current cursor position. I wish to use those exported functions in my own plugin.

However, I might need to pass `bufnr` as a parameter to those functions. The current implementation will not allow that.

```lua
M.get_struct_node_at_pos = function(row, col)
  local query = M.query_struct_block .. " " .. M.query_em_struct_block
  local bufn = vim.fn.bufnr("") -- will only query at the current buffer
  -- ...
end
```

My idea is that we can pass `bufnr` as the 3rd parameter for those function. This should be optional and fallback to the current implementation if missing. I suppose this will not break any current behavior.

```lua
M.get_struct_node_at_pos = function(row, col, bufnr)
  local query = M.query_struct_block .. " " .. M.query_em_struct_block
  local bufn = burnr or vim.fn.bufnr("") -- fallback if bufnr is missing
  -- ...
end
```

Just wondering if you are open to updating. I will gladly make a PR for this modification

**Comment by ray-x** [comment]
Thanks for the feedback.
I am wondering in what scenario may this been used?

**Comment by vanhtuan0409** [comment]
I’m adding code actions for go tooling (goimpl, tag, etc…) via null-ls
The code actions handler is passed with bufnr and I think it is better to use this bufnr param.
Most of the case, I’m thinking that vim.fn.bufnr(“”) will work. Just want to avoid unexpected edge case

**Comment by ray-x** [comment]
Thanks,  I updated a commit for this.
