### ISSUE TITLE
Don't start local dlv dap when using remote dlv

### ISSUE THREAD

**Issue by rainzm** [ray-x/go.nvim#312]
Hi, thank you very much for your plugin, I found a point that may be optimized.
I start the dlv manually on the remote machine, and use the following launch.json
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach region remote",
            "type": "go",
            "request": "attach",
            "mode": "remote",
            "port": 12345,
            "host": "10.0.50.16"
        },
        {
            "name": "Launch region remote",
            "type": "go",
            "request": "launch",
            "mode": "exec",
            "port": 12345,
            "host": "10.0.50.16",
            "program": "/opt/path/bin/region",
            "args": [ "--config", "/etc/path/region.conf" ]
        }
    ]
}
```
In this case, `dap.adapters.go` should not start the dlv dap locally, but directly `callback({ type = 'server', host = host, port = port, options = con_options })`, like this
```go
  dap.adapters.go = function(callback, config)
    ....
    if <some judgment conditions> then
      callback({ type = 'server', host = host, port = port, options = con_options })
    else
      handle, pid_or_err = vim.loop.spawn('dlv', {
        stdio = { nil, stdout, stderr },
        args = { 'dap', '-l', addr },
        initialize_timeout_sec = con_options.initialize_timeout_sec,
        detached = true,
      }, function(code)
        if code ~= 0 then
          vim.schedule(function()
            log('Dlv exited', code)
            vim.notify(string.format('Delve exited with exit code: %d', code), vim.log.levels.WARN)
            _GO_NVIM_CFG.dap_port = _GO_NVIM_CFG.dap_port + 1
          end)
        end

        _ = stdout and stdout:close()
        _ = stderr and stderr:close()
        _ = handle and handle:close()
        stdout = nil
        stderr = nil
        handle = nil
      end)
      assert(handle, 'Error running dlv: ' .. tostring(pid_or_err))
      stdout:read_start(onread)
      stderr:read_start(onread)

      vim.defer_fn(function()
        callback({ type = 'server', host = host, port = port, options = con_options })
      end, 1000)
    end
  end
```

**Comment by rainzm** [comment]
For `Attach region remote`, my remote dlv command is: `dlv --listen=:12345 --headless=true --api-version=2 attach <pid>`; for `Launch region remote`, my remote dlv command is `dlv dap --listen=:12345`.

**Comment by ray-x** [comment]
I pushed a fix for it. Could you check if it works?

**Comment by rainzm** [comment]
Thanks for your fix. This fix should only be for the first case I listed more, and it works. It doesn't handle the second case `Launch region remote`, and I don't have any conclusive ideas about it.
In fact, it always works in the end. Because no matter whether the local dlv dap can be started or not, it will try to connect to the correct dlv dap in the end, but there will be an error that the local dlv dap fails to start.

**Comment by ray-x** [comment]
```
        {
            "name": "Launch region remote",
            "type": "go",
            "request": "launch",
            "mode": "exec",
            "port": 12345,
            "host": "10.0.50.16",
            "program": "/opt/path/bin/region",
            "args": [ "--config", "/etc/path/region.conf" ]
        }
```
As it specified `launch`, a dap server will be started locally

**Comment by rainzm** [comment]
I don’t know if my usage is standardized, but I thought `launch` meant to actively launch the program to be debugged. And my usage worked. I started debug adapter by executing the command `dlv dap --listen=:12345` on the remote server, so there is no need to start it locally. When I start debugging, dap will connect to host:port and then execute the `program+args` in my configuration to launch the program and start debugging. Maybe I should judge whether I need to start locally by the host field. I found this use case on the Internet. As for the meaning of the `mode` field, I didn't find it in the official document.

**Comment by rainzm** [comment]
And，removing `exec` or changing to other modes will not work, if you are interested and have time you can try this use case.

**Comment by ray-x** [comment]
```
The launch feature uses a launch request type configuration in your launch.json file. Its program attribute needs to be the absolute path to either the Go file, or folder containing the main package or test file. In this mode, the Go extension will start the debug session by building and launching the program. The launched program will be terminated when the debug session ends.
```
This means the adapter will launch the program, in this case go.nvim will launch your binary and the dlv-dap server and start the debug session. To debug a remote program (e.g. a go proccess started with `dlv exec`)
You should use
```json
        {
            "name": "Launch region remote",
            "type": "go",
            "request": "attach",
            "mode": "remote",
            "port": 12345,
            "host": "10.0.50.16"
        }
```

**Comment by rainzm** [comment]
Fine, got it and thanks. Maybe this is the correct way to use.
