### ISSUE TITLE
[question/feature request] new file with package name

### ISSUE THREAD

**Issue by brenol** [ray-x/go.nvim#313]
Hi!

Searched for docs but I did not see if go.nvim has this feature.

Basically, the same as **[vim-go](https://github.com/fatih/vim-go/blob/master/doc/vim-go.txt):** 
```
                                                  *'g:go_template_autocreate'*

When a new Go file is created, vim-go automatically fills the buffer content
with a Go code template. By default, the templates under the `templates`
folder are used.  This can be changed with the |'g:go_template_file'| and
|'g:go_template_test_file'| settings to either use a different file in the
same `templates` folder, or to use a file stored elsewhere.

If the new file is created in an already prepopulated package (with other Go
files), in this case a Go code template with only the Go package declaration
(which is automatically determined according to the current package) is added.

To always use the package name instead of the template, enable the
|'g:go_template_use_pkg'| setting.

By default it is enabled.
>
  let g:go_template_autocreate = 1
<

                                                     *'g:go_template_use_pkg'*

Specifies that, rather than using a template, the package name is used if a
new Go file is created. Checkout |'g:go_template_autocreate'| for more info.
By default the template file specified by |'g:go_template_file'| is used.

>
  let g:go_template_use_pkg = 0
<
```

Basically this has two features:
- New file without another file in the same directory, creates a `package main` with empty main body;
- New file with another file in the same directory, creates a file with the same package in the first line

Not sure if its supported, but if it is can you please tell me how I can configure that? Perhaps with another plugin.

Btw go.nvim is great, I basically only miss that feature from vim-go :)

Thanks!

**Comment by ray-x** [comment]
not supported yet. did you che if snippets could resolve you feature request?

**Comment by brenol** [comment]
Nope, even though I think snippets might work I'd need them to autotrigger (I don't think they world like that though)

Perhaps I can work something out by using something like https://github.com/glepnir/template.nvim, I'll have a look
Thanks

**Comment by brenol** [comment]
> New command `GoNew` added

Wow! Thanks. I'll play with it a little bit to see if I find any issues/unexpected behavior :)
