### ISSUE TITLE
Cannot do :GoImpl

### ISSUE THREAD

**Issue by rmscoal** [ray-x/go.nvim#317]
I am using LunarVim.. And lunarvim uses Lazy.nvim to install which I have successfull instatll go.nvim with lazy.nvim via lunarvim. Other go.nvim functions (the one I've been using) works fine except this GoImpl... It is to worked just fine, but after I did PackerSync (if I'm not mistaken), it just doesntt work anymore. I am new to Neovim too.

Thank you and any help is really appreciated.

https://user-images.githubusercontent.com/101387958/229122698-189d85c1-093e-47d8-991e-7d4dce9eb44b.mov

**Comment by ray-x** [comment]
Just to confirm if you have treesitter and go parser installed.

**Comment by rmscoal** [comment]
You're absolutely right, turns out I have not installed the parser for go. After doing `:TSInstall go` in LunarVim, it fixes it. Sorry for bothering and thank you very much for the help  😄 🙏🏼 .
