### ISSUE TITLE
[LSP] gopls default config support SemanticToken

### ISSUE THREAD

**Issue by youngxhui** [ray-x/go.nvim#321]
nvim 0.9 has been released which support semantic token, but go.nvim lsp default config not support semanticToken.

**Comment by ray-x** [comment]
I think it is enabled by default:
https://github.com/ray-x/go.nvim/blob/fcc88590e0ad9d4f967ce61e14f2f979acb63b77/lua/go/lsp.lua#L94-L108

**Comment by youngxhui** [comment]
this is my config 

![image](https://user-images.githubusercontent.com/16971804/232370327-d4ff5b19-070f-42bf-b419-4bd6ee38e056.png)

code
![not support semanticToken](https://user-images.githubusercontent.com/16971804/232371388-0f1f65d1-0e91-4b02-b288-82ff11723928.png)

it is not support semanticToken.

when i add config in lsp, it support semanticToken
 
![image](https://user-images.githubusercontent.com/16971804/232372256-704aad21-d090-4323-a447-7c72ac1ba495.png)


```lua
nvim_lsp.gopls.setup({
-- other config
on_attach = {
    -- other config
            client.server_capabilities.semanticTokensProvider = {
              full = {
                delta = false
              },
              legend = {
                -- from https://github.com/golang/tools/blob/master/gopls/internal/lsp/semantic.go#L981
                tokenTypes = {
                  "namespace", "type", "class", "enum", "interface",
                  "struct", "typeParameter", "parameter", "variable", "property", "enumMember",
                  "event", "function", "method", "macro", "keyword", "modifier", "comment",
                  "string", "number", "regexp", "operator",
                },
                tokenModifiers = {
                  "declaration", "definition", "readonly", "static",
                  "deprecated", "abstract", "async", "modification", "documentation", "defaultLibrary",
                },
              },
              range = true,
            }
}

})

```

**Comment by ray-x** [comment]
Pushed a change for this. Could you take a look?

**Comment by youngxhui** [comment]
No effect

**Comment by ray-x** [comment]
what is the result of :
vim.lsp.get_active_clients()[1].server_capabilities.semanticTokensProvider

It should be:

```
{                                                                                                                                                                                               
  full = true,                                                                                                                                                                                  
  legend = {                                                                                                                                                                                    
    tokenModifiers = { "declaration", "definition", "readonly", "static", "deprecated", "abstract", "async", "modification", "documentation", "defaultLibrary" },                               
    tokenTypes = { "namespace", "type", "class", "enum", "interface", "struct", "typeParameter", "parameter", "variable", "property", "enumMember", "event", "function", "method", "macro", "key
word", "modifier", "comment", "string", "number", "regexp", "operator" }                                                                                                                        
  },                                                                                                                                                                                            
  range = true                                                                                                                                                                                  
}     
```

BTW, the setup was loaded when you use go.nvim on_attach

**Comment by ray-x** [comment]
Would be helpful to print out your gopls config
e.g. The output of `lua =vim.lsp.buf_get_clients()`  and post the gopls setup.

**Comment by youngxhui** [comment]
> what is the result of : vim.lsp.get_active_clients()[1].server_capabilities.semanticTokensProvider
> 
> It should be:
> 
> ```
> {                                                                                                                                                                                               
>   full = true,                                                                                                                                                                                  
>   legend = {                                                                                                                                                                                    
>     tokenModifiers = { "declaration", "definition", "readonly", "static", "deprecated", "abstract", "async", "modification", "documentation", "defaultLibrary" },                               
>     tokenTypes = { "namespace", "type", "class", "enum", "interface", "struct", "typeParameter", "parameter", "variable", "property", "enumMember", "event", "function", "method", "macro", "key
> word", "modifier", "comment", "string", "number", "regexp", "operator" }                                                                                                                        
>   },                                                                                                                                                                                            
>   range = true                                                                                                                                                                                  
> }     
> ```
> 
> BTW, the setup was loaded when you use go.nvim on_attach



output

```
:lua =vim.lsp.get_active_clients()[1].server_capabilities.semanticTokensProvider

{
  full = {
    delta = false
  },
  legend = {
    tokenModifiers = { "declaration", "definition", "readonly", "static", "depre
cated", "abstract", "async", "modification", "documentation", "defaultLibrary" }
,
    tokenTypes = { "namespace", "type", "class", "enum", "interface", "struct",
"typeParameter", "parameter", "variable", "property", "enumMember", "event", "fu
nction", "method", "macro", "keyword", "modifier", "comment", "string", "number"
, "regexp", "operator" }
  },
  range = true
}
```

**Comment by ray-x** [comment]
I checked your default config. You did not enable lsp_cfg by default.
You should use this:
```lua
require('go').setup({
  lsp_cfg = true  -- it is false by default
})

```

**Comment by youngxhui** [comment]
thanks. i enable `lsp_cfg = true`, nvim's semanticToken work successful.
