### ISSUE TITLE
Cannot open :GoTest in floating window

### ISSUE THREAD

**Issue by 1garo** [ray-x/go.nvim#335]
When I run :GoTest it just pop out a little window in the bottom left corner

![image](https://github.com/ray-x/go.nvim/assets/44412643/9818110c-38e7-4634-943a-7229c368e626)

my nvim config using lazy.nvim
![image](https://github.com/ray-x/go.nvim/assets/44412643/d149b583-99bb-40fa-ab4f-0c76c8d3b788)

**Comment by ray-x** [comment]
`:GoTest -F` ?

**Comment by i-vrnv** [comment]
I was confused too. Because I didn't get to the `GoTestXXX Arguments` section, and the `Build and test` section doesn't say anything about a floating window ¯\_(ツ)_/¯

**Comment by ray-x** [comment]
Depends on your config. If you have floating enabled by default in the config, `GoTestxxx` should pop up a floating windows

**Comment by ray-x** [comment]
Need either specify `GoTest -F` (with -F option) or in setup
```lua
  ...
  run_in_floaterm=true
  ...
```
