### ISSUE TITLE
`run_in_floaterm` overrides test_runner is using go

### ISSUE THREAD

**Issue by MadsRC** [ray-x/go.nvim#336]
I recently tried setting `run_in_floaterm` and noticed that the next time I ran `:GoTest`, `richgo test -v ...` would be executed instead of the regular go test runner I have configured.

I then tried to reconfigure `test_runner` to use `richgo` instead, and that caused `richgo test ...` to be run when I ran `:GoTest` (notice the missing `-v` despite also having `verbose_tests` set to `true` (I know it's deprecated).

I had a look at the codebase, but couldn't immediately locate the culprit - Lua isn't my strong side.

This was replicated using the default config from the README.md file.

**Comment by ray-x** [comment]
Yes, richgo will overrides default test_runner if running in floating term... This is because it looks better in floating terminal.
Do you want me adding `-v` to the `richgo test` ?

**Comment by shaunduncan** [comment]
I found this issue after experiencing the same behavior. Personally I would expect it to honor `test_runner` regardless of using `run_in_floaterm` or not, specifically because that is the output I prefer to see.

**Comment by ray-x** [comment]
I think the issue is obsolete, as `richgo` has been removed. other `test_runner` will not be override `run_in_floaterm` setting.
