### ISSUE TITLE
allow arbitrary arguments to GoTest

### ISSUE THREAD

**Issue by ldelossa** [ray-x/go.nvim#34]
Right now it seems like "GoTest" arguments are limited to just providing a tag.

Other go plugins like vim-go allow for any arbitrary flags to be provided at the end of the "GoTest" command.

This is useful  for only testing a particular package from neovim: "GoTest ./pkg/mypackage"

**Comment by ray-x** [comment]
You can do following now
```
GoTest ./pkg/... -tag=unit
```

**Comment by ldelossa** [comment]
Awesome, thanks a lot.
