### ISSUE TITLE
Disable errshadow

### ISSUE THREAD

**Issue by gonzaloserrano** [ray-x/go.nvim#348]
Hi,

I'm not finding the combination to hide this:

<img width="713" alt="CleanShot 2023-06-02 at 13 01 40@2x" src="https://github.com/ray-x/go.nvim/assets/349328/2df5f870-5b48-49a8-9106-803062537441">

Any hints?

**Comment by ray-x** [comment]
see this issue
https://github.com/ray-x/go.nvim/issues/388
