### ISSUE TITLE
Improve GoTestSubCase

### ISSUE THREAD

**Issue by thuan1412** [ray-x/go.nvim#358]
Currently, the `GoTestSubCase` command has two small problems:
1. It only supports table-drivent test pattern and does not support normal subtest pattern.
2. We must put the cursor in the name of the testcase to run the testcase.

We should resolve these two problems to increase productivity when writing tests.

**Comment by ray-x** [comment]
For 1 an alterative is snippets included in go.nvim
for 2, it is by design, as the plugin need to know the name of testcase to run a specific test. But you do not need to put the cursor on the name, anywhere inside the testcase should be fine. For table driven test you need to put cursor on the table entry to run a specific test case.

**Comment by thuan1412** [comment]
1. Could you give more detail about the snippets?
2. I tried to run `GoTestSubCase` where I put the cursor outside of the testcase name, but it does not run the `1 + 2 = 3` testcase, instead, it run the whole `Test_add` function.
```golang 
package add

import "testing"

func Test_add(t *testing.T) {
	type args struct {
		a int
		b int
	}
	tests := []struct {
		name string
		args args
		want int
	}{
		{
			name: "1 + 2 = 3",
			args: args{1, 2},
			want: 3,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := add(tt.args.a, tt.args.b); got != tt.want {
				t.Errorf("add() = %v, want %v", got, tt.want)
			}
		})
	}
}

```

**Comment by ray-x** [comment]
Yes, I know it is a bit painful. I will need to update the AST parser to handle TestSubCase.

**Comment by FernandoBasso** [comment]
`GoTestSubCase` is working fine for one level sub test. It covers something like this:

```shell
$ go test -v -run 'TestTopLevel/SubCase'
```

Would it be too hard to make it cover deeper levels of sub cases?
Something like:

```go
func TestTopLevel(t *testing.T) {
  t.Run("SubCase", func(t *testing.T) {
    t.Run("SubSubCase1", func(t *testing.T) {
      // Assert something.
    })

    t.Run("SubSubCase2", func(t *testing.T) {
      // Assert some other thing.
    })
  })
}
```

We can, from the command line, run specific nested sub sub tests:

```shell
$ go test -v -run 'TestTopLevel/SubCase/SubSubCase1'
$ go test -v -run 'TestTopLevel/SubCase/SubSubCase2'
```

At least currently, `GoTestSubCase` doesn't seem to cover cases like that.
