### ISSUE TITLE
GoDoc on hovered input and GoDef

### ISSUE THREAD

**Issue by khatibomar** [ray-x/go.nvim#36]
Can you please add this features ?
when you place cursor on a word and type GoDoc it will open a popup containing doc to it (just like vim.go)
Also GoDef which take you to the definition of what ever cursor on.

**Comment by ray-x** [comment]
I think 
If you have lsp configured, you can use `lua vim.lsp.buf.hover()` to check document of current symbol
also you can use `lua vim.lsp.buf.definition()` to jump to definition

**Comment by ray-x** [comment]
GoDoc will default to lsp hover if no arguments are provided.
