### ISSUE TITLE
Disable treesitter highlight injection for SQL and json

### ISSUE THREAD

**Issue by razcoen** [ray-x/go.nvim#360]
How do I disable the treesitter highlight injection for SQL and JSON?
It has too many false positives for me so I prefer to disable it.

I tried setting `textobjects` to false but without luck.

**Comment by hay-kot** [comment]
Any updates on this and/or if it's possible to disable the highlight injection?

**Comment by ray-x** [comment]
Currently, it can not be done.
It requires different syntax/logic to conditionally inject, which has not been implemented.
Could you show some failed injection cases?

**Comment by hay-kot** [comment]
Here's an example, I wouldn't really expect it to work here though. 

![CleanShot 2024-11-03 at 22 32 11@2x](https://github.com/user-attachments/assets/1dc3c803-28d9-471e-aeb6-18ab77bc854a)

To be honest, I just don't really like the highlighting anyways, just personal preference.

**Comment by ray-x** [comment]
I agree it wont work as `) AS v(id...` can not parsed by sql_treesitter. Maybe you can use sprintf. But that is not same topic.

The only way to disable it is to override the injected queries manually.  It is feasible but it will take me some time.

**Comment by hay-kot** [comment]
No worries, I totally understand. FWIW I did find a work around with removing "go" from the `ft` config option.

```lua
ft = { "gomod" },
``` 

This still lets me use `GoAddTag` which I think is really the only thing I use from this plugin for now - so I'm happy :D

Thanks for all the hard work on this plugin!

**Comment by ray-x** [comment]
I feel it would still be best to call 
```lua
vim.treesitter.query.set("go", "injections", "") 
```
after load go.nvim to clear all injections. while keep your filetype settings
also, you can do 

```lua
vim.treesitter.query.set("go", "injections", "") 
vim.cmd('e')
```
If injections still loading
