### ISSUE TITLE
Support show call hierarchy

### ISSUE THREAD

**Issue by sp71** [ray-x/go.nvim#361]
Offer feature to show call hierarchy of a function.

**Comment by ray-x** [comment]
I had been using navigator.lua for callHierarchy. Not sure should I duplicate the work over to go.nvim
![image](https://github.com/ray-x/go.nvim/assets/1681295/4bd40959-1b0a-4b1e-894f-19ae18e7f4d6)

**Comment by ray-x** [comment]
I will close the issue for now as there is a workaround.
