### ISSUE TITLE
Enabling capabilities yields an error by calling the deprecated 'show_line_diagnostics' function

### ISSUE THREAD

**Issue by pedro-git-projects** [ray-x/go.nvim#362]
The "LSP cmp support" section on the github page suggests the following for setting up capabilities:

```lua
local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())
require('go').setup({
  -- other setups ....
  lsp_cfg = {
    capabilities = capabilities,
    -- other setups
  },
})
```

This is deprecated and will instantly cause the following error:

```
cmp_nvim_lsp.update_capabilities is deprecated, use cmp_nvim_lsp.default_capabilities instead.
This feature will be removed in cmp-nvim-lsp version 1.0.0
```

I fixed this issue by updating to the new adequate function:

```lua
local capabilities = require('cmp_nvim_lsp').default_capabilities(vim.lsp.protocol.make_client_capabilities())
require('go').setup({
    lsp_cfg = {
        capabilities = capabilities,
    },
})
```
This seems to solve the problem, however, when performing certain operations, in my case, reopening nvim-tree in a Go project for example, will cause yield the follwing error:

```
E5108: Error executing lua [string ":lua"]:1: attempt to call field 'show_line_diagnostics' (a nil value)
stack traceback:
        [string ":lua"]:1: in main chunk
```

This suggests that the way go.vim's LSP configuration sets up capabilities is somehow calling a deprecated function. If anyone can confirm this or provide solutions, I would be grateful. Additionally, updating the README to reflect the new way of setting up capabilities would be appreciated.

**Comment by ray-x** [comment]
I pushed a fix and please check if it works for you.

**Comment by pedro-git-projects** [comment]
It does, thank you!
