### ISSUE TITLE
Discard new changes on save

### ISSUE THREAD

**Issue by khatibomar** [ray-x/go.nvim#37]
Hello When I write changes to a file and save them , they got discarded
```lua
hooks.add("setup_mappings", function(map)
    -- go
    vim.api.nvim_exec([[ autocmd BufWritePre *.go :silent! lua require('go.format').gofmt() ]], false)
    vim.api.nvim_exec([[ autocmd BufWritePre *.go :silent! lua require('go.format').goimport() ]], false)
 ```
when I comment those lines , it works again. the loosing is only in `*.go` files.
I got this error when I open vim , also it goes away when I comment lines above.

![image](https://user-images.githubusercontent.com/35725554/138114989-8313f105-43a6-431d-b1fa-764ef82985fb.png)

**Comment by rodrigc** [comment]
I think you do not need both:
```
vim.api.nvim_exec([[ autocmd BufWritePre *.go :silent! lua require('go.format').gofmt() ]], false)
vim.api.nvim_exec([[ autocmd BufWritePre *.go :silent! lua require('go.format').goimport() ]], false)
```

You only need one of them.  Otherwise it will try to format twice on saving.
I have this PR to clarify the README: https://github.com/ray-x/go.nvim/pull/70/files

**Comment by khatibomar** [comment]
Hi I have returned to my old config because I am lazy , this config is far far far far better from mine but I am used to my workflow.
My mistake was to replace it directly with mine maybe I will do an VM and play with it until I became familiar.

**Comment by rodrigc** [comment]
I am new to go.nvim, but you can look at my config if you want some ideas:

## Setup
* Default setup: https://github.com/rodrigc/neovim-setup/tree/main/.config/nvim
* Init: https://github.com/rodrigc/neovim-setup/blob/main/.config/nvim/init.lua
* plugins: https://github.com/rodrigc/neovim-setup/blob/main/.config/nvim/lua/plugins.lua
* go setup:  https://github.com/rodrigc/neovim-setup/blob/main/.config/nvim/lua/config/go.lua

**Comment by ray-x** [comment]
Close as no report from other users. I can not reproduce as well.
