### ISSUE TITLE
GoRun ignores hyphen "-arg" 

### ISSUE THREAD

**Issue by ogios** [ray-x/go.nvim#377]
**command:**
![image](https://github.com/ray-x/go.nvim/assets/96933655/33459ee1-18f6-4779-8aa2-dda8e81c1ba8)

**it runs:**
![image](https://github.com/ray-x/go.nvim/assets/96933655/98ea9f06-cca7-4112-9d3f-daed06a9c1a8)

**Comment by ray-x** [comment]
I submitted a fix
You need to run like `GoRun main.go -a -c\ ./setting.yaml` so that "-c ./setting.yaml" will passed to main.go
