### ISSUE TITLE
Error while trying to add json to struct

### ISSUE THREAD

**Issue by rnp0728** [ray-x/go.nvim#378]
![image](https://github.com/ray-x/go.nvim/assets/98372124/0d23622d-1a9d-4f6e-9aa6-36d1155cec8f)

**Comment by ray-x** [comment]
what is the `checkhealth` result for `go.nvim` ?

**Comment by rnp0728** [comment]
> what is the `checkhealth` result for `go.nvim` ?

sorry for being late, it got resolved. It happend due to my fault. I was new at that time so I did some wrong configurations. Thanks a lot the the reply.
