### ISSUE TITLE
packer.nvim: Error running config for go.nvim: [string "..."]:0: attempt to index a boolean value 

### ISSUE THREAD

**Issue by zbindenren** [ray-x/go.nvim#387]
Issue with neovim 0.9.4.

Config:

```lua
	use({
		"ray-x/go.nvim",
		config = function()
			require("go").setup()
		end,
	})

```

**Comment by ray-x** [comment]
I used `https://github.com/ray-x/go.nvim/blob/master/playground/init_packer.lua` to verify this issue. But I can not reproduce it.
Also FYI, packer was achieved.

**Comment by ray-x** [comment]
As paker has been EOL, I have no intension of supporting issues related to packer.nvim.
