### ISSUE TITLE
Latest changes break neovim

### ISSUE THREAD

**Issue by lordvidex** [ray-x/go.nvim#389]
Updated go.nvim plugin and i started getting the following error when i'm in insert mode when the LSP is on

Error executing vim.schedule lua callback: ...l/Cellar/neovim/0.9
.4/share/nvim/runtime/lua/vim/lsp.lua:2319: attempt to call upvalue 'handler' (a nil value)
stack traceback:
        ...l/Cellar/neovim/0.9.4/share/nvim/runtime/lua/vim/lsp.lua:2319: in function 'handler'
        ...l/Cellar/neovim/0.9.4/share/nvim/runtime/lua/vim/lsp.lua:1056: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>

**Comment by ray-x** [comment]
Could you check if the fix works for you?

**Comment by lordvidex** [comment]
Fixed
