### ISSUE TITLE
Invalid workig directory when debugging tests

### ISSUE THREAD

**Issue by szaffarano** [ray-x/go.nvim#39]
Given a test that reads a file relative to the package folder, let's suppose the following project structure:
```sh.
$ tree
├── dummy
│   ├── dummy.go
│   ├── dummy_test.go
│   └── testdata
│       └── goldenfile
└── go.mod
$ cat dummy/dummy_test.go
package dummy

import (
	"os"
	"path"
	"testing"
)

func TestDummy(t *testing.T) {
	cases, err := os.Open(path.Join("testdata", "goldenfile"))
	if err != nil {
		t.Error(err)
	}
       // ........
}
$ go test ./dummy -test.run TestDummy
ok      tt/dummy        0.001s

```
It fails when it's debugged, i.e.: `:GoDebug test`
```
--- FAIL: TestDummy (9.10s)
    dummy_test.go:13: open testdata/goldenfile: no such file or directory
FAIL
```
Changing the `os.Open` sentence to `cases, err := os.Open(path.Join("dummy", "testdata", "goldenfile"))`, it works fine.

**Comment by ray-x** [comment]
I think it is expected. For me, the vim will set root to either `.git` or `go.mod`, so you will need to use `dummy/testdata/goldenfile` to access the test folder.

But suggestions are welcome.

**Comment by szaffarano** [comment]
But this means that I have to change this kind of tests when I want to debug them.  IMHO the behavior should be the same, either running or debugging.

**Comment by ray-x** [comment]
You can change your current folder from vim with `cd` and run the test with `GoTest .`

**Comment by szaffarano** [comment]
Ok, it's a good workaround.  Thanks @ray-x 
I'm closing the issue
