### ISSUE TITLE
Old inlay hints types

### ISSUE THREAD

**Issue by hurricanehrndz** [ray-x/go.nvim#396]
I really miss seeing the function definition and return types like in the image below, anyway to get that back

![image](https://github.com/ray-x/go.nvim/assets/5804237/27dc9c34-bf94-4112-a4fd-bfedb1be163a)

**Comment by ray-x** [comment]
I pushed a change so the old style of lsp hint will work for neovim 0.10
please set `lsp_inlay_hints.style='eol'`
