### ISSUE TITLE
Getting error about `inlay_hint`

### ISSUE THREAD

**Issue by 1995parham** [ray-x/go.nvim#398]
I am using the nightly build of neovim and recently I've got the following error:

```
Error executing vim.schedule lua callback: ...share/nvim/site/pack/packer/opt/go.nvim/lua/go/inlay.lua:312: attempt to call field 'inlay_hint' (a table value)
```

**Comment by ray-x** [comment]
It seems something modified the internal vim.lsp.inlay_hint. It is type is function for neovim nightly and it is nil for release version

**Comment by 1995parham** [comment]
Yes, you are right. Yesterday neovim merged https://github.com/neovim/neovim/issues/25069, I think a change is required in the code to make it compatible with the upcoming release.

**Comment by luv2code** [comment]
Changing [this line](https://github.com/ray-x/go.nvim/blob/f9672fd446d6527ddc3f0c180bb7e3320e450546/lua/go/inlay.lua#L312) from
```lua
      vim.lsp.inlay_hint(bufnr, enabled)
```
to
```lua
      vim.lsp.inlay_hint.enable(bufnr, enabled)
```
fixed it for me.

It looks like they changed the API to enable more lsp interactions with inlay hints.

**Comment by 1995parham** [comment]
@ray-x what do you think about providing MR for changing this by version constraint?

**Comment by ray-x** [comment]
Update pushed. 
I have to drop support for users who stay with the old version of nightly.

**Comment by 1995parham** [comment]
Awesome :heart_eyes: :woman_dancing:
