### ISSUE TITLE
GoRun - GoDebug not working on windows

### ISSUE THREAD

**Issue by ITHDevelopment** [ray-x/go.nvim#40]
Firts of all, I just intalled your plugin and already love it. It have several features and run so fast.
The thing is, when trying to do anything related to the project path like `GoRun` - `GoRun ./cmd` or `GoDebug` it says that it **doesn't find the main module** (.projectRoot/cmd/main.go - go.mod - go.sum) , which i'm running the code from. Obviously I have all my modules declared, builded and linked with each other.
Hope you can help me, it's such a great plugin!!

OS: Windows 10
Shell: Powershell
Nvim version: v0.5.1

**Comment by ray-x** [comment]
I guess that in windows, you need to use `GoRun .\\cmd` ?
You need to set the path the same as you did when you run it with `go run`  in windows cmd.

**Comment by ITHDevelopment** [comment]
Just tried that, same response :(
I also found out that it doesn't detect any modules. Because I thought, it should at least work inside cmd folder, but when I GoRun there, it literally does nothing. So I tried GoDebug, but the log says it doesn't detect any of the non-standard imported modules so it fails.

**Comment by ray-x** [comment]
I think the issue is more regarding windows vs linux/Mac have different path name format
`.projectRoot/cmd/main.go` does not seem to be a valid path in windows.

For debug . you may have same issue. As in `dap.lua`, the code says

```
    dap_cfg.program = "./${relativeFileDirname}"
```
I doubt it is valid in windows....

**Comment by ITHDevelopment** [comment]
Okey, I have reduced the problem to the minimum creating a new golang project `./go` which file structure is:
**main.go
go.mod
go.sum
pkg/sum.go**
This show me a couple things, firts of all GoRun/GoDebug works **only if you enter neovim inside the project folder**, otherwise it doesn't matter if you run GoRun or GoRun ./go or whatever it always throw an error.
Once you open neovim inside ./go folder, GoRun works well and what remains is GoDebug. 
Another thing I figured out it's that for the plugin to work you **must have a global main.go with its respective go.mod and go.sum**. If you have your main file and stuff inside, let's say cmd folder, again , no matter what command you run it always fails saying that it doesn't detect any of the imported modules (local or external).

**Comment by ray-x** [comment]
In your windows command line, with old project structure, does any of this work 
```
cmd> go run .projectRoot/cmd/main.go
cmd> go run .projectRoot/cmd/...
cmd> go run .projectRoot\\cmd\\...
cmd> go run .projectRoot\\cmd\\main.go
```

**Comment by ITHDevelopment** [comment]
Yes, `go run ./cmd` works perfect. And also find out what was making `GoRun ./cmd` not work.
The only thing that still doesn't work is GoDebug. But you already helped so much and I think that it has more to do with nvim-dap or nvim-dap-go that what it has to do with this plugin.
Thank u for the patience! :)
You can close the issue if you feel like

**Comment by ray-x** [comment]
link to dap issue:
https://github.com/mfussenegger/nvim-dap/issues/346
