### ISSUE TITLE
golines not working on save

### ISSUE THREAD

**Issue by lightbluepoppy** [ray-x/go.nvim#400]
Currently, these lines of code is not enough to run GoFmt on save which runs `golines` which formats long lines of code.
When I run `:GoFmt`, golines runs and lines are being formatted.

```go

local format_sync_grp = vim.api.nvim_create_augroup("GoImport", {})
vim.api.nvim_create_autocmd("BufWritePre", {
    pattern = "*.go",
    callback = function()
        require('go.format').goimport()
    end,
    group = format_sync_grp,
})

require('go').setup({
    max_line_len = 80, -- max line length in golines format, Target maximum line length for golines
})

```

How is it possible to run golines properly on save?

**Comment by ray-x** [comment]
you may need to config `goimport='golines'`

**Comment by dimitarvp** [comment]
I was using `command = 'GoFmt'` and not the `callback` block and also didn't have the `golines` configuration. I added both and now my Golang code gets auto-formatted on save! Thanks to both of you!

Just to help future readers: it's `goimports='golines'` now (plural `goimports` and NOT `goimport`).

(Also, now as in: 2024-APR-02.)

**Comment by Chaitanyabsprip** [comment]
how do I add other arugments to golines?

**Comment by ray-x** [comment]
you can use `gofmt_args` and set `gofmt` to `golines`
