### ISSUE TITLE
Equivalent of GoImplements from Fatih/vim-go?

### ISSUE THREAD

**Issue by adelowo** [ray-x/go.nvim#408]
Hi @ray-x , do you have plans to add some method like `GoImplements` so implementations of a specific interface can be shown in a list and cycled through

**Comment by ray-x** [comment]
Not really, as it already supported by gopls
you can define your key binding for `vim.lsp.buf.implementation()`. If you need a UI for it, there are lots of options, e.g. telescope `builtin.lsp_implementations`, `ray-x/navigator.lua` ...

**Comment by ray-x** [comment]
Pushed an update to add `GoImplements` wrapper based on lsp. As it may be 2nd time someone asked this question.

**Comment by adelowo** [comment]
thanks!
