### ISSUE TITLE
GoAddTag doesn't work

### ISSUE THREAD

**Issue by xtrats** [ray-x/go.nvim#411]
![2023-12-22_19-07-01 (1)](https://github.com/ray-x/go.nvim/assets/5361387/6ca139a7-f98f-4fcd-bb9b-0d13d360e896)

The go binaries is in the directory `/root/go/bin`, and `/root/go/bin` is in the `$PATH`.

health check result:

```
go: require("go.health").check()

Binaries
- go installed.
- Tool installed: golangci-lint
- Tool installed: gomodifytags
- Tool installed: gofumpt
- Tool installed: gopls
- Tool installed: dlv
- Tool installed: gomvp
- Tool installed: govulncheck
- Tool installed: go-enum
- Tool installed: fillswitch
- Tool installed: fillstruct
- Tool installed: json-to-struct
- Tool installed: gonew
- Tool installed: goimports
- Tool installed: richgo
- Tool installed: ginkgo
- Tool installed: gotests
- Tool installed: mockgen
- Tool installed: guru
- Tool installed: gorename
- Tool installed: callgraph
- Tool installed: impl
- Tool installed: gotestsum
- Tool installed: golines
- Tool installed: iferr
- sed installed.
- curl installed.
- OK All binaries installed

Go Plugin Check
- OK lspconfig: plugin is installed
- OK nvim-treesitter: plugin is installed
- OK guihua: plugin is installed
- WARNING nvim-dap-virtual-text: not installed/loaded
- OK telescope: plugin is installed
- OK nvim-treesitter-go is installed
- WARNING nvim-dap: not installed/loaded
- WARNING nvim-dap-ui: not installed/loaded
- WARNING Not all plugin installed
- OK GOROOT is set
- GOBIN is not set
- Not all environment variables set
- WARNING GOBIN is not in PATH
```

**Comment by ray-x** [comment]
Please check if the issue reproducible with https://github.com/ray-x/go.nvim/blob/master/playground/init_lazy.lua

**Comment by xtrats** [comment]
> Please check if the issue reproducible with https://github.com/ray-x/go.nvim/blob/master/playground/init_lazy.lua

Doesn't work either.

![2023-12-25_19-06-15 (1)](https://github.com/ray-x/go.nvim/assets/5361387/ee469a9f-04a0-4a04-9d4f-6623d766d81a)

The log:

[gonvim.log](https://github.com/ray-x/go.nvim/files/13765742/gonvim.log)

**Comment by xtrats** [comment]
I found something in the log file. I execute the `:GoAddTag` command when my cursor is in the `IdcPosition` struct,  but the json tags added to the `QueryNetModuleInfoResp` struct. I don't know why.

![2023-12-25_19-21-49 (1)](https://github.com/ray-x/go.nvim/assets/5361387/aadaa169-4921-464b-83be-86b3747c9206)

**Comment by ray-x** [comment]
Ok, it should been fixed now. Thanks for the screenshot, it is very helpful.

**Comment by xtrats** [comment]
It works now, thanks for your excellent work.
