### ISSUE TITLE
Question: Should go mod tidy require an LspRestart?

### ISSUE THREAD

**Issue by markhuge** [ray-x/go.nvim#42]
I've noticed that  I need to `:LspRestart` after running `:GoModTidy` to clear import errors. I was going to just write a wrapper that did this automatically, but I was wondering if maybe I just have something misconfigured. Are you seeing the same behavior?

**Comment by ray-x** [comment]
I think that might be true.  I normally will do that because gopls seems will still using old version of go.mod/sum
