### ISSUE TITLE
`GoTestFunc`: Unable to find nodes. Is your query correct?

### ISSUE THREAD

**Issue by Aphoh** [ray-x/go.nvim#43]
Hey there,
Running into this err when running `GoTestFunc`. I've tried with the cursor in the middle of the method name (ex: on the '2' in '256') and in the body of the method.
![Screen Shot 2021-11-16 at 11 10 49 AM](https://user-images.githubusercontent.com/7565007/142050351-db17720d-c362-485c-b5cb-2765452f32bf.png)
Can't seem to get it to work in any of my projects, but for example it fails [here](https://github.com/Aphoh/solana-go-sdk/blob/main/program/secp256k1/instruction_test.go)

My `init.lua` looks like
```
local use = require('packer').use
require('packer').startup(function()
...
  use 'nvim-treesitter/nvim-treesitter'
  -- Additional textobjects for treesitter
  use 'nvim-treesitter/nvim-treesitter-textobjects'
...
  use {'ray-x/go.nvim', requires = { 'nvim-treesitter/nvim-treesitter' } }
...
end)
...
-------------------------------------------------
-- Golang config
-------------------------------------------------
require('go').setup()
vim.api.nvim_exec([[ autocmd BufWritePre (InsertLeave?) <buffer> lua vim.lsp.buf.formatting_sync(nil,500) ]], false)
-- Import on save
vim.api.nvim_exec([[ autocmd BufWritePre *.go :silent! lua require('go.format').goimport() ]], false)
```

`gotests` is on the path, and the `gopls` language server is set 
![Screen Shot 2021-11-16 at 11 16 35 AM](https://user-images.githubusercontent.com/7565007/142050823-4b60c53d-6345-4010-a8bd-ee44af8286e6.png)
up and running.

Any idea why this is happening? Thanks

**Comment by ray-x** [comment]
Could you run a healthcheck in your nvim and see if treesitter configured correctly?

**Comment by Aphoh** [comment]
Ah didn't realize I had to manually do a `:TSInstall go` with treesitter. Thanks!
