### ISSUE TITLE
How to Align sign coverage

### ISSUE THREAD

**Issue by gmtstephane** [ray-x/go.nvim#441]
Hello, 

I wonder how i could align the not covered and covered line as shown as in your readme.

The red line is offset with my green one.

<img width="333" alt="image" src="https://github.com/ray-x/go.nvim/assets/42695797/191207b8-e058-433d-9f37-05ecb635e30b">

And I also wonder how i could have a thinner line, like in my git sign diff provided by nvchad.
I tried setting an half block ascii character, it works, but then i have the feeling that the red one is the inversion ont the green so it look strange.

<img width="333" alt="image" src="https://github.com/ray-x/go.nvim/assets/42695797/80c0cf16-8704-499d-99f7-e58e78aaafc1">

Thanks you

**Comment by ray-x** [comment]
To the first question
`  gocoverage_sign = '█', `
Change it in your config

To the second one, one thing you can try is to increase `sign_priority`
But this should caused by you allowing multiple columns in your sign colunm. Set it back to 1 should also help.

**Comment by gmtstephane** [comment]
Thanks for the quick response. 

If i set :set signcolumn=yes:1   , i still have this . 

<img width="598" alt="image" src="https://github.com/ray-x/go.nvim/assets/42695797/711c28e0-09e8-46c3-a33d-fdea4195829a">

If i change the sign in the config, with "|" for instance, i have this , which is ok for the green one, but the red looks strange.

<img width="584" alt="image" src="https://github.com/ray-x/go.nvim/assets/42695797/beb30f9f-a269-428d-92be-8b56e56559d4">

Thanks for your help 👍🏻

**Comment by ray-x** [comment]
The default sign highlight is defined like this:
```
  sign_covered_hl = 'String', --- highlight group for test covered sign
  sign_partial_hl = 'WarningMsg', --- highlight group for test partially covered sign
  sign_uncovered_hl = 'Error', -- highlight group for uncovered code
```
I think the Error in your vim color scheme may have a red background set

you can change 'Error' so foreground color is red and no background, Or you can define your sign color group without a background color.

**Comment by gmtstephane** [comment]
Thanks that was the color highlight ! 

<img width="388" alt="image" src="https://github.com/ray-x/go.nvim/assets/42695797/4a4de097-3766-4593-8388-47bffae0bb5b">
