### ISSUE TITLE
inlay_hint.lua:383: enable: expected boolean, got table

### ISSUE THREAD

**Issue by bryanmaina** [ray-x/go.nvim#456]
I am running into the following error every time I invoke lspsaga peek definition (before it peek definition shows up the error is thrown - peek definition shows up fine - then the same error appears again after closing peek definition) but it seem like the problem is connected to go.nvim.

```
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/inlay_hint.lua:383: enable: expected boolean, got table
stack traceback:
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        /usr/share/nvim/runtime/lua/vim/lsp/inlay_hint.lua:383: in function 'enable'
        ...are/nvim/site/pack/packer/start/go.nvim/lua/go/inlay.lua:322: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
Press ENTER or type command to continue 
```

**Comment by ray-x** [comment]
https://github.com/ray-x/go.nvim/issues/454
Might need multiple updates to get things to work...

**Comment by Maduki-tech** [comment]
If you update to the latest Neovim Version. The error should be fixed. Seems like this code is already setup for the new Nvim Nighly version.
