### ISSUE TITLE
LspCodeLens highlight group collision

### ISSUE THREAD

**Issue by dstanberry** [ray-x/go.nvim#47]
https://github.com/ray-x/go.nvim/blob/3329238deb8c2294d1b7f5ceffdeb3d5b31fe8be/lua/go/codelens.lua#L30-L35

Having the highlight groups defined in this way can be problematic if they are also set elsewhere by the user (like in a colorscheme, or init.[vim/lua]). Can you make it so that it is configurable or expose a way to choose the group parameters or what they're linked to?

**Comment by ray-x** [comment]
Thanks. 
I think we need add `default` to prevent overwrite. It was fixed in a038113bad1156902d50680cff5b8400164d8b41

**Comment by dstanberry** [comment]
This is close to what I think is the desired behavior, but the `!` overrides the group (if the group is already defined). The docs state that this shouldn't happen so maybe it's an upstream bug.

The only way I can get around this is to explicitly unlink each group after `require("go").setup({...})`:

```lua
  vim.cmd [[
    highlight! default link LspCodeLens NONE
    highlight! default link LspCodeLensText NONE
    highlight! default link LspCodeLensTextSign NONE
    highlight! default link LspCodeLensTextSeparator NONE
  ]]
```

**Comment by ray-x** [comment]
Yes, should be
`highlight default link LspCodeLens NONE`
