### ISSUE TITLE
help finding autocomplete bug: extmark/helper text persists.

### ISSUE THREAD

**Issue by gonzaloserrano** [ray-x/go.nvim#477]
Hi,

Do you know by chance if it's go.nvim the one that renders `println(... args.Type)` above (not the one below) the `println` statement? It gets stuck in there.

https://github.com/ray-x/go.nvim/assets/349328/b249d700-42a3-4fd7-bc53-bb7943e62ebb

Thanks!

**Comment by ray-x** [comment]
I do not think it is something from go.nvim. Also, I have not experienced this issue so far.

**Comment by gonzaloserrano** [comment]
Thanks!

**Comment by gonzaloserrano** [comment]
It was mini.completion, as per https://github.com/echasnovski/mini.nvim/issues/924
