### ISSUE TITLE
Question: does go.nvim work with revive?

### ISSUE THREAD

**Issue by rodrigc** [ray-x/go.nvim#48]
Thanks for your neovim plugin work.  Your work is excellent.

Does go.nvim work with [revive](https://github.com/mgechev/revive)?

This is a drop in replacement for golint which is frozen and deprecated: https://github.com/golang/lint#readme

**Comment by ray-x** [comment]
not by default.
The go.nvim golint is using golangci-lint. I think revive can be enabled by golangci-lint.

**Comment by rodrigc** [comment]
Oh I see, you are correct.

revive is listed here, disabled by default by golangci-lint:
https://golangci-lint.run/usage/linters#disabled-by-default-linters--e--enable
