### ISSUE TITLE
[question] How to make go.nvim to pick up just installed module?

### ISSUE THREAD

**Issue by ribtoks** [ray-x/go.nvim#481]
Hi

Thank you so much for developing go.nvim!

I have this small issue that when I install a new module in the external terminal using `go get ...` and then trying to use it in code, opened in Neovim, `go.nvim` highlights everything with errors and never "sees" the new module, until I fully restart Neovim. Then it immediately picks everything up and no errors show up.

Thank you

**Comment by ray-x** [comment]
1. You can use `GoGet` command provided by `go.nvim`. If you check the code of `goget.lua` you will find after `go get`, the plugin will call `require('go.lsp').watchFileChanged('your_workspace/go.mod')`

2. You can call `LspRestart` provided by nvim to restart gopls

**Comment by ribtoks** [comment]
Thank you for your response! Just in case, is there a way to do `.watchFileChanged('my_workspace/go.mod')` by default? (e.g. via some config)

**Comment by ray-x** [comment]
The plugin does not support config option as `go get` was run outside neovim. You can write a simple function to check if go.mod is updated outside nvim and run watchFileChanged()

**Comment by ribtoks** [comment]
All right. Thank you again!
