### ISSUE TITLE
How to add -gcflags="all=-N -l" in GoTest or GoTestFunc

### ISSUE THREAD

**Issue by runninghai** [ray-x/go.nvim#485]
I tried add -b -gcflags='all=-N -l'
![image](https://github.com/user-attachments/assets/8ff68cd0-1619-4dc9-8b16-a24a8fe76371)
It reponsed like this, failed to parse gcflags

**Comment by ray-x** [comment]
maybe: 
`GoTest -b -gcflags="all-N\ -l"`

**Comment by runninghai** [comment]
Thanks it works.
