### ISSUE TITLE
GoInstallBinaries and GoUpdateBinaries for go.nvim, similar to vim-go?

### ISSUE THREAD

**Issue by rodrigc** [ray-x/go.nvim#49]
Do you think it would be useful to have `GoInstallBinaries` and `GoUpdateBinaries`, similar 
to vim-go: https://github.com/fatih/vim-go/blob/master/doc/vim-go.txt#L496 ?

For example, I found that I did not have `golines` and `gofumpt` installed, so formatting with goimport did not work.
Once I installed those utilities, formatting worked.

**Comment by rodrigc** [comment]
nvim-go also has it: https://github.com/crispgm/nvim-go/blob/c9000d1f64cd17c9bb4eab5024bb63373f180530/doc/nvim-go.txt#L82

**Comment by ray-x** [comment]
New command added

**Comment by rodrigc** [comment]
Thanks for implementing this.  I verified that it works.

However, I don't think `GoInstallBinaries` and `GoUpdateBinaries` takes an argument?

**Comment by rodrigc** [comment]
Also, in these docs: https://github.com/ray-x/go.nvim/commit/7d39be943149e43256dd5e79e342641d3e82111c#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R133

`go re-install`
`go update`

Are not actual go commands.  Might be good to put real go commands here, just to clarify.

**Comment by ray-x** [comment]
Thanks for the suggestions.  The readme updated.

**Comment by rodrigc** [comment]
Thanks for incorporating my suggestions.
I have a few more small suggestions:

https://github.com/ray-x/go.nvim/pull/51

**Comment by rodrigc** [comment]
Do you know what file to edit so that
`:help GoInstallBinaries`

or

`:help :GoInstallBinaries` 

will show help for the `GoInstallBinaries`?

I can help with this but do not know how to do this.

**Comment by ray-x** [comment]
There should be a txt file in `doc` folder like this:
https://github.com/fatih/vim-go/blob/master/doc/vim-go.txt
However I did not even put a similar file in `doc` folder ATM :(

**Comment by rodrigc** [comment]
GoInstallBinaries and GoUpdateBinaries is now implemented and works great!
Thanks!!

I will try to help with docs in other PRs.
