### ISSUE TITLE
Feature Request: Support for neotest

### ISSUE THREAD

**Issue by Ydot19** [ray-x/go.nvim#492]
Is the project interested in adding support for neotest and if so, are contributions welcomed to add this capability.

**Comment by ray-x** [comment]
I don't use Neotest very often, but there's a Neovim plugin you might find interesting: [Neotest-Go](https://github.com/nvim-neotest/neotest-go). I'm not sure if there are many gaps that would require us to write new codes inside go.nvim to enable Neotest. 
I suggest integrating Neotest-Go first to see if anything missing. However, any contributions that can benefit the project are welcome.
My personal preference is using none-ls/null-ls and converting test failure to LSP error so you can use LSP tools e.g. trouble to show the errors
