### ISSUE TITLE
Inlay Hints dont work

### ISSUE THREAD

**Issue by ghost** [ray-x/go.nvim#495]
Hi,
I am using [LazyVim](https://lazyvim.github.io/) and I created a new file using your lazy config under the plugins directory. Everything works fine except for the inlay hints.

Could you please take a look?

Thanks!

**Comment by danilevy1212** [comment]
Same here, there seems to be something broken with how it is enabled here: https://github.com/ray-x/go.nvim/blob/abd282564a31c5dec14e2038ebf04fdac9ea3278/lua/go/inlay.lua#L322

<img width="856" alt="image" src="https://github.com/user-attachments/assets/f66287cd-89b6-4762-9b91-5025ece6a3a5">

I get this error continuously. I can confirm that disabling inline hints fixes the issue.

Looking at the `:help vim.lsp.inlay_hint`, seems line `enable` takes a boolean, not the bufn. the bufnr should be passed to the second argument.

```console
[dlevym@inspirion] ~ nvim --version
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1713773202
Run "nvim -V1 -v" for more info
```

**Comment by ray-x** [comment]
I think this one was fixed. Please check and re-open if you see issues after the update. Thanks
