### ISSUE TITLE
Gofmt/Goimport will add an extra line after go file.

### ISSUE THREAD

**Issue by nanozuki** [ray-x/go.nvim#5]
* minimal config file:

```lua
require('packer').startup(function (use)
  use 'ray-x/go.nvim'
end)
require('go').setup()
```

* steps

Create a new go project, just add `hello world` project, use nvim to open it, and call command `:Goimport` or `:Gofmt`.
And will get:

```go
package main

import (
        "fmt"
)

func main() {
        fmt.Println("hello, world")
}

```

There will be an extra line at end of the file. This is not the behavior of goimport/gofumport, and will let the linter warning.

**Comment by ray-x** [comment]
Strange
If the file is 
```
package main

import (
	"fmt"
)
func main() {
	fmt.Println("hello, world")
}


```
And I run Goimport
I got this:
```go
package main

import (
	"fmt"
)

func main() {
	fmt.Println("hello, world")
}
```

It seems to be ok.
Can you check the goimport

If you are using the default setup. You should be using `gofumports`/`gofumpt` and all of them are wrapped with golines

Maybe you can change the setup to 
```
let g:go_nvim_goimport="goimport"
let g:go_nvim_goimport_args=""
```
And check if it solve the problem.

**Comment by nanozuki** [comment]
It's possible because of the 'problem' of OS? I use macOS 11.4. And I called a command in the command line, the result looks well. Includes: 

```
golines --max-len=120 --base-formatter=gofumpt main.go
goimport -w main.go
gofumport -w main.go
```

And I add some `print` in `format.lua`: 

```lua
    args,
    {
      on_stdout = function(job_id, data, event)
        if not data or #data==1 and data[1] == "" then return end
        print("data")
        for i,v in ipairs(data) do print(i,v) end
        if not util.check_same(old_lines, data) then
          print("updating codes")
          api.nvim_buf_set_lines(0, 0, #data, false, data)
          api.nvim_command("write")
```

and the `data` also have an extra line.

**Comment by nanozuki** [comment]
I'll test it in Linux later. I add a line at `lua/go/format.lua` line.31: `if data[#data] == '' then data[#data] = nil end` for workaround.

**Comment by ray-x** [comment]
Hi, @nanozuki 
Thanks for working on that.
From your test, I think this issue may also affect other go tools, e.g. fillswitch.
Would be good to add checks
```lua 
if data[#data]== "" then
  table.remove(data, #data)
end
```

**Comment by ray-x** [comment]
Thanks for the PR Nanozuki?
