### ISSUE TITLE
Start with Inlay Hints un-toggled

### ISSUE THREAD

**Issue by den-is** [ray-x/go.nvim#508]
Hello,
I'm curious is it possible to start with InlayHints by default unToggled and Toggle them when needed?

In general my LSP gopls InlayHints setup is working.
But in all my editors I have InlayHints switched off by default and toggling them only when needed.

This is not the option I'm looking for:
```lua
        lsp_inlay_hints = {
          enable = false,
        },
```

I'm coming from another nvim Go plugin, but since this plugin is maintained and has more features I would like to stay with it.

**Comment by ray-x** [comment]
This should been fixed in the latest version. Update the ticket if you see other issues.

**Comment by den-is** [comment]
omg. I completely forgot to reply.
I don't need for Go (or any other plugin) to control my LSP config. LSP config and "related" features are controlled within LSP module in my neovim setup.

so for this Go plugin I have
```lua
        lsp_inlay_hints = {
          -- controlled in lspconfig configuration, <leader>i to toggle hints
          enable = false,
        },
```

**Comment by ray-x** [comment]
It is fine to use the Neovim native inlay setup/functions. 
The plugin and relevant functions were designed when Neovim did not support the inlay feature.
