### ISSUE TITLE
Keybindings for going to definition of functions?

### ISSUE THREAD

**Issue by rodrigc** [ray-x/go.nvim#53]
In the past, I used https://github.com/fatih/vim-go and could type `gd` to go to the definition of a Go function.

How do you recommend that I do the same with go.nvim?

Should I implement the keybindings shown in this blog:

https://www.chrisatmachine.com/Neovim/27-native-lsp/

Thanks for your support.

**Comment by rodrigc** [comment]
BTW, my neovim config is at:

https://github.com/rodrigc/neovim-setup/tree/main/.config/nvim

**Comment by ray-x** [comment]
Thanks for bring this up. I would say `go.nvim` should not override lsp setup which is also used by other language servers (e.g. tsserver, pyright)
E.g.  In python, you may already defined `gd` or `<c-]>` as goto definition. When you use go, you may expect the same behaviour.
It is true that for engineers use go for 90% of their time and used vim-go previous, they may find it will take some time to convert their setup from vim-go to go.nvim and nvim-lsp.  But for long time nvim-lsp user, they may find go.nvim a supplement to native lsp and relatively simple to setup.

**Comment by rodrigc** [comment]
That makes sense.  Does LSP have default keybindings, or do I need to specify them in my own config?
For example, do I need to take these keymappings from the nvim-lspconfig documentation and put it in my own config?

https://github.com/neovim/nvim-lspconfig/blob/026ab6bd54075cc8e095f9040f7912ffb708864d/README.md#keybindings-and-completion

**Comment by ray-x** [comment]
the lspconfig plugin does not provide a default keybinding. But as each lsp client need to provide a keybind when it is attached (in on_attach). Most people may copy/paste from the sample config file provided in the URL you mentioned.

So in your on_attach function, you will need to define all binding to the lsp functions. You can copy/paste from the sample config/on_attach function. You can also providing your own keybinding to some/all the mapping.

**Comment by rodrigc** [comment]
OK, I wrote my own on_attach function, and passed it to the setup of the rust_analyzer and gopls language servers here:

https://github.com/rodrigc/neovim-setup/blob/main/.config/nvim/lua/lsp.lua

Is this the correct approach?

**Comment by ray-x** [comment]
Yes. look good to me.

**Comment by rodrigc** [comment]
Thank you!
It looks like you have defined some key mappings like `the gd` in navigator.lua.
Is using navigator.lua instead of defining my own key mappings another approach?
https://github.com/ray-x/navigator.lua#default-keymaps

**Comment by rodrigc** [comment]
Thanks for your help, and patience explaining things to me.  I am new to lua, and only started neovim 3 weeks ago.

I logged into the Neovim Matrix chat server, and got a bit of help from @simrat39 , the author of the https://github.com/simrat39/rust-tools.nvim plugin.

Based on @simrat39's suggestions, I did the following:

1.  In https://github.com/rodrigc/neovim-setup/blob/main/.config/nvim/lua/lsp.lua , I created an `on_attach` function, and returned it from this file inside a map.
2.  In https://github.com/rodrigc/neovim-setup/blob/main/.config/nvim/lua/go.lua#L6 , I passed this `on_attach` function to `gopls.setup`
3.  In https://github.com/rodrigc/neovim-setup/blob/main/.config/nvim/lua/rust.lua#L47 , I passed this `on_attach` function to `rust-tools.setup`.  
4.  `rust-tools` passes lsp options from inside the `server` section: https://github.com/simrat39/rust-tools.nvim#configuration

So by doing this, I was able to create a single `on_attach` function, and pass it to lsp for go and rust.
I tested, and this works for go and rust.

I was a bit confused because the structure of go.nvim and rust-tools.nvim is slightly different, how they both interact with lsp.

Thanks for your support and your patience.

**Comment by ray-x** [comment]
go.nvim can work without lsp.
And you can use the default lsp setup from go.nvim
e.g. https://github.com/ray-x/go.nvim/blob/master/lua/go/lsp.lua
you can setup:
```
require("go").setup({
  lsp_cfg = true,
})

```

The plugin provided a basic on_attach and gopls setup so you can use gopls out of box.

**Comment by rodrigc** [comment]
Oh!  Thanks for pointing that out.
One question I have is that in my on_attach function, I initialize 

https://github.com/rodrigc/neovim-setup/blob/main/.config/nvim/lua/lsp.lua#L35

But in go/lsp.lua, ray-x/lsp_signature is not called: https://github.com/ray-x/go.nvim/blob/master/lua/go/lsp.lua#L9

Would I still need to pass in my own on_attach function?

Also, I saw some third party neovim configs where they pass the capabilities back to the lsp server, so I did that
too.  Is that really needed?  I don't understand all of the LSP api

Thanks.

**Comment by ray-x** [comment]
You can setup signature with this :
```
cfg = {...}
require'lsp_signature'.setup(cfg) -- no need to specify bufnr if you don't use toggle_key

```
By doing this, you do not need to do on_attach for each lsp on_attach.
If you want to pass on_attach to go.nvim you may need to do this
```

{
  lsp_cfg = true, -- false: use your own lspconfig
  lsp_on_attach = your_go_on_attach, -- use on_attach from go.nvim
}
```


capabilities setup is not necessary. Unless you really need that. E.g. disable format capability, enable signature etc. That depends on lsp server default setup.

**Comment by rodrigc** [comment]
I saw this comment on Reddit regarding go.nvim keybindings for DAP/debugger integration: https://www.reddit.com/r/neovim/comments/rexqf4/comment/hod6y78/?utm_source=share&utm_medium=web2x&context=3

Any thoughts on it?

**Comment by ray-x** [comment]
Thanks for sharing me the URL. The GoDebug stop will unmap keys. maybe I need to check how to unmap the keys automatically when session stops.

**Comment by rodrigc** [comment]
Thank you for your support.

**Comment by rodrigc** [comment]
I am still having a slight problem, that I hope you can assist with.

1.  My init.lua is here: https://github.com/rodrigc/neovim-setup/blob/main/.config/nvim/init.lua
2.  I load `ray-x/go.nvim` here: https://github.com/rodrigc/neovim-setup/blob/main/.config/nvim/lua/plugins.lua#L65
3.  In init.lua, I load the go config from here: https://github.com/rodrigc/neovim-setup/blob/main/.config/nvim/init.lua#L9
4.  In the go setup, on this line: https://github.com/rodrigc/neovim-setup/blob/main/.config/nvim/init.lua#L9, I do:
```lua

require('go').setup({lsp_cfg = true, lsp_on_attach = lsp.on_attach})
```

When I edit a Go file, things are mostly working, but I get this error:

```
LSP[gopls] unexpected gopls setting "filetypes"
```

Any idea what causes this?

I am using:

```
golang.org/x/tools/gopls v0.7.4
    golang.org/x/tools/gopls@v0.7.4 h1:hw8cpqjio1iMwIKbbDkG3MeW4l8R9dY/yqOHqv7HImA=
```

**Comment by ray-x** [comment]
Seems I have a duplicate key for filetypes. Should be fixed now

**Comment by rodrigc** [comment]
Thanks!  I verified the fix.

**Comment by rodrigc** [comment]
I have one other question.  In the code, I see lsp_cfg is always defined as a boolean.

But in this section, it is a table: https://github.com/ray-x/go.nvim/blob/3fe0c3ededbeb3d6ad35fee87ec4071cf3fe6cc7/lua/go/lsp.lua#L140

How can lsp_cfg be used as a table instead of a boolean?

**Comment by ray-x** [comment]
lua is week type
 
```lua
if expression then
   print("true")
else
   print("false")
end
```
it will print "true" when `expression` is not nil (e.g. a table, even a empty table like `{}`, or a number etc), or it is boolean `true`
if it is nil, false it will print `false`

**Comment by rodrigc** [comment]
Ah, OK that makes sense.  I put some wording in the README which clarified things a bit for me:
https://github.com/ray-x/go.nvim/pull/61

**Comment by rodrigc** [comment]
There are some confusing things in the code.
1.  It looks like `lsp_cfg` **and** `lsp_on_attach` must **both* be not nil, otherwise the keybindings for `gd` are not active
2. in README.md, it shows that `lsp_on_attach = true` by default.  However in `doc/go.txt`, and in `lua/go/lsp.lua`, `lsp_on_attach = nil` by default.  So there will be no `on_attach` function passed to lsp.  This is a bit confusing.

**Comment by ray-x** [comment]
lsp_on_attach is false in README now.  lsp_on_attach by default nil.
