### ISSUE TITLE
Quickfix layout of test

### ISSUE THREAD

**Issue by imkerberos** [ray-x/go.nvim#54]
Thanks you for this great plugin.

When open an outline buffer, the quickfix of test result is below outline buffer.
See image:
![image](https://user-images.githubusercontent.com/636187/146014139-58d2898a-839c-48e2-95a0-2080b8499fc4.png)

I think it shoule be this layout:
![image](https://user-images.githubusercontent.com/636187/146014637-c5e4ddec-3d2d-471e-9f4e-dbc8eebbd370.png)

**Comment by ray-x** [comment]
you are right. submitted a fix for it

**Comment by imkerberos** [comment]
Thanks ray-x for your support!
