### ISSUE TITLE
Run test error of 'errorformat' after commit "41a5a3e08e58864f7c2fc1dd9c36ee0754518c5d"

### ISSUE THREAD

**Issue by imkerberos** [ray-x/go.nvim#55]
After commit hash "41a5a3e08e58864f7c2fc1dd9c36ee0754518c5d", It's always failed when run test.
error message:
`
...nvim/site/pack/packer/start/go.nvim/lua/go/asyncmake.lua:80: Failed to get value for option 'errorformat'
stack traceback:
^I[C]: in function 'nvim_buf_get_option'
^I...nvim/site/pack/packer/start/go.nvim/lua/go/asyncmake.lua:80: in function <...nvim/site/pack/packer/start/go.nvim/lua/go/asyncmake.lua:66>
`

**Comment by ray-x** [comment]
Which command you are running?

**Comment by imkerberos** [comment]
GoTestFunc

**Comment by imkerberos** [comment]
@ray-x thanks for your help.
