### ISSUE TITLE
Can't run test in path which contains some special characters.

### ISSUE THREAD

**Issue by imkerberos** [ray-x/go.nvim#56]
If the test file path contains special characters such as ' ', '-'. Can't run "GoTestFunc".
For example:
"/Users/imkerberos/tmp/This is a - special path/MyProject". Neovim will output:

`
E5108: Error executing lua ...re/nvim/site/pack/packer/start/go.nvim/lua/go/gotest.lua:234: Vim(setlocal):E518: Unknown option: a 
stack traceback:
	[C]: in function 'cmd'
	...re/nvim/site/pack/packer/start/go.nvim/lua/go/gotest.lua:234: in function 'test_fun'
	[string ":lua"]:1: in main chunk
`

I think should escape the path when run test. But I can't fix it because I don't understand lua.

**Comment by imkerberos** [comment]
@ray-x You are so quick!!!

**Comment by ray-x** [comment]
Thanks, I have never used folders with special chars.  I think it should work now.

**Comment by imkerberos** [comment]
It's still error message in quickfix.
`
|| stat /Users/I553461/tmp/This: directory not found
|| package is is not in GOROOT (/usr/local/Cellar/go/1.17.5/libexec/src/is)
|| package a is not in GOROOT (/usr/local/Cellar/go/1.17.5/libexec/src/a)
|| malformed import path "-": leading dash
|| package special is not in GOROOT (/usr/local/Cellar/go/1.17.5/libexec/src/special)
|| package path/apii/pkg/services/enrichmentrule/api is not in GOROOT (/usr/local/Cellar/go/1.17.5/libexec/src/path/apii/pkg/services/enrichmentrule/api)
`
I'm going to create a demo project for you.

**Comment by imkerberos** [comment]
@ray-x Please refer https://github.com/imkerberos/go.nvim.demo

**Comment by ray-x** [comment]
yes. I can reproduce it. Seems to relate to the shell you are using.
I pushed another update, please check if it works

**Comment by imkerberos** [comment]
It's fixed. Thanks you ray-x.
