### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by tom-on-the-internet** [ray-x/go.nvim#58]
Hello!

I apologize for posting this issue because I think my issue is not related to your plugin. But I thought I would ask.

Your screen shots so great syntax highlighting for Go.

![image](https://user-images.githubusercontent.com/8356936/146698788-d4780097-dbf2-4376-9129-ff81de280676.png)

But I have very little syntax highlighting.

![image](https://user-images.githubusercontent.com/8356936/146698808-8b05124b-0924-4350-8b2a-268bd643066a.png)

Do you have any ideas why I have very little syntax highlighting? I have syntax highlighting in other languages.

Thanks again

**Comment by ray-x** [comment]
I think you are using the default highlight provided by neovim.
The screenshot is from treesitter highlight. Please install nvim-treesitter plugin and add treesitter parser for go and enable the highlight.

**Comment by tom-on-the-internet** [comment]
Thank you Ray. I thought I had set tree sitter up properly. I'll look into this. Doesn't seem to be working for me!
Thanks again for the plugin.

**Comment by tom-on-the-internet** [comment]
If anyone is running into the issue of missing syntax highlighting for Go, my issue was exactly what Ray posted above.
I had tree sitter installed, but the parsers were not installed. I though `TSUpdate` installed parsers, but I guess it does not.

I added `ensure_installed` to my treesitter setup

ex from Ray's dotfiles:

```
    ensure_installed = {
      "go", "css", "html", "javascript", "typescript", "jsdoc", "json", "c", "java", "toml", "tsx",
      "lua", "cpp", "python", "rust", "jsonc", "dart", "css", "yaml", "vue"
    }
```
