### ISSUE TITLE
GoCoverage throw error and feature request: enable -tags on GoCoverage

### ISSUE THREAD

**Issue by tempegarit** [ray-x/go.nvim#65]
Hi! First of all, thanks for this amazing plugins. It really speed up coding.

I've never used this but today i used `:GoCoverage` and this error was thrown:

`E5108: Error executing lua Vim:E730: using List as a String
stack traceback:
        [C]: in function 'jobstart'
        .../nvim/site/pack/packer/start/go.nvim/lua/go/coverage.lua:268: in function 'run'
        [string ":lua"]:1: in main chunk`

One more thing. It would be great if we can add tags on coverage like this:
`:GoCoverage -tags=sqlite_fts5`

But it seems like it doesn't support adding `-tags` on `:GoCoverage` now based on what i've read on the readme. Is it possible to add `-tags` to `:GoCoverage`?

Thanks.

**Comment by ray-x** [comment]
With the bug fix, you should be able to run 
`:GoCoverage -tags=sqlite_fts5`

**Comment by tempegarit** [comment]
It's still not working. When i run `:GoCoverage`, it throws this error:

go coverage finished with message: { "go", "test", "-coverprofile", "/home/pc/projects/sqlitedb/cover.cov" }error: { "no Go files in /home/pc/projects" }job9evstderr
Press ENTER or type command to continue
Vim:E484: Can't open file /home/pc/projects/sqlitedb/cover.cov
Press ENTER or type command to continue
stack traceback:
Press ENTER or type command to continue
^I[C]: in function 'readfile'
Press ENTER or type command to continue
^I.../nvim/site/pack/packer/start/go.nvim/lua/go/coverage.lua:190: in function 'read_cov'
Press ENTER or type command to continue
^I.../nvim/site/pack/packer/start/go.nvim/lua/go/coverage.lua:291: in function <.../nvim/site/pack/packer/start/go.nvim/lua/go/coverage.lua:286> function: builtin#18
Vim:E484: Can't open file /home/pc/projects/sqlitedb/cover.cov
Press ENTER or type command to continue
stack traceback:
Press ENTER or type command to continue
^I[C]: in function 'readfile'
Press ENTER or type command to continue
^I.../nvim/site/pack/packer/start/go.nvim/lua/go/coverage.lua:190: in function 'read_cov'
Press ENTER or type command to continue
^I.../nvim/site/pack/packer/start/go.nvim/lua/go/coverage.lua:291: in function <.../nvim/site/pack/packer/start/go.nvim/lua/go/coverage.lua:286> function: builtin#18
Vim:E484: Can't open file /home/pc/projects/sqlitedb/cover.cov
Press ENTER or type command to continue
stack traceback:
Press ENTER or type command to continue
^I[C]: in function 'readfile'
Press ENTER or type command to continue
^I.../nvim/site/pack/packer/start/go.nvim/lua/go/coverage.lua:190: in function 'read_cov'
Press ENTER or type command to continue
^I.../nvim/site/pack/packer/start/go.nvim/lua/go/coverage.lua:291: in function <.../nvim/site/pack/packer/start/go.nvim/lua/go/coverage.lua:286>
Press ENTER or type command to continue

**Comment by ray-x** [comment]
you have to run this command when your at you root folder of your go project. Or same folder of your test files.

/home/pc/projects does not seems to be a root folder of a go project to me.

**Comment by tempegarit** [comment]
> you have to run this command when your at you root folder of your go project. Or same folder of your test files.
> 
> /home/pc/projects does not seems to be a root folder of a go project to me.

`/home/pc/projects` is the root folder. `projects` is the name of the project.

Here's the directory structure:
`$ pwd`
/home/pc/projects

`$ tree`
.
├── go.mod
├── go.sum
└── sqlitedb
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;├── db.go
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;└── db_test.go

**Comment by ray-x** [comment]
Ok. seems there are no go files in workspace folder top level. I pushed an update to fix that.
Also, you can specify the package for the coverage tests.

**Comment by tempegarit** [comment]
It works now. Thanks mate.

**Comment by ray-x** [comment]
G
