### ISSUE TITLE
:GoLint, causes asyncmake.lua  Invalid %( in format string

### ISSUE THREAD

**Issue by rodrigc** [ray-x/go.nvim#68]
When I tried to run:

```
:GoLint
```

I just got this:

```
stack traceback:
^I[C]: in function 'setqflist'
^I...nvim/site/pack/packer/start/go.nvim/lua/go/asyncmake.lua:104: in function <...nvim/site/pack/packer/start/go.nvim/lua/go/asyncmake.
lua:77> function: builtin#18 Vim:E377: Invalid %( in format string
```

Any ideas what might be causing this?

**Comment by rodrigc** [comment]
I don't know how to reproduce this,
but I ran `:GoLint` in a repository that
did not have an updated `go.mod / go.sum` file.

When I updated `go.mod / go.sum` in my tree, this problem went away and I was able to successfully run `:GoLint`.

Any idea how the code in `go.nvim` could be made more robust and display a more helpful error message?

**Comment by ray-x** [comment]
Thanks.
It was caused by the error message of 'go mod not found'
I updated the code so it will handle those messages.

**Comment by rodrigc** [comment]
Thanks I verified the fix.  Now I got a more useful error message after running `:GoLint`:

```
| Running error: context loading failed: failed to load packages: failed to load with go/packages: err: exit status 1: stderr: go: myrepo@v0.0.0-20181210034025-5253adc5f75d: missing go.sum entry; to add it:\n\tgo mod download myrepo\ngo: myrepo@v0.0.0-20181210034025-5253adc5f75d: missing go.sum entry; to add it:\n\tgo mod download myrepo\n
```

**Comment by ray-x** [comment]
Great!

**Comment by rodrigc** [comment]
@ray-x I started some new Go development, and using go.nvim, my experience is excellent.
I have all the functionality I had with https://github.com/fatih/vim-go , but the experience is better with neovim, treesitter, etc.

Thanks for the great work!

**Comment by ray-x** [comment]
I am glad you enjoy the plugin!
