### ISSUE TITLE
Need help with :GoCoverage and :GoTestFunc

### ISSUE THREAD

**Issue by linxGnu** [ray-x/go.nvim#75]
First of all, thank you so much for great plugin :heart: 

#### `:GoCoverage`:

![Screenshot from 2022-01-13 13-18-59](https://user-images.githubusercontent.com/20961936/149265251-9f71cea6-78a0-40e7-8a6b-d80038aea496.png)

In short, `GoCoverage` could not find the package (where current buffer is) to perform test coverage. Note that: `GoTestPkg` runs fine (detectable)

#### `:GoTestFunc`

Seem like `GoTestFunc` is performing `go test ./...` which search for run-able test not only in current package (where current buffer is), but also all packages inside my workspace. Thus result in bloat of `Skip package, no test to run`

Could you please help @ray-x

**Comment by ray-x** [comment]
You can use `GoCoverage ./...` as well.
If still failing, then please post your folder structure and also check if you have plugin like rooter.nvim that reset the root folder?

**Comment by linxGnu** [comment]
@ray-x 

How do you think if:
- I think it's better to set default arg is `./...` for `GoCoverage`. In this way, user just type: `GoCoverage`, no need to set `./...`. 
- How about having a special tag (similar to `--toggle`) to run coverage for package (which contains current buffer)? It will help many projects with multi-package/complex structure. Some project takes lot of time to run all unit tests. Partially cover only necessary package (especially current package contains current buffer)?

And could you please also check the `GoTestFunc` on multi-package project:
```
|- pkg1
|- pkg2
|----pkg3
|- main.go
```

**Comment by ray-x** [comment]
By default, the GoCoverage will set package to `./...`. But be careful lots of plugins will set root folder to `.git` . So that means `./...` will run all tests  (instead of the current file folder)
`GoTestFunc` will grep function name identified by treesitter. So it should work out of box in the different package structures.

**Comment by linxGnu** [comment]
@ray-x 
I am sorry if my question is unclear. Here is the screenshot:

![Screenshot from 2022-01-13 15-14-19](https://user-images.githubusercontent.com/20961936/149275788-69dcda67-704d-4c53-b734-f4a57102c1c8.png)

As you could see: many `Skip` package. It means that the plugin is performing `go test -v ^Test ./...` right?

**Comment by linxGnu** [comment]
The behavior of `GoTestPkg` is quite correct

![Screenshot from 2022-01-13 15-21-59](https://user-images.githubusercontent.com/20961936/149276613-e88549af-33ba-483e-a8c3-3671c323f72d.png)

As you could see, no `Skip`, no scan through `./...`

**Comment by linxGnu** [comment]
@ray-x yes. I wonder why it scan other package? 

Due to scanning other package, the log is printed with many “Skip warning”

**Comment by linxGnu** [comment]
Lets say I am standing at Package A. The plugin scan and run test not only in A but also in B. Is it expected bahavior?

**Comment by ray-x** [comment]
I think it can be too many info for GoTestFunc and GoTestFile.  Did some updates to the plugin.

**Comment by linxGnu** [comment]
You are awesome @ray-x let me check and feedback soon. Thank you so much

**Comment by linxGnu** [comment]
Thank you so much. I have checked new fix, it's much better than before. Thank you very much for the support.
