### ISSUE TITLE
GoTestCompile

### ISSUE THREAD

**Issue by renkam** [ray-x/go.nvim#76]
vim-go offers nice command `GoTestCompile` to only compile current file and check if it builds. Implemented as: 
https://github.com/fatih/vim-go/blob/c1fc27a5ad95589558f3083b0ece9d4d8f74ab18/ftplugin/go/commands.vim#L50
which calls `go test` with `-c` flag. It is very useful.

I've tried same thing with go.nvim by calling `GoTest -c` but got error `cannot use -c flag with multiple packages`

Is there any other way that I can only check if my files compile?

**Comment by ray-x** [comment]
Added -c option to GoTest

**Comment by renkam** [comment]
Looks like the command works, thanks for quick fix, it also opens quickfix window on errors, but output is messed up.
On every line it prepends `||` so jumping to file:line error location is not working as expected.
Also for a simple case when only `main.go` exists command should finish without reporting that no test files exist (if no compile errors).

**Comment by ray-x** [comment]
I updated efm and it should work now.

**Comment by renkam** [comment]
Its working.

Just two minor things.

1. Is there a way to jump to first error if compilation fails?
2. How can I avoid opening quickfix if there are no errors?
