### ISSUE TITLE
GoImport doesn't also run GoFmt

### ISSUE THREAD

**Issue by wavded** [ray-x/go.nvim#83]
https://github.com/ray-x/go.nvim#run-gofmt--goimport-on-save

This documentation makes me think that GoImport command also would run GoFmt but it seems it only runs the `goimport` tool. Is this correct?

**Comment by pbar1** [comment]
`goimports` (somewhat surprisingly) formats your code via `go fmt` in addition to the rest of its functionality, so `go fmt` is redundant there.

[Here's a link mentioning that](https://pkg.go.dev/golang.org/x/tools/cmd/goimports#pkg-overview)

**Comment by wavded** [comment]
Thanks for the info @pbar1. However, in my case, `:GoFmt  runs `golines` with `gofumpt` which `goimports` does not and I cannot figure out a way to do that with this tool that works on save, as they both seem to run asynchronously, overwriting each other in strange ways.

**Comment by ray-x** [comment]
You can config 
` {goimport = 'gopls'}` so it will use gopls to import the packages. And then format the code in a synchronise way.

The if using `goimports` by setting ` {goimport = 'goimports'}` , the way GoImport works is calling
```
golines --max-len=120 --base-formatter=goimports
```

I would suppose it will run golines first and format with `goimports`

**Comment by akinsho** [comment]
This might be worth creating a separate issue but I stumbled upon this whilst trying to get `golines` working and having switched my `goimport` command I'm now getting notifications every time I save (since I use a `BufWritePost` autocommand). Is there any way to turn off the notifications or opt out of them?
https://github.com/ray-x/go.nvim/blob/192486892bb01217db342d690f812b95da91b475/lua/go/format.lua#L20-L21

**Comment by wavded** [comment]
For anyone coming back to this, I was able to get this to work with the following configuration:

```lua
require("go").setup({
  goimport = "goimports"
})

vim.api.nvim_exec(
  [[ autocmd BufWritePre *.go :silent! lua require('go.format').goimport() ]],
  false
)
```

Using the default `gopls` wouldn't use `golines`.

**Comment by alphatroya** [comment]
I do

> For anyone coming back to this, I was able to get this to work with the following configuration:
> 
> ```lua
> require("go").setup({
>   goimport = "goimports"
> })
> 
> vim.api.nvim_exec(
>   [[ autocmd BufWritePre *.go :silent! lua require('go.format').goimport() ]],
>   false
> )
> ```
> 
> Using the default `gopls` wouldn't use `golines`.

I tried that, but looks like not goimports not call golines for now.
`:GoFmt` works fine
