### ISSUE TITLE
Rendering bug when typing parens with error on the same line

### ISSUE THREAD

**Issue by raine** [ray-x/go.nvim#84]
Firstly, thanks for the great plugin!

Now, I'm experiencing this rendering bug when typing parens on a line that also has errors on it.

It doesn't happen if there is no inline error message on that line, and it doesn't seem to be appearing when typing anything else than parenthesis.

You can see it on the gif below. Notice how the whole thing in parens jumps left one character.

![Kapture 2022-02-13 at 20 16 53](https://user-images.githubusercontent.com/11027/153768882-da1631ff-b420-4415-88bb-989a5e33b46b.gif)

Any idea what might be causing this? It's extremely distracting and have never seen anything like this with other plugins in my vim setup over the many years.

**Comment by ray-x** [comment]
Well, it is not a bug. Seems to me it is a feature of vim diagnostic. It will generate diagnostic message on the fly. You can disable it by using.
How to disable the message depends on version of you neovim. I think you like to disable either virtual text or disable diagnostic when editing.
Chech `help vim.lsp.diagnostic.on_publish_diagnostics` for more info.

**Comment by raine** [comment]
Rendering bug is the best way I could describe it. The text should definitely not move like that.

Anyway, I think I figured it out.

`spacing = 0` set to `virtual_text` appears to be the reason for the problem.

**Comment by ray-x** [comment]
did you try:
`update_in_insert = false` ?

**Comment by raine** [comment]
Yeah or I just went with `virtual_text = true` for now.
