### ISSUE TITLE
Sample vimrc :GoCmt and :GoAddTest showing lua errors

### ISSUE THREAD

**Issue by timchurchard** [ray-x/go.nvim#86]
Using the sample vimrc from the README I get a lua error when trying :GoCmt - with cursor on the func main line or inside the function body
```
Unable to find any nodes. place your cursor on a go symbol and try again                                                                                            
Unable to find any nodes. place your cursor on a go symbol and try again
Unable to find any nodes. place your cursor on a go symbol and try again
WARN: struct not found
Unable to find any nodes. place your cursor on a go symbol and try again
WARN: interface not found
E5108: Error executing lua /root/.vim/plugged/go.nvim/lua/go/comment.lua:50: attempt to index local 'ns' (a nil value)
stack traceback:
        /root/.vim/plugged/go.nvim/lua/go/comment.lua:50: in function 'gen'
        [string ":lua"]:1: in main chunk
```

And when using :GoAddTest
```
Unable to find any nodes. place your cursor on a go symbol and try again
```

I've created a gist with a Dockerfile reproducing my setup and showing the bug here:https://gist.github.com/timchurchard/158027f28a7597bdd67ba97ecde67406

**Comment by ray-x** [comment]
I looked into you dockerfile. I think it might releated to go treesitter parser not installed.
Could you run `checkhealth` and see if you have anything warning.

**Comment by timchurchard** [comment]
Thank you, that was exactly the problem. The solution was `:TSInstall go` to install the parser. It did not appear on the `:checkhealth`.

Looking at docker diff it seems these files were added. But I'm not familiar enough with lua or nvim plugins to add a health check.
```
C /root/.vim/plugged/nvim-treesitter
C /root/.vim/plugged/nvim-treesitter/parser
A /root/.vim/plugged/nvim-treesitter/parser/go.so
C /root/.vim/plugged/nvim-treesitter/parser-info
A /root/.vim/plugged/nvim-treesitter/parser-info/go.revision
```

**Comment by ray-x** [comment]
Thanks, I updated the README and healthcheck script for the treesitter parser
