### ISSUE TITLE
Compatibility with hrsh7th/nvim-cmp

### ISSUE THREAD

**Issue by raine** [ray-x/go.nvim#88]
Hello again,

[hrsh7th/nvim-cmp](https://github.com/hrsh7th/nvim-cmp/)'s README has this section about LSP in recommended configuration:

```lua
-- Setup lspconfig.
local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())
-- Replace <YOUR_LSP_SERVER> with each lsp server you've enabled.
require('lspconfig')['<YOUR_LSP_SERVER>'].setup {
  capabilities = capabilities
}
```

I ended up doing this:

```lua
-- nvim/init.vim

local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())
-- somewhere below
require 'go'.setup({
  -- ...
  capabilities = capabilities
})
```

And of course I had to make this change in your plugin at `lua/go/gopls.lua` in order to pass `capabilities` from setup call.

```diff
diff --git i/lua/go/gopls.lua w/lua/go/gopls.lua
index 9190aec..e125698 100644
--- i/lua/go/gopls.lua
+++ w/lua/go/gopls.lua
@@ -115,7 +115,7 @@ function M.version()
 end
 
 local setups = {
-  -- capabilities = cap,
+  capabilities = _GO_NVIM_CFG.capabilities,
   filetypes = { "go", "gomod", "gohtmltmpl", "gotexttmpl" },
   message_level = vim.lsp.protocol.MessageType.Error,
   cmd = {
```

What do you think? Is there a better way? Should you make go.nvim take `capabilities` as argument in setup?

Thanks in advance for taking time to think about this.

p.s. I'm a complete LSP noob.

**Comment by ray-x** [comment]
I think you only need to do 
```
local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())
-- somewhere below
require 'go'.setup({
  -- ...
  capabilities = capabilities
})

```
But I also pushed a version that turn on the snippet by default

**Comment by raine** [comment]
So looking at the readme and the code,

```
lsp_cfg = {
  capabilities = capabilities
}
```

in `require 'go'.setup()` should get merged with the built-in lsp configuration over at https://github.com/ray-x/go.nvim/blob/d8638ab9c84e4154493ddadea995e3be078a3e16/lua/go/gopls.lua#L117

Brilliant. Thanks!

**Comment by raine** [comment]
Any ideas how to integrate with [coq.nvim](https://ms-jpq.github.io/coq_nvim)?

The official instruction for LSP is:

```lua
local lsp = require "lspconfig"
local coq = require "coq" -- add this

lsp.<server>.setup(<stuff...>)                              -- before
lsp.<server>.setup(coq.lsp_ensure_capabilities(<stuff...>)) -- after
```

Not sure what would be the best way to override https://github.com/ray-x/go.nvim/blob/0fe0a9ee3367f7bd1e9c9ab30d5b7d5e66b83fc6/lua/go/lsp.lua#L114
