### ISSUE TITLE
Request; reload functionality

### ISSUE THREAD

**Issue by Davincible** [ray-x/go.nvim#89]
Sometimes gopls needs to be reloaded, for example after running a `go get xxx`, or `go mod tidy` to detect new imports, or after making a change in a imported library, gopls does not detect it immediately (understandable).

So far I have been using `https://github.com/famiu/nvim-reload` to reload my entire nvim, which also restarts gopls. However, this is a bit much and spawns way too many LSP servers.

Would it be possible to create a command here to reload gopls?

**Comment by ray-x** [comment]
You can use `LspRestart` to restart gopls

**Comment by Davincible** [comment]
Oeh sweet. Makes more sense. Thanks
