### ISSUE TITLE
GoTestFunc got error

### ISSUE THREAD

**Issue by tinytub** [ray-x/go.nvim#9]
run GoTestFunc in my test function and got an error

```
E488: 多余的尾部字符: :Gmake -run ..
```
Is there some dependence I missed ?

**Comment by ray-x** [comment]
My bad.
There were some missing pieces. 
I fixed that and also made some improvements. Thanks

**Comment by Rizary** [comment]
@ray-x when I run `:GoTestFunc` I got an error `Unable to find any nodes. Is your query correct?`.

In my understanding, I need to point the cursor to the test function and run the above command. Any idea?

**Comment by ray-x** [comment]
You should be able to test current function if the cursor is inside the test function scope. (anywhere from function name to end of the function

**Comment by Rizary** [comment]
@ray-x yes, I placed the cursor in the function name but still got the `unable to find any nodes` error. I already install gotests and available on my path.

**Comment by Rizary** [comment]
@ray-x I want to test this function: https://github.com/0chain/gosdk/blob/rizary-wallet-zboxsdk/wasm/wallet_test.go#L21

normally we use `GOOS=js GOARCH=wasm go test -v github.com/0chain/gosdk/wasm -run TestSetWalletInfo`

**Comment by ray-x** [comment]
![image](https://user-images.githubusercontent.com/1681295/131774818-c17075bb-81c6-4292-99e7-39048156dcec.png)

Suppose you export GOOS and GOARCH before you run neovim.
It should work.

Did you update and install treesitter? That is required to parse the function name.

**Comment by Rizary** [comment]
@ray-x thank you, it seems I have not setup the treesitter well. Thanks again for the plugin, it helps me as nvim beginner.
