### ISSUE TITLE
GoTest doesn't open floating window

### ISSUE THREAD

**Issue by prurph** [ray-x/go.nvim#92]
When I use `GoTest` I see `go test -v <my directory> finished` but no window pops up with the results. Running from the command line produces the expected test output.

Any pointers on how I might debug this? I'm using the sample vimrc from this repo so I'm not sure what could be going wrong.

Specs:

- MacOS 12.1
- Terminal: Kitty
- nvim 0.7.0
- Using the [sample vimrc](https://github.com/ray-x/go.nvim#sample-vimrc) linked in this project

**Comment by ray-x** [comment]
how about `copen` to open the quickfix.
Also float windows disable the float windows by default, as it depends on guihua.lua

**Comment by prurph** [comment]
Ugh, I'm so sorry—I didn't realize the default was false for floating. 🤦 

Working great now, thanks!
