### ISSUE TITLE
Feature: GoImport tab completion

### ISSUE THREAD

**Issue by ldelossa** [ray-x/go.nvim#94]
Hey there,

One thing I am missing from `vim-go` a lot is tab completion after "GoImport". 

This is very helpful when working in a large codebase with many depedencies.

**Comment by ray-x** [comment]
Feature added in the latest version.

**Comment by ldelossa** [comment]
Hey @ray-x finally got around to trying this. It does not work correctly for me. Its easier to show with a video. 

https://user-images.githubusercontent.com/5642902/164786747-a8f3628e-2720-4349-b3fa-2e26eb95adb6.mp4

As you can see, I can't complete anything other then "github<tab>". So this isn't very useful, since it gives me a giant list I need to scroll thru anyway.

**Comment by ray-x** [comment]
<img width="207" alt="image" src="https://user-images.githubusercontent.com/1681295/164889635-8ac515d5-2a6a-4b97-9454-4030be482b6e.png">
It can import standard pkg e.g. fmt/strings...

**Comment by ldelossa** [comment]
Ah I see. Its not intended to work with the packages found in go.mod or package cache?

**Comment by ray-x** [comment]
Correct. it trying to import available packages.

**Comment by ldelossa** [comment]
In vim-go auto complete works for any packages used throughout the current project, including all third party packages pulled in from go.mod. 

In fact, your implementation does show them all, its just not doing shortest prefix matching on the strings.

**Comment by ray-x** [comment]
I think those should from `completeopt` and `wildmode` setup

**Comment by ray-x** [comment]
Yes, it re-use gopls list package feature.
The package can be filter with wild match , e.g. `GoImport g*aws<Tab>`

**Comment by ldelossa** [comment]
Hmm, does not work for me.

**Comment by ray-x** [comment]
I uploaded a short video to youtube
https://youtu.be/0lpsDc_mJMs?t=137

**Comment by ldelossa** [comment]
Ohh, I see. it works when I follow your example. Thanks!
