### ISSUE TITLE
GoAlt not working correctly

### ISSUE THREAD

**Issue by ldelossa** [ray-x/go.nvim#95]
Hello,

When using `GoAlt` it correctly moves from the test file to the source code.

However, when moving from the source code to the test file it opens a file called '~/git_test.go` instead.

**Comment by ray-x** [comment]
moving from source to test depends on `    alt_file = vim.fn.expand('%:r') .. "_test.go"`
When you opened source, what is the output of `echo expand('%:r')` from vim cmd line? It is strange why would it be `git`. Also are you in the latest master and what is your operating system?

**Comment by ray-x** [comment]
@ldelossa 
Do you still see this issue? Could you share more info on how to reproduce it?
