### ISSUE TITLE
wrong compiler error messages

### ISSUE THREAD

**Issue by iltoga** [ray-x/go.nvim#97]
wrong compiler error messages (using vstudio code these messages don't show up).
GoTestFunc runs the test without issues both in neovim (lunarvim) and vscode 

![image](https://user-images.githubusercontent.com/2296264/158622986-9585a9fc-f8a4-41d5-bb91-a3e85fbf5250.png)

installed latest gopls and latest go.nvim

**Comment by iltoga** [comment]
errata corrige: setting lsp_cfg = false in configuration solves the issue. Eg:

```
          require 'go'.setup({
            goimport = 'gopls', -- if set to 'gopls' will use golsp format
            gofmt = 'gopls', -- if set to gopls will use golsp format
            max_line_len = 120,
            tag_transform = false,
            test_dir = '',
            comment_placeholder = '   ',
            lsp_cfg = false, -- false: use your own lspconfig
            lsp_gofumpt = true, -- true: set default gofmt in gopls format to gofumpt
            lsp_on_attach = true, -- use on_attach from go.nvim
            dap_debug = true,
          })
```

**Comment by ray-x** [comment]
looks like a gopls false alarm. Could you update it to latest?

**Comment by ray-x** [comment]
I saw the same thing today, with go1.18 :(

**Comment by ray-x** [comment]
This was fixed in upstream(gopls)
